### ISSUE TITLE
Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by nethravathi95** [chapter-three/next-drupal#122]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/54062543/158370369-a0d02191-fba4-43c6-ae1f-59845287f3c8.png">

Nextjs for drupal Authentication am getting fetch error on
 invalid JSON response body at http://localhost/drupalnextjs/oauth/token reason: Unexpected token T in JSON at position 0.

I googled this issue and find that I should add the User-Agent header to my request but this did not solve my problem.

I am new to Next.js, I don't know what is reason any help would be appreciated.

**Comment by shadcn** [comment]
@nethravathi95 ok let's see. Is there anything in the Drupal logs? Under Reports → Recent log messages?

**Comment by nethravathi95** [comment]
![image](https://user-images.githubusercontent.com/54062543/158378603-d15a8c9e-98f8-4d14-8fd5-d5db8b9c9b02.png)

This is my recent log message

**Comment by shadcn** [comment]
Which php version are you on?

**Comment by shadcn** [comment]
simple_oauth `5.2.0` requires php `7.4`

**Comment by nethravathi95** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/54062543/158387037-e87a9ba9-9844-4d9f-bd95-fb2a6062dbe3.png">

yes its 7.4 php version am using 

> simple_oauth `5.2.0` requires php `7.4`

**Comment by shadcn** [comment]
This issue is happening when you're implementing the password grant? or when fetching data in pages?

**Comment by nethravathi95** [comment]
This issue happing with the password grant 

> This issue is happening when you're implementing the password grant? or when fetching data in pages?

**Comment by shadcn** [comment]
@nethravathi95 Can you send us some code sample on the Next.js side? Are you using next-auth?

**Comment by nethravathi95** [comment]
@shadcn yes am using next auth

**Comment by nethravathi95** [comment]
nextjs.zip
<https://drive.google.com/file/d/1jFf3mUCqTi16Y341bsPHBS7fQ0nqBd9X/view?usp=drive_web>

**Comment by shadcn** [comment]
@nethravathi95 I was looking into this yesterday and found a few things.

I wrote down a guide here: https://gist.github.com/shadcn/819d842b7b5644f88772f460e223c467

Can you take a look and let me know?

**Comment by nethravathi95** [comment]
@shadcn This guide is related to Authorization Code Grant which works fine before reporting the issue. I need a solution for the password grant which gives an error called Unexpected token T in JSON at position 0 

> @nethravathi95 I was looking into this yesterday and found a few things.
> 
> I wrote down a guide here: https://gist.github.com/shadcn/819d842b7b5644f88772f460e223c467
> 
> Can you take a look and let me know?

**Comment by shadcn** [comment]
@nethravathi95  I'm going to close this as done/stale. Feel free to reopen if not. Thank you.
