### ISSUE TITLE
The block fetched without img just title and alt, tha same for taxonomy (no taxonomy name)?

### ISSUE THREAD

**Issue by ansdb** [chapter-three/next-drupal#136]
Hi

I've created a block in **Drupal** then try to fetch its content _(3 image fields with title and alt + taxonomy term)_ I've got the following data structure and I've got just **title** and **alt** no **_img_** the same goes for **taxonomy term** no **taxonomy name** 

I've used `getResource('block_content--basic', 'uid')` method to fetch the block.

```
{
    "type": "block_content--basic",
    "id": "a1e0df3f-88b8-4c04-859a-c5e8eb9z5b17",
    "drupal_internal__id": 2,
    "drupal_internal__revision_id": 2,
    "langcode": "en",
    "revision_created": "2022-03-31T15:51:08+00:00",
    "revision_log": null,
    "status": true,
    "info": "Bagdes",
    "changed": "2022-04-01T14:50:30+00:00",
    "reusable": true,
    "default_langcode": true,
    "revision_translation_affected": true,
    "body": null,
    "links": {
        "self": {
            "href": "http://web/jsonapi/block_content/basic/a1e0df3f-88b8-4c04-859a-c5e8eb9z5b17"
        }
    },
    "block_content_type": {
        "type": "block_content_type--block_content_type",
        "id": "48f76ec0-7c2a-4c91-a0dc-6f53434e3e92",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": "basic"
        }
    },
    "revision_user": null,
    "field_acquia_drupal_7_certificat": {
        "type": "file--file",
        "id": "78148035-a610-4516-b02d-a14a3a10203d",
        "resourceIdObjMeta": {
            "alt": "Acquia Drupal 7 certification",
            "title": "Acquia Drupal 7 certification",
            "width": 147,
            "height": 147,
            "drupal_internal__target_id": 16
        }
    },
    "field_acquia_drupal_8_certificat": {
        "type": "file--file",
        "id": "12cdc36a-e4ab-4830-aa60-481296b2a173",
        "resourceIdObjMeta": {
            "alt": "Acquia Drupal 8 certification",
            "title": "Acquia Drupal 8 certification",
            "width": 295,
            "height": 295,
            "drupal_internal__target_id": 18
        }
    },
    "field_bagdes": {
        "type": "taxonomy_term--achevements",
        "id": "2cd66146-893f-4178-b092-10d88ff2b62f",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 1
        }
    },
    "field_drupal_association_members": {
        "type": "file--file",
        "id": "449195da-beca-4151-b4ce-dc9f3b23aa05",
        "resourceIdObjMeta": {
            "alt": "Drupal Association membership",
            "title": "Drupal Association membership",
            "width": 217,
            "height": 217,
            "drupal_internal__target_id": 17
        }
    },
    "relationshipNames": [
        "block_content_type",
        "revision_user",
        "field_acquia_drupal_7_certificat",
        "field_acquia_drupal_8_certificat",
        "field_bagdes",
        "field_drupal_association_members"
    ]
}
```

Please if someone can help because there is a _native way_  using **JS Promise** to fetch the **image** that **resides** in this **api route link** but i think there will be another special **next-drupal** way to fetch the image as well.

**http://127.0.0.1:8080/jsonapi/block_content/basic/a1e0df3f-88b8-4c04-859a-c5e8eb9z5b17/field_acquia_drupal_7_certificat**

Thanks in advance.

**Comment by shadcn** [comment]
You can fetch additional data (relationships or entity references in Drupal) using the "include" params.

```ts
const block = await getResource<DrupalBlock>(
  "block_content--basic",
  "a1e0df3f-88b8-4c04-859a-c5e8eb9z5b17",
  {
    params: {
      include: "field_bagdes", // <----- This will include the taxonomy terms.
    },
  }
)
```

What is the name of the image field you want to fetch? `field_drupal_association_members `?

**Comment by ansdb** [comment]
> 

Thank you so much @shadcn this fixed the problem I didn't know about **params** argument before :smile: 

Thanks a lot for your prompt help :+1:

**Comment by shadcn** [comment]
Quick note: when you include the `field_badges` it will fetch **all** the fields for the terms. You probably care about a few fields only. You can do so as follows:

```ts
const block = await getResource<DrupalBlock>(
  "block_content--basic",
  "a1e0df3f-88b8-4c04-859a-c5e8eb9z5b17",
  {
    params: {
      include: "field_bagdes, field_acquia_drupal_7_certificat",
      "fields[taxonomy_term--achevements]": "id, name", // <---- Only give me the id and the name for the terms.
    },
  }
)
```

**Comment by ansdb** [comment]
> Quick note: when you include the `field_badges` it will fetch **all** the fields for the terms. You probably care about a few fields only. You can do so as follows:
> 
> ```ts
> const block = await getResource<DrupalBlock>(
>   "block_content--basic",
>   "a1e0df3f-88b8-4c04-859a-c5e8eb9z5b17",
>   {
>     params: {
>       include: "field_bagdes, field_acquia_drupal_7_certificat",
>       "fields[taxonomy_term--achevements]": "id, name", // <---- Only give me the id and the name for the terms.
>     },
>   }
> )
> ```

Yes this is amazing didn't know about it, thank you so much for letting me know about this ability as well, I really appreciate your help.

Thanks a million :pray:

**Comment by TheRuslan** [comment]
> Quick note: when you include the `field_badges` it will fetch **all** the fields for the terms. You probably care about a few fields only. You can do so as follows:
> 
> ```ts
> const block = await getResource<DrupalBlock>(
>   "block_content--basic",
>   "a1e0df3f-88b8-4c04-859a-c5e8eb9z5b17",
>   {
>     params: {
>       include: "field_bagdes, field_acquia_drupal_7_certificat",
>       "fields[taxonomy_term--achevements]": "id, name", // <---- Only give me the id and the name for the terms.
>     },
>   }
> )
> ```

Is that possible to use with drupal-jsonapi-params?

**Comment by shadcn** [comment]
@TheRuslan Yes. See https://next-drupal.org/docs/guides/jsonapi-params
