### ISSUE TITLE
FetchError: request to https://drupal-site.ddev.site/oauth/token failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by itamair** [chapter-three/next-drupal#14]
From the Quickstart guide, as soon as I follow the [3. Run Site](https://next-drupal.org/docs/quick-start#3-run-site) steps, I hit the following error on http://localhost:3000:

`FetchError: request to https://drupal-site.ddev.site/oauth/token failed, reason: unable to verify the first certificate`

I cannot realise what is causing this issue (from the Drupal site settings) ... 

<img width="980" alt="Screenshot 2021-08-13 at 21 35 54" src="https://user-images.githubusercontent.com/1429859/129410106-0e47b08d-5713-49f0-b9eb-3dbfd9523f5f.png">

Thanks in advance for your support!

**Comment by arshad** [comment]
This has to do with the https request. 

Since you’re running this on your local you can safely disable this by setting the following in your .env file. 

```
NODE_TLS_REJECT_UNAUTHORIZED=0
```

You won’t have this issue when you deploy to a prod server with a valid certificate.

**Comment by itamair** [comment]
Thanks @arshad  ... your workaround looks working.
and now leads me to this new one: https://github.com/chapter-three/next-drupal/issues/15
