### ISSUE TITLE
Question about deletion of folder "example-ssr"

### ISSUE THREAD

**Issue by theodorosploumis** [chapter-three/next-drupal#145]
I was using the `example-ssr` as an example for SSR development (https://github.com/chapter-three/next-drupal/tree/main/examples/example-ssr). It seems that the whole folder was deleted last week.

Is the same functionality included on another example?
Thanks.

**Comment by shadcn** [comment]
@theodorosploumis the example was not complete. We are working on a new one. Anything you would like to see in SSR example?

**Comment by shadcn** [comment]
@theodorosploumis I added the example here if you'd like to see it: https://github.com/shadcn/next-drupal-examples/tree/main/example-ssr

**Comment by theodorosploumis** [comment]
Thanks for the quick response @shadcn!

I am trying to use the `getServerSideProps` method for Pages. I managed to make this work but your example has a lot of information about conditions inside the function.
