### ISSUE TITLE
Approaches to implement search autocomplete suggestions

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#151]
While user is typing, I want it to suggest terms in a dropdown that can autocomplete. On the Next.js side, I think it's just a typical debounced input field. 

But is there any support for this feature in `next-drupal`? And how to configure for on the Drupal side?

Thanks.

(Please let me know if Issues is not the place for such discussions. If the discussion is open, I'll probably post there.)

**Comment by shadcn** [comment]
Yes. You can use a simple debounced field and an API route for filtering.

Here's an example: `/pages/api/autocomplete.ts`

```ts
import { NextApiRequest, NextApiResponse } from "next"
import { getResourceCollection } from "next-drupal"

export default async function (
  request: NextApiRequest,
  response: NextApiResponse
) {
  if (request.method !== "POST") {
    return response.status(405).end()
  }

  try {
    const { search } = request.body

    if (!search) {
      throw new Error(`'search' missing`)
    }

    // Make a request to Drupal to find article containing search.
    const articles = await getResourceCollection("node--article", {
      params: {
        "filter[title][operator]": "CONTAINS",
        "filter[title][value]": search,
        "fields[node--article]": "title",
      },
    })

    return response.json(articles)
  } catch (error) {
    return response.status(422).end(error.message)
  }
}
```

You can now make a post request to this route to get articles containing `search` keywords.

**Comment by fnick851** [comment]
@shadcn Thank you! I think this actually solves the problem in https://github.com/chapter-three/next-drupal/issues/152

With this pattern, I don't need the Docker container to accept client side (browser) requests. It can always be server to server.

**Comment by fnick851** [comment]
@shadcn 
What will happen if I call `getResourceCollection` on the client side? It won't work right?

**Comment by shadcn** [comment]
`getResourceCollection` is meant to run on `node`. It contains your `client_id` and `client_secret` and makes auth calls to your Drupal site so you don't want to do that in the browser :)

(Using it in `getStaticProps/getServerSideProps` or API routes means Next.js can properly tree shake it when bundling your JavaScript)

**Comment by fnick851** [comment]
@shadcn Thanks!

**Comment by fnick851** [comment]
@shadcn Could you share some thoughts on why this is using `getResourceCollection ` but not the Search API (https://next-drupal.org/docs/guides/search-api)?

**Comment by shadcn** [comment]
@fnick851 The original question did not mention Search API so I went with the easiest solution :)

You can totally replace `getResourceCollection` with `getSearchIndex` with filters.

**Comment by fnick851** [comment]
@shadcn Thanks. Still curious what is the difference (on the Drupal side) between `getResourceCollection` with `getSearchIndex`? 

I guess what makes "search" a search if just querying and looking up with `getResourceCollection` kind of does the same thing?

**Comment by shadcn** [comment]
`getSearchIndex` uses Search API: https://www.drupal.org/project/search_api
