### ISSUE TITLE
Docker container communication during build step

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#152]
Hi, on the doc page for environment variables: https://next-drupal.org/docs/environment-variables, I can see `NEXT_PUBLIC_DRUPAL_BASE_URL` is needed by Next.js. I believe Next.js will use this URL during build time to fetch some data from the Drupal instance, right?

So given that, here is my situation:
Our setup will authenticate all network requests to containers in non-PROD environments, using Azure Active Directory. So if Next.js, during build time, send a GET request to `NEXT_PUBLIC_DRUPAL_BASE_URL` which is the Drupal container's public facing URL, it will fail. We could use Kubernetes to set up an inter-container network and give the Drupal container a "virtual URL", say it is "drupal-api". So now, the `NEXT_PUBLIC_DRUPAL_BASE_URL` variable becomes "drupal-api". It will then work for the build step. But this then will cause any Next.js AJAX/client-side call to fail, right? - because "drupal-api" is not a real URL that lives on the internet.

I'm curious if you have faced similar situations with Docker. (Non-PROD environments need to authenticate network communications.) And how do you resolve it? Thanks.

**Comment by shadcn** [comment]
@fnick851 I see what you mean but I don't use Kubernetes and I'm afraid I can't be of much help here. Are you on Slack? Maybe someone from the Next.js can help? https://drupal.slack.com/archives/C01E36BMU72

**Comment by fnick851** [comment]
@shadcn 
I will check the Next.js side too, thanks.

But I think it is more related to `next-drupal`. Basically, whatever I put in `getStaticProps` need to access the backend Docker container via an inter-container network (`getStaticProps` runs at build time). So it cannot use the same `NEXT_PUBLIC_DRUPAL_BASE_URL ` value.

Is there a way to specify a different network address value for these methods such as `getResource`? These methods use `NEXT_PUBLIC_DRUPAL_BASE_URL` under the hood right?

**Comment by fnick851** [comment]
It turns out I can build Next.js API to replay requests server to server. So there is no need to expose Drupal backend container to public. 

https://github.com/chapter-three/next-drupal/issues/151
