### ISSUE TITLE
FetchError: request to https://localhost/drupal-9.2/jsonapi failed, reason: certificate has expired.

### ISSUE THREAD

**Issue by bandita0907** [chapter-three/next-drupal#153]
![image](https://user-images.githubusercontent.com/102651724/162962860-10d8ee93-63fb-4008-81dd-0cee5281d9bd.png)

I followed all the steps  from ( https://next-drupal.org/learn/quick-start/) but after running the development server, I am getting this error. Can anyone help with the solution, what needs to be done.

**Comment by shadcn** [comment]
Do you need `https`? You can use `http` on localhost.

**Comment by bandita0907** [comment]
Thank you @shadcn , it got solved.
