### ISSUE TITLE
Server Error: Error: resource of type taxonomy_term--team not found.

### ISSUE THREAD

**Issue by bandita0907** [chapter-three/next-drupal#154]
![image](https://user-images.githubusercontent.com/102651724/162972945-891e4cc0-e3a8-4b6d-97a3-81aeb080215e.png)
 
I have used (npx create-next-app -e https://github.com/chapter-three/next-drupal/tree/main/examples/example-webform) command to get the webform and followed (https://next-drupal.org/docs/guides/webform) for the installation. When i run the development server , i am getting this issue. Can anyone please help on this.

**Comment by shadcn** [comment]
@bandita0907 The page is looking for a `teams` vocabulary to load the options. Have you created this on the Drupal side?

1. Visit `/admin/structure/taxonomy`.
2. Add a vocabulary named **Team**.
3. Add some terms.
4. Then run the Next.js site again.5. 

![vocabulary-team](https://user-images.githubusercontent.com/124599/162992042-5b87b085-0a39-4928-8699-a351bb8a01f1.jpg)

**Comment by bandita0907** [comment]
Thank you so much for helping :) it got solved

**Comment by shadcn** [comment]
@caroline-dsouza This looks like a different error. It looks like the next.js site cannot find the Drupal site. Can you check if you got everything configured as per the quick start?

**Comment by shadcn** [comment]
@caroline-dsouza I'm going to close this as done/stale. Feel free to reopen if not. Thank you.
