### ISSUE TITLE
Proper way to get all Nodes for all Content types. 

### ISSUE THREAD

**Issue by theodorosploumis** [chapter-three/next-drupal#157]
Function `getPathsFromContext` fetches all the entity paths. I would like to do something similar and get all the entities of an entity type (eg all Nodes).

The functions `getResourceCollectionFromContext` and `getResourceCollection` do not allow multiple `types` as arguments so a solution is to make a loop and call one of these for each Content type.

Is there a better solution than a loop? Or there is already a function for this case?

Thanks!

**Comment by shadcn** [comment]
@theodorosploumis Yeah. `getPathsFromContext` uses a loop as well.

You could so something like this:

```ts
const articles = await getResourceCollection("node--article")

const pages = await getResourceCollect("node--page")
```

**Comment by shadcn** [comment]
@theodorosploumis I'm going to close this as done/stale. Feel free to reopen if not. Thank you.
