### ISSUE TITLE
... failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by rfmarcelino** [chapter-three/next-drupal#160]
Just dropping this as a suggestion to add to docs.
I'm using ddev and by default it's exporting the URL with https causing:
"... failed, reason: unable to verify the first certificate"
Make sure that the NEXT_PUBLIC_DRUPAL_BASE_URL added on is using **http** and not **https** (unless you're running the Next app with https.

**Comment by shadcn** [comment]
Thanks @rfmarcelino 

If, and only if, you're running against a local Drupal install, you can also use `NODE_TLS_REJECT_UNAUTHORIZED=0` in your `.env.local` file and use `https`.

**Note: only use this for local dev servers and not against production sites.**
