### ISSUE TITLE
next-drupal-basic-starter get 400 bad request 

### ISSUE THREAD

**Issue by EustaceCheng** [chapter-three/next-drupal#161]
According quick start, I was working decouple Drupal with Nextjs and JSONAPI, and stuck.

    pages/index.tsx (43:16) @ async getStaticProps
   
    41 |   context
    42 | ): Promise<GetStaticPropsResult<IndexPageProps>> {
    > 43 |   const nodes = await getResourceCollectionFromContext<DrupalNode[]>(
       |                ^
    44 |     'node--article',
    45 |     context,
    46 |     {

And I try to find error on next-drupal, I found that 'src/utils.ts::getJsonApiIndex' will check the response of http://example.com/jsonapi and it prints 400 bad request. Detail is "The following query parameters violate the JSON:API spec: 'q'."
I also checked  http://example.com/jsonapi/node/article and http://example.com/jsonapi/node/article/{id} looks good. 
I have no idea how to fix it, need help please.

**Comment by shadcn** [comment]
Hmm what are you running your Drupal site on? Valet? ddev?

**Comment by EustaceCheng** [comment]
Laravel Valet 2.18.4

**Comment by shadcn** [comment]
Yeah I'm on Laravel Valet and I've definitely seen this. Can you try updating Valet and check? It looks like there was a fix committed recenlty: https://github.com/laravel/valet/pull/1218

**Comment by EustaceCheng** [comment]
I upgrade valet to 3.1.3, and rebuild drupal, it works. thanks!
Is there has preview before submit add-content form?

**Comment by shadcn** [comment]
@EustaceCheng You mean when editing content? Right now you can save and preview draft. The native Drupal preview is not supported yet but we are looking into it here #132

**Comment by EustaceCheng** [comment]
Thanks for your reply.

**Comment by aprice42** [comment]
@shadcn I also ran into this issue and updating laravel to 3.1.3 fixed it for me too. 

As I was experiencing this error I was wishing for a common "gotchas" section in the tutorial. And IMO this issue would be a nice addition (or maybe there are not so many valet users out there?). In any case, it would have saved me a few hours of digging around. 😉
