### ISSUE TITLE
How to retrieve DRUPAL_CLIENT_ID and DRUPAL_CLIENT_SECRET

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#166]
One can retrieve this from /admin/config/services/next/sites/nextjs_site/env:
NEXT_PUBLIC_DRUPAL_BASE_URL=http://localhost:xxxx
NEXT_IMAGE_DOMAIN=localhost
DRUPAL_SITE_ID=nextjs_site
DRUPAL_FRONT_PAGE=/node
DRUPAL_PREVIEW_SECRET=xxxxxxxxx
DRUPAL_CLIENT_ID=Retrieve this from /admin/config/services/consumer
DRUPAL_CLIENT_SECRET=Retrieve this from /admin/config/services/consumer

As seen above, it recommends "Retrieve this from /admin/config/services/consumer". But I can't find the ID and SECRET anywhere.

**Comment by shadcn** [comment]
@fnick851 

1. When you visit `/admin/config/services/consumer`, the `DRUPAL_CLIENT_ID` is the **UUID**
<img width="599" alt="Consumer_entities___Chapter_Three" src="https://user-images.githubusercontent.com/124599/164002552-9aaf6b16-9ccd-40e0-bf1b-77781a4b3e27.png">

2. The `DRUPAL_CLIENT_SECRET` is the secret provided under **New Secret** when creating the client.
<img width="720" alt="Edit_Next_js___Chapter_Three" src="https://user-images.githubusercontent.com/124599/164002457-9eb555dd-d199-436b-a6ca-095db0aaa926.png">

**Comment by fnick851** [comment]
@shadcn 
And when creating the client, we should note down the New Secret we put in right? Probably a dumb question, because it seems there's no way to retrieve this.

**Comment by shadcn** [comment]
@fnick851 Yes. Simple OAuth module does not allow this value to be retrieved. You can note it down when you set it. If you forgot you can always set a new secret.
