### ISSUE TITLE
Invalid eslint config file from https://github.com/chapter-three/next-drupal-basic-starter

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#167]
Hi, the project created with `npx create-next-app -e https://github.com/chapter-three/next-drupal-basic-starter` contains an eslint config file with a name `eslintrc.json`. But it should be `.eslintrc.json`. So it won't be recognized.

Is this intentional or an error?

**Comment by shadcn** [comment]
@fnick851 Yes this is an error. I'll fix. Thank you :)

**Comment by shadcn** [comment]
Fixed. Thank you.
