### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by bandita0907** [chapter-three/next-drupal#168]
I followed the https://next-drupal.org/docs/guides/webform . After filling up the form ,i am unable to submit the form , getting the error like this.
![image](https://user-images.githubusercontent.com/102651724/164066077-322c4589-c68c-4213-9b96-20744f27c34d.png)
Could anyone help on this what steps needs to be followed for this.

**Comment by shadcn** [comment]
When does this happen? Right after you click submit?

**Comment by bandita0907** [comment]
Yes after click on submit

**Comment by shadcn** [comment]
@bandita0907 I've not been able to reproduce this but I found this thread with some helpful answers. Can you give it a try? https://stackoverflow.com/questions/49343024/getting-typeerror-failed-to-fetch-when-the-request-hasnt-actually-failed

**Comment by bandita0907** [comment]
Hi Shadcn, this problem only occurs in client side on submit , and on server it works fine.. Could you let me know why it is appearing and how it can be solved?

**Comment by shadcn** [comment]
@bandita0907 Can you share the client side code? I'll try to reproduce the issue.

**Comment by shadcn** [comment]
@bandita0907 did you figure this out?

**Comment by shadcn** [comment]
@bandita0907 I'm going to close this as done/stale. Feel free to reopen if not. Thank you.

**Comment by CsarRamos** [comment]
> Hi @shadcn , this problem only occurs in client side on submit , and on server it works fine.. Could you let me know why it is appearing and how it can be solved?

Hi, I had the same problem but I was able to solve it by implementing the default.services.yml file in my Drupal site. Apparently it was a problem with the CORS Policy. I hope it can be helpful to someone. Cheers

**Comment by shadcn** [comment]
Awesome. Thanks for sharing the solution @CsarRamos. Appreciate it.

**Comment by MikleDen** [comment]
> 


where should I put the servise.yml file&

**Comment by MikleDen** [comment]
> > Hi @shadcn , this problem only occurs in client side on submit , and on server it works fine.. Could you let me know why it is appearing and how it can be solved?
> 
> Hi, I had the same problem but I was able to solve it by implementing the services.yml file in my Drupal site. Apparently it was a problem with the CORS Policy. I hope it can be helpful to someone. Cheers

where should I put the servise.yml file?

**Comment by CsarRamos** [comment]
> > > Hi @shadcn , this problem only occurs in client side on submit , and on server it works fine.. Could you let me know why it is appearing and how it can be solved?
> > 
> > 
> > Hi, I had the same problem but I was able to solve it by implementing the services.yml file in my Drupal site. Apparently it was a problem with the CORS Policy. I hope it can be helpful to someone. Cheers
> 
> where should I put the servise.yml file?

Hello, you have to enable CORS config on Drupal with the services.yml file.
Example: https://drupal.stackexchange.com/questions/245903/how-do-i-set-up-cors
