### ISSUE TITLE
Configured oauth , but no filtered content?

### ISSUE THREAD

**Issue by kdejaeger** [chapter-three/next-drupal#169]
Hello,

I followed the steps described on https://next-drupal.org/ to install nextjs in drupal and added a username/password oauth login, like in the examples projects.

Now when I do a getResourceCollection call, I get all the content, not the content applicable to the rights of the logged in user. Am I missing something or is this going to be supported in the future?

**Comment by shadcn** [comment]
@kdejaeger How are you configuring the auth?

**Comment by kdejaeger** [comment]
We used this: https://github.com/chapter-three/next-drupal/blob/main/examples/example-auth/pages/api/auth/%5B...nextauth%5D.ts

**Comment by shadcn** [comment]
@kdejaeger I created an example here: https://github.com/shadcn/next-drupal-examples/tree/main/example-crud with some links to pages showing the implementation.

Here's how it works.

1. We're using next-auth for authentication using the Password Grant.
2. The user logs in and we get an access token which we can use for authenticated calls to Drupal.
3. We set the token using: `drupal.auth = () => `Bearer ${session.accessToken}`

> Why did you guy's decide to make a new class instead of building onto the existing code? Is it such a big diffference?

The class is more flexible as in it makes things easier to swap with custom auth, cache...etc

**Comment by kdejaeger** [comment]
Thanks, we are using this client now.

**Comment by shadcn** [comment]
@kdejaeger How's the client working out? Did you get bearer tokens to work?

**Comment by kdejaeger** [comment]
No sorry my backend colleagues don't consume the tokens yet on drupal. But as far as I can see from the source code, the new client picks up the token from the session.

**Comment by shadcn** [comment]
@kdejaeger ok. I'll keep this open. We can revisit when confirmed the tokens are properly sent.

**Comment by shadcn** [comment]
@kdejaeger I'm going to close this as done/stale. Feel free to reopen if not. Thank you.

PS: the `DrupalClient` supports creating resources as of `1.4.0`: https://next-drupal.org/docs/creating-resources
