### ISSUE TITLE
getResourceFromContext throws error on certain URLs

### ISSUE THREAD

**Issue by MichaelCastelbuono** [chapter-three/next-drupal#172]
I got the `Failed to fetch resource: ...` error on a url where I presume the error has to do with a `urlencode` issue. The url in my test was `/library/Faculty&Staff`. The `getResourceFromContext` function threw the error, with the jsonapi endpoint that it supposedly could not reach, which I was able to load manually in my browser. After removing the `&` from the url, so that it read `/library/FacultyStaff` the page loaded fine. Let me know if you need any more details.

*Edit*
I just realized that this url was probably a custom override to the path alias pattern that was setup and sure enough it was. When I checked, generate automatically, it stripped out the `&`. My thought though is that why was `translatePathFromContext` able to return the jsonapi url in its response but `getResourceFromContext` could not load it? Seems like it still should work, or am I missing something?

**Comment by shadcn** [comment]
Yes. Agreed. It should still work. I just tested and confirmed this is a bug.

I'll push a fix. A quick `encodeURIComponent` before assembling the route seems to fix it but I'd like to make sure it's a proper fix.

```ts
slug = Array.isArray(slug)
      ? slug.map((s) => encodeURIComponent(s)).join("/")
      : slug
```

I'll update here. 

Thanks for reporting. Appreciate it.

**Comment by MichaelCastelbuono** [comment]
Thanks for the response and the great work on this project. We're testing out the idea of using this by taking an existing production website with ~1,000 pages. So far that's the only error we've encountered and everything's been really nice to work with. Looking forward to using it on upcoming projects.

**Comment by shadcn** [comment]
Thanks. 

We’re also running a few 1000+ pages sites with it. Ping here if you have any questions. 

PS: Try the DrupalClient. This is where we’ll be focusing future work: https://next-drupal.org/docs/client

**Comment by shadcn** [comment]
This is now fixed in `1.3.1`: https://github.com/chapter-three/next-drupal/blob/main/CHANGELOG.md#131

Thank you.

**Comment by MichaelCastelbuono** [comment]
Thanks! I confirmed it works for me after pulling `1.3.1`. I am curious about the fix. How come no action is needed when `slug` is not an array? Is that an edge case for the `/` or empty string url?

**Comment by shadcn** [comment]
@MichaelCastelbuono next-drupal will always handle slugs as arrays. If you're passing slug directly, we assume you have the slug properly encoded.
