### ISSUE TITLE
Requests are very slow when building the app

### ISSUE THREAD

**Issue by Kroonax** [chapter-three/next-drupal#18]
Hi !

I'm encountering a pretty big issue with next-drupal, the build times are extremely high (on a localhost setup), I tried logging precise times in the built index.js in `node_modules/next-drupal/dist` and for every fetch I am getting between 1500ms and 4000ms which results in pages taking from 5 to 15 seconds to be built when running `next build`.

When I am running these requests myself with Postman (for example on `/oauth/token` which is ran by `getAccessToken` in next-drupal), it takes a maximum of 400ms. It is the same for every function used by next-drupal, getResourceByPath takes between 1500ms and 6000ms, etc...

The project I am working on needs to build around 2000 pages at build time, if the build of every page took around 2 or 3 seconds that would not be a big problem but the fact that right now it can take more than 10 seconds is just not conceivable.
I do not think it is caused by the fact that at build time it concurrently builds multiple page because when I am adding or editing a page the ISR takes between 5 and 15 seconds to (re)build the new page.

Do you have any idea of the cause ?

**Comment by arshad** [comment]
Interesting. I'll take a look at this.

How are you testing for the response time?

**Comment by Kroonax** [comment]
I take timestamps in and out of the requests Promises. I had the opportunity to do the same requests on the client side (project has some functional caveats that need some requests to be done on client). And those requests (including subrequests) take around 150 to 300ms in a local environment.

I don't think it is caused by the overload of the computer at build time as I thought it would be, since we have the same problem when we run the app in dev mode, even a single page can take around 8 to 15 seconds to load sometimes, depending on the content.

Also, in the case of a Drupal exposing its API publicly (no user accounts, one ruleset - one consumer), we should be able to bypass `getAccessToken` when not needed, in our case (since the requests are very slow) it only adds to the build time.

**Comment by arshad** [comment]
Agreed on the `getAccessToken` bypass. We *are* calling this for every request.

**Comment by shadcn** [comment]
@Kroonax I'm going to mark this as fixed. It not, feel free to re-open.
