### ISSUE TITLE
Mistake in auth example

### ISSUE THREAD

**Issue by kdejaeger** [chapter-three/next-drupal#185]
https://github.com/chapter-three/next-drupal/blob/main/examples/example-auth/pages/api/auth/%5B...nextauth%5D.ts

Hello, I think in this example -> refreshAccessToken method

```
    formData.append("client_id", process.env.DRUPAL_CLIENT_ID)
    formData.append("client_secret", process.env.DRUPAL_CLIENT_SECRET)
```
needs to be replaced with
```
    formData.append("client_id", process.env.OAUTH_CLIENT_ID)
    formData.append("client_secret", process.env.OAUTH_CLIENT_SECRET)
```

We started a new project. Followed the next.js tutorial and ended up with a 'default consumer'.
Then added Oauth and added a second consumer by following guides.

And now we just deleted the 'oauth consumer' and it seems we can just use the same consumer for everything. This was confusing.

**Comment by shadcn** [comment]
You're right. Nice catch. Thank you.

**Comment by shadcn** [comment]
I pushed a fix and also updated the docs. https://next-drupal.org/docs/authentication/refresh-token

Thank you

**Comment by shadcn** [comment]
@kdejaeger This is the hook I'm using as well. See https://next-drupal.org/docs/authentication/authorization-code-grant#additional-information

**Comment by kdejaeger** [comment]
I think we're using it differently. We login and logout on our own frontend / sending the requests to drupal. So we removed the second provider with `async profile(profile)`.

I guess in that case we need to add a call to /oauth/userinfo in the session callback.
