### ISSUE TITLE
Drupal returning 2000 paths per request maximum

### ISSUE THREAD

**Issue by Kroonax** [chapter-three/next-drupal#19]
Hi, I found something quite odd when building an app with more than 2000 paths.

I have 6000 (3000 x 2 languages) nodes of one type (artwork) in my Drupal database but when I'm building the app, only 2000 are actually built when building the pages under `/artworks/[...slug].js`.

Is this a limitation from next-drupal, the next Drupal module or even the subrequests module ? I know that the basic Drupal/JSONAPI is limited to 50 nodes per request but I believe subrequests go through.

If we can't bypass this limitation, are we able to use limits to queue requests as long as we do not have all nodes ?

**Comment by shadcn** [comment]
You're probably hitting the `1000` max size that the Next.js module sets.

See https://github.com/chapter-three/next-drupal/blob/db2f99c3872a7e46cedcad66650b6f03fd645dbb/modules/next/modules/next_jsonapi/next_jsonapi.services.yml#L1

Can you try overriding this parameter in your sites services.yml file?

**Comment by Kroonax** [comment]
It _seems_ to be working but I am hitting the 60 seconds timeout when retrieving the nodes now, so the build does not even start, do you know where I can change the timeout value ?

**Comment by Kroonax** [comment]
OK, there is an experimental flag to add in next.config.js :
`experimental.pageDataCollectionTimeout` is 60 by default, problem solved !

I will have to create a patch on the .yml file to make sure that the value never changes :)

**Comment by shadcn** [comment]
> I will have to create a patch on the .yml file to make sure that the value never changes :)

Do you mean the `next_jsonapi.size_max` value?

You could also look into ISR and only build the most important pages and let the other pages be server rendered.
