### ISSUE TITLE
Oauth: The resource owner or authorization server denied the request

### ISSUE THREAD

**Issue by mrchristophy** [chapter-three/next-drupal#2]
I'm very new to Oauth so please bear with me if I have something terribly wrong, but I cannot get the oauth/token route to work, after following all the steps. I always get the response:

```
{error: "invalid_client", error_description: "Client authentication failed",…}
error: "invalid_client"
error_description: "Client authentication failed"
message: "Client authentication failed"
```

With logs in the Drupal backend:
`League\OAuth2\Server\Exception\OAuthServerException: The resource owner or authorization server denied the request. in League\OAuth2\Server\Exception\OAuthServerException::accessDenied() (line 243 of /app/drupal/vendor/league/oauth2-server/src/Exception/OAuthServerException.php).`

`Symfony\Component\HttpKernel\Exception\HttpException: The JWT string must have two dots in Drupal\simple_oauth\Authentication\Provider\SimpleOauthAuthenticationProvider->authenticate() (line 81 of /app/drupal/web/modules/contrib/simple_oauth/src/Authentication/Provider/SimpleOauthAuthenticationProvider.php).`

Doing a bit of debugging I found that the simple_oauth module appears to require the client_id explicitly set in the body of the post, whereas the next-js package doesn't include it:

**Oauth2Token.php**
```
if (!empty($body['client_id'])) {
      $consumer_storage = $this->entityTypeManager()->getStorage('consumer');
      $client_drupal_entities = $consumer_storage
        ->loadByProperties([
          'uuid' => $body['client_id'],
        ]);
      if (empty($client_drupal_entities)) {
        return OAuthServerException::invalidClient($request)
          ->generateHttpResponse(new Response());
      }
      $client_drupal_entity = reset($client_drupal_entities);
    }
```
**get-access-token.ts**

```
const response = await fetch(
    ${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/oauth/token,
    {
      method: "POST",
      headers: {
        Authorization: `Basic ${basic}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: querystring.stringify({
        grant_type: "client_credentials",
      }),
    }
)
```

**Logging the body of the POST**

```
Array
(
    [grant_type] => client_credentials
    [client_id] => undefined
    [client_secret] => undefined
)
```

As I say, I might be horribly wrong here, but I'm just desperately trying to get this working as it looks awesome. Any help appreciated!

**Comment by arshad** [comment]
No worries. This is very early alpha and I know there's a lot to configure to get this working properly (we're working on making this simpler).

Let's do a quick preflight check.

Are your environment variables configured and properly loaded?

You need the following:

```
NEXT_PUBLIC_DRUPAL_BASE_URL=http://localhost:8080
NEXT_IMAGE_DOMAIN=localhost
DRUPAL_SITE_ID=
DRUPAL_CLIENT_ID=
DRUPAL_CLIENT_SECRET=
DRUPAL_PREVIEW_SECRET=
```

You can test this by `console.log(process.env)` in `_app.jsx`.

**Comment by mrchristophy** [comment]
It's weird, when I run the app I see the following:

`info  - Loaded env from /../nextjs/next/.env.local`

And:

```
 NODE_ENV: 'development',
  __NEXT_PROCESSED_ENV: 'true',
  NEXT_PUBLIC_DRUPAL_BASE_URL: 'https://next.lndo.site',
  NEXT_IMAGE_DOMAIN: 'next.lndo.site',
  DRUPAL_SITE_ID: '0a44cc38-ed29-4e76-802b-5dec85bc41cf',
  DRUPAL_PREVIEW_SECRET: 'rushhour',
  DRUPAL_FRONT_PAGE: '/node',
  DRUPAL_CLIENT_ID: 'cf068b84-4813-456a-969e-148dbbe8e92a',
  DRUPAL_CLIENT_SECRET: 'secret',
  NEXT_PUBLIC_TEST: 'testing',
  TRACE_ID: '68ca412def1ef638'
```

But when I try to console log process.env it's empty. Not really anything to do with this package I know, but frustrating...

In any case, it appears to have everything correct even though I can't console.log(), here are the headers being sent on the oauth/token call:

```
:authority: next.lndo.site
:method: POST
:path: /oauth/token
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
authorization: Basic dW5kZWZpbmVkOnVuZGVmaW5lZA==
cache-control: no-cache
content-length: 29
content-type: application/x-www-form-urlencoded
origin: http://localhost:3000
pragma: no-cache
referer: http://localhost:3000/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
```

Thanks for your help!

**Comment by mrchristophy** [comment]
I also just tried running my drupal site on localhost:1234 instead of the lando url incase it's a domain issue to no avail (both running on https)

**Comment by mrchristophy** [comment]
EDIT: It's working! I was using getStaticProps() completely wrong, I need to read up on how to use Nextjs :)

Still not sure why I can't console.log the process.env though???

**Comment by arshad** [comment]
Marking this issue as closed. Thank you.
