### ISSUE TITLE
Caching getMenu not working

### ISSUE THREAD

**Issue by mikegikas** [chapter-three/next-drupal#201]
Hello,

I am trying to get the menu, but the request didn't return the full menu.

https://next-drupal.org/docs/client/cache

If the Link at the menu is /node/{id} the method didn't return the items but only the items with absolute path.

Full Menu:
![full_menu](https://user-images.githubusercontent.com/14880242/167132928-e7852797-b804-4475-a944-e7f3e51bee4c.jpg)

Response Request has only two items.
![request](https://user-images.githubusercontent.com/14880242/167133053-7633abc2-4a9c-46c0-b048-4bdb52f6c59b.jpg)

Here is the absolute path to the link and the request returns it.
![Screenshot 2022-05-06 154052](https://user-images.githubusercontent.com/14880242/167133235-7f43fa82-8bed-4386-bb05-ee5e87fac678.jpg)

but here I have a /node/{id} and the response didn't get it.
![Screenshot 2022-05-06 154046](https://user-images.githubusercontent.com/14880242/167133241-79eba445-c519-4d0d-8ad6-97b288418222.jpg)

The old getMenu() function returns all of the menu items without a problem.

https://next-drupal.org/docs/reference#getmenu

![old_getMenu](https://user-images.githubusercontent.com/14880242/167134259-525c5e94-7201-44cf-b677-b3ddfb723683.jpg)

**Comment by shadcn** [comment]
I see. Are the menu items publicly available in Drupal? As in can anonymous users view and access those menu items?

**Comment by mikegikas** [comment]
I added the Authentication clientId and clientSecret.

In the console, I can see that the getMenu() returns the fullMenu, but I got the following error.

Error:
![error](https://user-images.githubusercontent.com/14880242/167411750-634cf3c2-e8d7-446b-a4de-63decf074417.jpg)

getMenu response:
![full_menu](https://user-images.githubusercontent.com/14880242/167411052-5f7d6c6c-a626-4790-a0c2-20b9f335ee02.jpg)

drupal init:
![drupal_method](https://user-images.githubusercontent.com/14880242/167411515-1cce19b4-14b2-434e-b10b-76a89b6680c5.jpg)

**Comment by shadcn** [comment]
So once you’ve configured `auth` with a `client_id` and `client_secret`, you can make authenticated requests to Drupal using the `withAuth` option:

```ts
const menu = await drupal.getMenu(“main”, {
  withAuth: true
})
```

This will make an authentication request to Drupal to fetch the menu items.

**Comment by shadcn** [comment]
hmm that's weird. Are `DRUPAL_CLIENT_ID` and `DRUPAL_CLIENT_SECRET` defined in your `.env.local` file?

**Comment by mikegikas** [comment]
I have the right one because it works with the old getMenu on the same application.

The strange thing is that the new getMenu() returns the menu, but then it throws the error.

**Comment by mikegikas** [comment]
I had a lifecycle problem with one component. It works as designed. 
@shadcn Thank you very much for your help.
