### ISSUE TITLE
Search: return Search Result highlighting input view mode

### ISSUE THREAD

**Issue by kevlarswift** [chapter-three/next-drupal#204]
Hi, I have just enabled the Search on my site. I'm wondering if, in addition to returning the node, it is possible to return the 'Search Result highlighting input' view mode. This way, you could see the word you have input in bold and in context of the page content.

Thanks for this great project.

**Comment by shadcn** [comment]
@kevlarswift My friend @robdecker just published a guide on how to do this :)

https://www.chapterthree.com/blog/search-api-excerpts-nextjs

**Comment by shadcn** [comment]
@kevlarswift was the guide helpful? Did you figure it out?

**Comment by kevlarswift** [comment]
I missed this comment. That's great though! Let me take a look.

**Comment by backlineint** [comment]
Closing as resolved. Hoping the blog post helped here.
