### ISSUE TITLE
Allow passing contextual filters to a view

### ISSUE THREAD

**Issue by stoker88** [chapter-three/next-drupal#206]
Looking for the possibility to pass a contextual filter to a view , for instance:

//Current
 const related = await drupal.getView('related_blog_articles--whats_new');

//Proposed
 const related = await drupal.getView('related_blog_articles--whats_new', {filter: '1234'});

**Comment by shadcn** [comment]
You can use params to filter.

```ts
const related = await drupal.getView('related_blog_articles--whats_new', {
  params: {
    filter: '1234'
  }
});
```

or if you have filters configured for the view you can use

```ts
const related = await drupal.getView('related_blog_articles--whats_new', {
  params: {
    "views-filter[status]": 1,
  }
});
```

See https://next-drupal.org/docs/reference#getview

**Comment by stoker88** [comment]
@shadcn thanks set me down the right path there, helps when you read the jsonapi_views module README.

For reference contextual filters are in the format '?views-argument[]={{ value }': in my case to filter by current nid:

const filters = {
        params: {
            'views-argument[]': resource.drupal_internal__nid,
        },
    };

const related = await drupal.getView('related_blog_articles--whats_new', filters);
