### ISSUE TITLE
Converting circular structure to JSON (Drupal entity reference field)

### ISSUE THREAD

**Issue by theodorosploumis** [chapter-three/next-drupal#212]
Hi, has anyone solved the issue "**Converting circular structure to JSON**" where JSON:API loops over an entity reference in Drupal. I get this when a Node references other Nodes which they reference back to the Node on a JSONAPI get call.

I can see that the `next-drupal` functions are using the native [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify). Some people propose to use a more safe npm like:

- https://www.npmjs.com/package/safe-json-stringify
- https://www.npmjs.com/package/json-stringify-safe
- https://www.npmjs.com/package/fast-safe-stringify

but in this case, **how could I override the functions**?

Related issues: 

- https://github.com/vercel/next.js/discussions/10992
- https://www.drupal.org/project/drupal/issues/3039730

Thanks.

**Comment by shadcn** [comment]
@theodorosploumis We have hit this once I think and from what I can see we've used `safe-json-stringify`.

```ts
// pages/[[...slug]].tsx
import safeJsonStringify from 'safe-json-stringify'

export async function getStaticProps() {
  // ....
  const stringifiedData = safeJsonStringify(node)
  const parsedNode = JSON.parse(stringifiedData)

  return {
    props: {
      node: parsedNode,
    },
  }
}

```

**Comment by TheRuslan** [comment]
I also used [safe-json-stringify](https://github.com/debitoor/safe-json-stringify) in my code when I ran into such errors with circular structure. A similar solution was given in the shadcn's example.

But it only was happening when I returned whole node(s) in props. I found the most convenient way is to massage data and return only necessary so the chance to run into this error is minimal.

**Comment by shadcn** [comment]
+1 to what @TheRuslan said above. We rarely fetch the entire resource. Always use sparse fieldsets.

**Comment by theodorosploumis** [comment]
I need to get the data on a NextJS API page by using the next-drupal functions like `getView` which by default fetches the whole Node (or not?). 

An example for such an API page:

```
// api/nodes/index.ts

import { NextApiRequest, NextApiResponse } from "next";
import { getView, JsonApiWithLocaleOptions } from "next-drupal";

export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse
) {
  if (request.method !== "GET") {
    return response.status(405).end();
  }

  try {

    const viewsOptions = {
       params: {
         include: "field_media_image_photo.field_media_image",
         "views-argument[]": 65+62, // Taxonomy term ids
         "views-filter[promote]": "All",
       },
    };

    const result = await getView("nodes--page", viewsOptions);

    return response.json(result);
  } catch (error: any) {
    return response.status(422).end(error.message);
  }
}

```

**Comment by shadcn** [comment]
`getView` accepts all the JSON:API params. You can use `fields`.

```ts
const viewsOptions = {
       params: {
         include: "field_media_image_photo.field_media_image",
         "fields[node--article]": "title,path,field_name", // <-----------  
         "views-argument[]": 65+62, // Taxonomy term ids
         "views-filter[promote]": "All",
       },
    };
```

**Comment by theodorosploumis** [comment]
I tried that but I get Nodes for **multiple Node bundles** from views 😃. 
Which probably does not work even if I use: 

```
"fields[node--article]": "title,path,field_name",
"fields[node--blog]": "title,path,field_name", 
```

**Comment by theodorosploumis** [comment]
My fault, it works! I can use multiple `fields`.
