### ISSUE TITLE
Cant access a node's action tabs (view, edit, delete, revisions, translate) from a node type with preview mode enabled.

### ISSUE THREAD

**Issue by laurencefass** [chapter-three/next-drupal#218]
The example video [here](https://next-drupal.org/guides/route-syncing) shows that a node's action tabs are visible when viewing a node in preview mode. .e.g  "view, edit, delete, revisions, translate" tabs are visible.

My installation appears not to display them (I have raised a separate issue to notify of the error). Note the absence of the node action tabs.

![image](https://user-images.githubusercontent.com/3512857/171411256-22b172bf-8891-4675-a267-5e897415ef6f.png)

**Comment by shadcn** [comment]
I see. Bartik does not render the tabs by default.

Can you try setting the default theme to Seven?

By default, the preview takes over the main content area (we might make this configurable later).

**Comment by laurencefass** [comment]
I moved the tabs blocks in Drupal core blocks layouts to anoter region. This works for my testing needs now.
