### ISSUE TITLE
Feature request: Logging in/out and editing in the client?

### ISSUE THREAD

**Issue by laurencefass** [chapter-three/next-drupal#222]
Is there a template for logging in/out and basic content editing in the client? Is there an API to support this? 

Im not referring to the webform API, but to actual content editing to replace the core editor?

Are these features roadmapped for your core nextjs-drupal module, or will you leave this level of functionality  to be implemented by individual clients?

**Comment by shadcn** [comment]
For authentication, we recommend next-auth. See our implementation here:

1. Implementation: https://github.com/chapter-three/next-drupal/blob/main/examples/example-umami/pages/api/auth/%5B...nextauth%5D.ts
2. Custom Login form: https://github.com/chapter-three/next-drupal/blob/main/examples/example-umami/components/form--login.tsx

**Comment by laurencefass** [comment]
thanks for the links.
