### ISSUE TITLE
Localized search results

### ISSUE THREAD

**Issue by theRuslan** [chapter-three/next-drupal#226]
I found a non-obvious behavior with always returning default translation (original) node if no locale defined in fetch body.
Maybe we should supplement [documentation for getSearchIndex](https://next-drupal.org/guides/search-api) for i18n case?

``` tsx
const router = useRouter();

const response = await fetch("/api/search/INDEX-NAME-HERE", {
  method: "POST",
  body: JSON.stringify({
    params: {
      filter: { name_of_field: value },
    },
    locale: router.locale,
  }),
})
```

**Comment by shadcn** [comment]
Yeah unfortunately API routes have no context of locale. You need to pass it from the router.

Let me tag this under documentation. I'll update it.

Thank you.

**Comment by shadcn** [comment]
I've updated the docs.

https://next-drupal.org/guides/search-api#localized-search-results

Thanks @theRuslan
