### ISSUE TITLE
Preview mode is undefined when called inside of an iframe

### ISSUE THREAD

**Issue by Kroonax** [chapter-three/next-drupal#227]
Hello !

For context, I am updating an existing website on Next to use next-drupal, and I want to add the preview mode to it.
When navigating to the preview URL manually, the `preview` variable in context is correctly defined to `true`, but when provided by the Drupal module iframe, the value is always `undefined`.

I also have problems with the cookies (I made a GDPR compliant cookies manager), since it's in an iframe, the GDPR pop-up keeps opening on the preview mode, so it's kind of annoying, I decided to use the preview variable to conditionally disable it when previewing the page, thus my previous problem.

In my Next config file I've have some changes done like `X-Frame-Options` completely emptied out to allow the backend to communicate with my localhost in development and some HSTS headers to make it compliant with some security protocols our clients have.

Thanks in advance,

**Comment by shadcn** [comment]
@Kroonax is this happening on localhost or in prod?

**Comment by Kroonax** [comment]
It's been happening in localhost with a Drupal on ddev, not tested in a production environment.

**Comment by shadcn** [comment]
OK. Yeah this is a know issue running Next.js in an iframe. If your Drupal site is say at http://drupal.test and the Next.js site is running at http://localhost:3000, Next.js cannot properly set the required cookie for preview mode.

This does not happen in prod.

We have a work-around for this during development. See https://next-drupal.org/docs/client/configuration#forceiframesamesitecookie

Can you give this a try and see if it works?

**Comment by Kroonax** [comment]
I had to change my config and manually set everything in the `DrupalClient`, it seems that documentation on the subject is a little inconsistent from one point to another.

Once I set everything up I get `Error: The path attribute is missing for entity with slug /my/slug`.

**Comment by shadcn** [comment]
You're seeing this error after setting `forceIframeSameSiteCookie: true`?

**Comment by Kroonax** [comment]
Yes, before that it loaded correctly but was not able to retrieve the preview mode, now it just errors out.

**Comment by shadcn** [comment]
Did you figure it out?

**Comment by shadcn** [comment]
Hmm how is your `getStaticPaths` set up?

**Comment by Kroonax** [comment]
I've mixed up everything and every pages, I'm back on tracks (was working on a page without a slug or generated paths, it's a lonely node in its own content type).

Let's say we have this scenario :

The route is `/article/myslug`.

The context is :
```
{
  params: { slug: 'myslug' },
  locales: undefined,
  locale: undefined,
  defaultLocale: undefined
}
```

```
getResourceFromContext("node--article", ctx, {
  // adding prefix: "article" does not change anything
  params: {
    include: "my_includes",
  },
 deserialize: false,
});
```

`null` is returned by `getResourceFromContext`.

If I debug inside of `next-drupal`, I see that the path returned by `getPathFromContext` is `myslug` (or `article/myslug` if I add the `prefix: "article"` option)

**Comment by Kroonax** [comment]
I just tried changing it to `/article` but it does not change anything.

The node has a path alias and it matches, this is becoming weirder and weirder.

**Comment by Kroonax** [comment]
Ok, it seems that it is caused by the lines 65-67 of `get-resource.ts`.

```js
 if (!context.locale && !resource?.default_langcode) {
    return null
  }
```

It was so obvious I didn't see it, the website is not localized, therefore it always returns `null`, what's the short term solution ? Giving `getResourceFromContext` and `getPathsFromContext` a fake context with hardcoded langcode ?

**Comment by shadcn** [comment]
Ah this was added because of a bug how localized route was being handled but it assumes a `default_langcode` is returned from the server.

Are you disabling some fields on the Drupal server? Say with JSON:API extras? 

We fixed this in the `DrupalClient` version.

If it's not a lot of work, maybe try upgrading to the DrupalClient version? https://next-drupal.org/docs/client/upgrade

**Comment by shadcn** [comment]
@Kroonax  Since this bug came up a few times, I backported the fix and created a new release.

Can you upgrade to `next-drupal 1.4-rc1` and test please?

Note: I'd still recommend the `DrupalClient` going forward. 

Thank you.

**Comment by Kroonax** [comment]
Upgrading to the rc1 fixed the issue ! Thanks a lot !
