### ISSUE TITLE
getResourceFromContext returns null result during build

### ISSUE THREAD

**Issue by kretzschr** [chapter-three/next-drupal#228]
I'm currently facing an issue while running & building my project. My Drupal backend is running as a container in an Azure Web App. Pages are generated within `getStaticProps`.

`const apiResource: JsonApiResource = await getResourceFromContext(type, context);`

Type and context parameters are set correctly, but the result is always null. Below you'll find an example output of some console.log statements

**type**
`taxonomy_term--category`

**context**
```
{
  params: { slug: [ 'category', 'interviews' ] },
  locales: undefined,
  locale: undefined,
  defaultLocale: undefined
}
```
**apiResource**
`null`

I use the code from above in a page named `[...slug].tsx`

When I run or build my NextJS project with a local Drupal backend, all contents are fetched and queried correctly.

Am I missing something in my NextJS configuration, when working with a remote backend or is the issue more related to my web app security and networking settings?

**Comment by shadcn** [comment]
It it's working on local, we can assume you got the Next.js code correctly. It's most likely the Drupal backend on the Azure server here.

Can you access the `/jsonapi` path on the server? Is it public?

**Comment by kretzschr** [comment]
Yes, requesting /jsonapi via cURL, Postmon etc. is working fine. I'm  also wondering why requests made from my `index.tsx` are working:

```
const categories: JsonApiResource[] = await getResourceCollection('taxonomy_term--category')
const otherVideos: JsonApiResource[] = await getResourceCollection('node--video_others', {
    params: getParams('node--video_others')
  })
```

Both requests are also returning results, when called within getStaticProps of `[...slug].tsx`.

I also tested calling getRessourceCollectionFromContext from `[...slug].tsx` and I also received results.

`const categories: JsonApiResource[] = await getResourceCollectionFromContext('taxonomy_term--category', context)`

**Comment by kretzschr** [comment]
After a debugging session I found, that the returned resource objects from index.js (drupal-next) differ:

**Local**
```
{
  jsonapi: { version: '1.0', meta: { links: [Object] } },
  data: {
    type: 'node--plenary_meeting',
    id: '81b3c3ae-f10c-4cf6-bfcf-45d9cb25750c',
    links: { self: [Object] },
    attributes: {
      drupal_internal__nid: 20,
      drupal_internal__vid: 62,
      langcode: 'de',
      revision_timestamp: '2022-06-07T12:15:48+00:00',
      revision_log: null,
      status: true,
...
```

So, locally I got a valid JSONAPI node object. From my remote backend I receive the following:

```
{
  resolved: 'http://.../video_others/....,
  isHomePath: false,
  entity: {
    canonical: 'http://.../video_others/...',
    type: 'node',
    bundle: 'video_oterhs',
    id: '20',
    uuid: '...'
  },
  label: '....',
  jsonapi: {
    individual: 'http://..../jsonapi/node/video_others/...',
    resourceName: 'node--video_others',
    pathPrefix: 'jsonapi',
    basePath: '/jsonapi',
    entryPoint: 'http://.../jsonapi'
  },
  meta: {
    deprecated: {
      'jsonapi.pathPrefix': 'This property has been deprecated and will be removed in the next version of Decoupled Router. Use basePath instead.'
    }
  }
```

I assume, that something is wrong with my remote Drupal configuration.

**Comment by kretzschr** [comment]
Checked a few more things and it turned it out, that subrequests module causes this issue. Probably it is related to this bug here: https://www.drupal.org/project/subrequests/issues/3049395

I disabled caching in Drupal and finally receive a node / taxonomy-term.

Nevertheless, I still run into empty resource values:

```
return Promise.resolve(getResourceByPath(path, {
      deserialize: options.deserialize,
      isVersionable: options.isVersionable,
      locale: context.locale,
      defaultLocale: context.defaultLocale,
      params: _extends({
        resourceVersion: previewData == null ? void 0 : previewData.resourceVersion
      }, (_options2 = options) == null ? void 0 : _options2.params)
    })).then(function (resource) {
      return !context.locale && !(resource == null ? void 0 : resource.default_langcode) ? null : resource;
    }); // If no locale is passed, skip entity if not default_langcode.
    // This happens because decoupled_router will still translate the path
    // to a resource.
    // TODO: Figure out if we want this behavior.
    // For now this causes a bug where a non-i18n sites builds (ISR) pages for
    // localized pages.
  } catch (e) {
    return Promise.reject(e);
  }
```

I'm running a non I18N-site, which results in an empty `context.locale`. Also the check for `resource.default_langcode` returns false, because the default_langcode attribute is located with the _data > attributes_ part of the JSONAPI response.

**Comment by shadcn** [comment]
@kretzschr It looks like you're hitting the same issue @Kroonax as mentioned here: https://github.com/chapter-three/next-drupal/issues/227#issuecomment-1152079200.

Is it possible to upgrade to the DrupalClient?

(I'll also be patching this in the 1.4 release)

**Comment by kretzschr** [comment]
@shadcn Of course I will give it a try.

**Comment by shadcn** [comment]
@kretzschr Since this bug came up a few times, I backported the fix and created a new release.

Can you upgrade to `next-drupal 1.4-rc1` and test please?

Note: I'd still recommend the `DrupalClient` going forward. 

Thank you.

**Comment by kretzschr** [comment]
@shadcn Ran a few tests and everything is working as expected. :)
I will now check out `DrupalClient`.

Thanks for providing the quickfix.

**Comment by kretzschr** [comment]
Thanks for providing the quickfix.
