### ISSUE TITLE
Global site search

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#229]
I have a question. If I want to implement a global search with Drupal Search API that can search through the entire site, which includes something like a home page, a contact page, etc., does this mean I need to put all these pages in Drupal as content types? 

So say I have several of these pages (home, about us, contact, additional info, etc.), should I create one content type for each page? What would be the best strategy for implementing such a global search with Search API in a decoupled structure?

Thank you.

**Comment by TheRuslan** [comment]
@fnick851 If you want to search through content with Drupal Search API so yes, that content should be in the Drupal's database.
 
You can have few separate content types or one universal content type.
For example you could create few paragraph types for different types of data and one "basic page" content type with paragraphs field. So your search api would search through that field in one content type.

Eventually Drupal is very flexible and you can choose structure for your needs.

**Comment by shadcn** [comment]
It would be same as you would implement in a non-decoupled Drupal: **the content has to be in entity types that Search API can index**.

You then ping the Search API from your Next.js site and ask for the search results.

You can configure an index that searches across mutiple entity types:

![search-index](https://user-images.githubusercontent.com/124599/173025596-da9ae07e-5a91-42b8-9741-67724dd83fe7.jpg)

**Comment by fnick851** [comment]
@TheRuslan I haven't build it out yet. But I think I have some ideas thanks for your inputs. I'll close it for now.
