### ISSUE TITLE
Preview a next.js page before publishing

### ISSUE THREAD

**Issue by rilrom** [chapter-three/next-drupal#23]
I've managed to get iframe previews working for latest version and revisions so far.
Is there a way to preview changes of a page before publishing? Clicking the 'preview' button in Drupal does not render an iframe at the moment.
I've had a look through the documentation but nothing really stands out to me. Any guidance would be greatly appreciated.

**Comment by shadcn** [comment]
Unfortunately the way preview works in Drupal, we cannot do preview without saving (we need an actual `entity` that we can pull via JSON API).

The way we handle this right now is to enable `unpublished/draft` node preview.

If you have configured a `DRUPAL_CLIENT_ID` and a `DRUPAL_CLIENT_SECRET`, you can use check for `context.preview` in `getStaticProps` and allow access.

```tsx
// Return 404 if we're not in preview and is unpublished
if (!context.preview && !node?.status) {
    return {
      notFound: true,
    }
  }

// Continue if node is unpublished but we're in preview mode.
```

Let me know if this helps. If not, I'll try to put together a better example.

**Comment by rilrom** [comment]
That is very unfortunate.

Your example was helpful however, managed to get unpublished/draft working well.

Thanks very much.
