### ISSUE TITLE
Disallow anonymous users to see the iframe preview, but keep access to JSONAPI

### ISSUE THREAD

**Issue by lodewijkloos** [chapter-three/next-drupal#238]
Not sure if this is configuration I missed…… when I turn on the (default) Iframe previewer in the Next Drupal module, all “node view” pages (for the enabled entity types) get the iframe showing the Next.js preview instead of the classic Drupal HTML render.
However this is also the case for anonymous users. And they can also see the preview secret in the HTML.
I’d like to disallow anonymous users to see the iframe preview, but when I set the permission “View published content”, anonymous users are also disallowed to do JSONAPI requests, which I need for dynamic pages.
I was able to fix this by creating a module implementing hook_next_site_preview_alter, probably I will also create a redirect that will direct anonymous users to the login page, however it would be nice to be able to configure which roles gets to see the preview.

Thanks for the Next.js for Drupal project it’s pretty cool.

**Comment by shadcn** [comment]
I see. Yeah most of our implementations redirect anonymous users to the login page as well.

However, I can see how a permission like "view the iframe preview" can be useful.

Let's see how best we can implement this.

**Comment by shadcn** [comment]
Note: This is fixed in the latest release. Anonymous users now see the live URL and do not see the secret.
