### ISSUE TITLE
Invalid preview secret in preview iFrame

### ISSUE THREAD

**Issue by Heb-l** [chapter-three/next-drupal#242]
Hey, first of all thanks for all your work on this module. It's really interesting.

I've followed the guides from here: https://next-drupal.org/learn/quick-start to set up a Drupal install and a connected Next.js site.

I'm getting an "invalid preview secret" message in the iframe Drupal side. The secrets match in both the Drupal config and the env.local file on the Next.js site.

Do you have any idea why this might be happening?

I'm using ddev, with a fresh drupal install.

![image](https://user-images.githubusercontent.com/108140168/175614909-5cc8bd9c-a646-4d10-8e0d-c82f80df67ca.png)
![image](https://user-images.githubusercontent.com/108140168/175615040-8658660e-c4ef-4a6f-a266-63ac13e736d9.png)
![image](https://user-images.githubusercontent.com/108140168/175615190-a360a160-4806-435e-b6ce-3df531180aec.png)

Thanks

**Comment by shadcn** [comment]
Hi. Can you confirm if a `previewSecret` is configured on the client?

```ts
export const drupal = new DrupalClient(
  process.env.NEXT_PUBLIC_DRUPAL_BASE_URL,
  {
    previewSecret: process.env.DRUPAL_PREVIEW_SECRET,
  }
)
```

https://next-drupal.org/docs/preview-mode

**Comment by Heb-l** [comment]
Hey, I didn't have anything in there. I've added the following in drupal.ts now, but it's still the same issue.

```
import { DrupalClient } from "next-drupal"

export const drupal = new DrupalClient(
    process.env.NEXT_PUBLIC_DRUPAL_BASE_URL,
    {
        auth: {
            username: process.env.DRUPAL_USERNAME,
            password: process.env.DRUPAL_PASSWORD,
        },
        previewSecret: process.env.DRUPAL_PREVIEW_SELECT,
    }
)
```

**Comment by Heb-l** [comment]
Yes, both patches have been applied. I've given the next.js role bypass content access permission too.

**Comment by shadcn** [comment]
Does the anonymous role have the "Issue subrequests" permission?
