### ISSUE TITLE
Environment variables include variables that are specific to certain examples

### ISSUE THREAD

**Issue by lauriii** [chapter-three/next-drupal#247]
It seems like some of the environment variables are no longer required by _next-drupal-basic-starter_ since it has started using the `DrupalClient`. At least `DRUPAL_FRONT_PAGE` and `DRUPAL_SITE_ID` seem unused, and could potentially be removed from the environment variables that are provided by the Drupal module. If we still want to keep this in the module output, I guess we should at least add a comment there that some of the environment variables are required by some of the examples, but might be unnecessary.

**Comment by shadcn** [comment]
I've created a PR to fix this. Thanks @lauriii 

https://github.com/chapter-three/next-drupal/pull/251
