### ISSUE TITLE
Error: Initial locale argument was not passed into serverSideTranslations

### ISSUE THREAD

**Issue by septembre2018** [chapter-three/next-drupal#248]
Hello,

I'm trying to test the new example-umami out of the box.
While I'm trying to access to a node i'll get the error : Initial locale argument was not passed into serverSideTranslations

Errors logs : 
`error - Error: Initial locale argument was not passed into serverSideTranslations
    at _callee$ (/Users/septembre/Documents/GitHub/japi/test-umami/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:172:19)
    at tryCatch (/Users/septembre/Documents/GitHub/japi/test-umami/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
    at Generator._invoke (/Users/septembre/Documents/GitHub/japi/test-umami/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
    at Generator.next (/Users/septembre/Documents/GitHub/japi/test-umami/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (/Users/septembre/Documents/GitHub/japi/test-umami/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/septembre/Documents/GitHub/japi/test-umami/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/septembre/Documents/GitHub/japi/test-umami/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/septembre/Documents/GitHub/japi/test-umami/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at serverSideTranslations (/Users/septembre/Documents/GitHub/japi/test-umami/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:272:17) {
  page: '/[...slug]'
}
`

I don't think it is an auth issue because all the pages works correctly except nodes.
Not sure if it come from my drupal config or something in the local dev version of example-umami. 
**Drupal instance**
Drupal : 9.4.1
Php : 8.1

**Next-drupal** 
"next": "^12.1.4",
"next-auth": "^4.3.4",
"next-drupal": "^1.4.0",
"next-i18next": "^11.0.0",

Next.config is the same as github :
```
const { i18n } = require("./next-i18next.config")

module.exports = {
  i18n,
  images: {
    domains: [process.env.NEXT_IMAGE_DOMAIN],
  },
}
```
next-i18next.config.js is the same as github
```
const path = require("path")

const config = require("./site.config")

module.exports = {
  i18n: {
    defaultLocale: config.defaultLocale,
    locales: Object.keys(config.locales),
    localePath: path.resolve("./public/locales"),
  },
}
```

Would appreciate it if someone have a clue for this

**Comment by shadcn** [comment]
@septembre2018 quick question. Are you following the guide at https://gist.github.com/shadcn/23d2cff86eb68836774f877a3ecc88a3?

**Comment by septembre2018** [comment]
no, I've tried with my server where I've install a drupal instance

**Comment by septembre2018** [comment]
HI,
I've strictly follow the guide and I still have the same error.

**Comment by shadcn** [comment]
OK this might sound like an easy fix but I just had this error as well and clearing the cache on the Drupal site fixed it. Can you give it a try?

**Comment by septembre2018** [comment]
Sorry it doesn't change anything.

**Comment by ranx2k** [comment]
Hello

I'm getting the exact same error with my Umami installation - error : Initial locale argument was not passed into serverSideTranslations

I have followed the install guide to the letter. I also have cleared the caches several times. Everything seems to be working but when I click on any node, the error pops up. 

@septembre2018 could you please tell me in more detail which permissions were to blame?

**Comment by ranx2k** [comment]
Thank you for a quick answer. I deleted everything and started from scratch. Everything is working now. 

I think that for some reason the required Drupal patches in composer.json failed to apply. That was probably the reason for the error for me.

**Comment by RobinHoutevelts** [comment]
I also can't seem to trigger the patches

```
Composer version 2.5.4 2023-02-15 13:10:06
PHP 8.1.16 (cli) (built: Feb 16 2023 07:22:21) (NTS)
```

```json
{
    "name": "drupal/recommended-project",
    "description": "Project template for Drupal projects with a relocated document root",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "homepage": "https://www.drupal.org/project/drupal",
    "support": {
        "docs": "https://www.drupal.org/docs/user_guide/en/index.html",
        "chat": "https://www.drupal.org/node/314178"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "composer-runtime-api": "^2.0.0",
        "composer/installers": "^2.0",
        "cweagans/composer-patches": "^1.7",
        "drupal/core-composer-scaffold": "^10.0",
        "drupal/core-project-message": "^10.0",
        "drupal/core-recommended": "^10.0",
        "drupal/dotenv": "^1.2",
        "drupal/jsonapi_menu_items": "^1.2",
        "drupal/jsonapi_resources": "^1.0@beta",
        "drupal/jsonapi_views": "^1.1",
        "drupal/next": "^1.6",
        "drush/drush": "^11.5"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "config": {
        "discard-changes": true,
        "platform": {
            "php": "8.1.16"
        },
        "sort-packages": true,
        "allow-plugins": {
            "ergebnis/composer-normalize": true,
            "composer/installers": true,
            "cweagans/composer-patches": true,
            "composer/package-versions-deprecated": true,
            "drupal/core-composer-scaffold": true,
            "oomphinc/composer-installers-extender": true,
            "drupal-composer/drupal-scaffold": true,
            "drupal/core-project-message": false
        }
    },
    "extra": {
        "drupal-scaffold": {
            "locations": {
                "web-root": "public/"
            }
        },
        "installer-paths": {
            "public/core": [
                "type:drupal-core"
            ],
            "public/libraries/{$name}": [
                "type:drupal-library"
            ],
            "public/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "public/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "public/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "drush/Commands/contrib/{$name}": [
                "type:drupal-drush"
            ],
            "public/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "public/profiles/custom/{$name}": [
                "type:drupal-custom-profile"
            ],
            "public/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ]
        },
        "extra": {
            "composer-exit-on-patch-failure": true,
            "patches": {
                "drupal/subrequests": {
                    "Get same results on different request": "https://www.drupal.org/files/issues/2019-07-18/change_request_type-63049395-09.patch"
                },
                "drupal/decoupled_router": {
                    "Unable to resolve path on node in other language than default": "https://www.drupal.org/files/issues/2021-05-05/3111456-34.patch"
                }
            }
        }
    }
}
```
