### ISSUE TITLE
Error: Umami Example: Articles Api: drupal.createFileResource() 

### ISSUE THREAD

**Issue by MokDevelopment** [chapter-three/next-drupal#249]
I was able to set up the Umami example by following the guide. 

I found an issue when trying to create an article node via the **form--article component**, which is using the /api/articles api endpoint.

**Path: /pages/api/articles/index.ts**

I receive a server error (500) when getting to this part of the script (line 66):

> const file = await drupal.createFileResource<DrupalFile>(
      "media--image",
      {
        data: {
          type: "field_media_image",
          attributes: {
            filename: fields.image.newFilename,
            file: await fs.readFile(fields.image.filepath),
          },
        },
      },
      {
        withAuth: session.accessToken,
      }
    )

When I comment out the whole image creation the node is created correctly in the drupal database (so it is not a connection, authorization issue I believe)

Drupals logs stay clean.

Could somebody check if the used drupal.createFileResource() method is somehow outdated?

Thanks

**Comment by shadcn** [comment]
Can you add a log in the catch in pages/api/articles.ts?

**Comment by MokDevelopment** [comment]
PINO says:

`{"level":30,"time":1656677372592,"pid":81479,"hostname":"50","err":{"type":"Error","message":"Resource of type 'undefined' not found.","stack":"Error: Resource of type 'undefined' not found.\n    at /Users/mk/WORK/WORKSPACE/react/next-example-umami-main/node_modules/next-drupal/dist/index.js:2023:17\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async handler (webpack-internal:///(api)/./pages/api/articles/index.ts:65:22)\n    at async Object.apiResolver (/Users/mk/WORK/WORKSPACE/react/next-example-umami-main/node_modules/next/dist/server/api-utils/node.js:179:9)\n    at async DevServer.runApi (/Users/mk/WORK/WORKSPACE/react/next-example-umami-main/node_modules/next/dist/server/next-server.js:381:9)\n    at async Object.fn (/Users/mk/WORK/WORKSPACE/react/next-example-umami-main/node_modules/next/dist/server/base-server.js:488:37)\n    at async Router.execute (/Users/mk/WORK/WORKSPACE/react/next-example-umami-main/node_modules/next/dist/server/router.js:213:36)\n    at async DevServer.run (/Users/mk/WORK/WORKSPACE/react/next-example-umami-main/node_modules/next/dist/server/base-server.js:621:29)\n    at async DevServer.run (/Users/mk/WORK/WORKSPACE/react/next-example-umami-main/node_modules/next/dist/server/dev/next-dev-server.js:533:20)"},"msg":"Resource of type 'undefined' not found."}`

**Comment by MokDevelopment** [comment]
I added the two values to the attributes object:


>            type: 'media--image',
>            field: 'field_media_image',          

and it seems to work... I just don't understand why ;)

**Comment by MokDevelopment** [comment]
Thank you too. 
May I ask if the outdated logic is also applies to the "next-drupal" library or is it just the Umami Example code base?

**Comment by shadcn** [comment]
Looks like it's only the separate repo at https://github.com/chapter-three/next-example-umami that needs updating.

The example here is up to date: https://github.com/chapter-three/next-drupal/tree/main/examples/example-umami

**Comment by shadcn** [comment]
Done. I've updated the example. https://github.com/chapter-three/next-example-umami/blob/898669660bb7cda03ebc3e2c6bcca185ca774e9e/pages/api/articles/index.ts#L64
