### ISSUE TITLE
Upgrade guide for DrupalClient missing withAuth

### ISSUE THREAD

**Issue by lauriii** [chapter-three/next-drupal#252]
We are updating `next-acms` starterkit to use _DrupalClient_ on https://github.com/acquia/next-acms/pull/39. We followed steps from https://next-drupal.org/docs/upgrade-guide but it resulted in all of the requests being made as anonymous user, leading into permission issues and pages failing to render. To get the same behavior as with the previous APIs, it is required to also have `withAuth: true` in the _DrupalClient_ options.

**Comment by shadcn** [comment]
Step 5 on the Upgrade Guide covers the `withAuth` option. 

I'm open to suggestions on how we can improve this part of the docs :)

**Comment by lauriii** [comment]
Thanks for the quick response! I somehow missed that step completely 👍

If you want to reduce chances of that happening to others, it might make sense to cover it around step 2 where authorization is mentioned earlier.

**Comment by shadcn** [comment]
@lauriii I created a PR with updated docs: https://github.com/chapter-three/next-drupal/pull/253
