### ISSUE TITLE
Issue with [...slug].js

### ISSUE THREAD

**Issue by nishud16** [chapter-three/next-drupal#259]
I am building a PLP with url structure as /shop/[...slug]

directory structure :
pages -> shop -> [...slug].js

export async function getStaticPaths(context) {
    return {
        paths: await getPathsFromContext(['taxonomy_term--product_category'], context),
        fallback: 'blocking',
    };
}
/*
 * Use below function to get node/product details
 * */
export async function getStaticProps(context) {
    const path = await translatePathFromContext(context);
    if (!path) {
        return {
            notFound: true,
        };
    }

    const type = path.jsonapi.resourceName;

    const productCategories = await getResourceFromContext(type, context);
    params['filter'] = {
        field_product_category: productCategories.length
          ? productCategories[0].drupal_internal__tid
          : 8,
    };
    params['include'] =
      'field_product_image.field_large_screen_image.field_media_image,' +
      'field_product_image.field_medium_screen_image.field_media_image,' +
      'field_product_image.field_small_screen_image.field_media_image';
    const resource = await getSearchIndexFromContext(
      'commercefactory',
      context,
      {
          deserialize: false,
          params,
      }
    );

    // At this point, we know the path exists and it points to a resource.
    // If we receive an error, it means something went wrong on the Drupal.
    // We throw an error to tell revalidation to skip this for now.
    // Revalidation can try again on next request.
    if (!resource) {
        throw new Error(`Failed to fetch resource: ${path.jsonapi.individual}`);
    }

    // If we're not in preview mode and the resource is not published,
    // Return page not found.
    if (!context.preview && resource?.status === false) {
        return {
            notFound: true,
        };
    }

    return {
        props: {
            nodes: deserialize(resource),
            facets: resource.meta.facets
        },
        revalidate: 900,
    };
}

I am having issue in fetching data on the frontend.

**Comment by nishud16** [comment]
Thanks for the response @shadcn .

But on update i get the following error:

**CODE**
`export async function getStaticPaths(context) {
    return {
        paths: await getPathsFromContext(['taxonomy_term--product_category'], context),
        fallback: 'blocking',
    };
}

export async function getStaticProps(context) {
    const path = await translatePathFromContext(context);
    if (!path) {
        return {
            notFound: true,
        };
    }

    const type = path.jsonapi.resourceName;

    const productCategories = await getResourceFromContext(type, context);
    params['filter'] = {
        field_product_category: productCategories.length
          ? productCategories[0].drupal_internal__tid
          : 8,
    };
    params['include'] =
        'field_product_image.field_large_screen_image.field_media_image,' +
        'field_product_image.field_medium_screen_image.field_media_image,' +
        'field_product_image.field_small_screen_image.field_media_image';
    params['sort'] = {
        'sort-field_product_sale_purchase_pric': {
            path: 'field_product_sale_purchase_pric',
            direction: 'ASC'
        }
    }
    const results = await getSearchIndexFromContext(
        'commercefactory',
        context,
        {
            pathPrefix: '/shop',
            deserialize: false,
            params,
        }
    );
    return {
        props: {
            phonesApiData: deserialize(results),
            phonesFacetsApiData: results.meta.facets,
            paginationLinks: results.links,
        },
    };
}`

**ERROR**
Error: A required parameter (slug) was not provided as a string in getStaticPaths for /shop/[slug]

**Comment by shadcn** [comment]
You need to pass it to `getResourceFromContext`.

**Comment by nishud16** [comment]
Is it possible we can connect in a chat room or via google meet i am still facing issue

**Comment by shadcn** [comment]
I'm on Drupal Slack in #nextjs channel: https://drupal.slack.com/archives/C01E36BMU72

**Comment by shadcn** [comment]
@nishud16 Did you figure this out?

**Comment by nishud16** [comment]
@shadcn Yes the fix with path prefix worked for me. Earlier it wasn’t working due to some config issue at drupal end.

**Comment by devtim123** [comment]
@nishud16 can i ask you how you configured drupal to get this to work? for me this is not working and i try to figure out why. looking into the function "getResourceFromContext" it will actually add the prefix to subrequest query like "/router/translate-path?path=${path}" and ${path} have the prefix configured in the option paramter. But Drupal Backend has no clue about the prefix, because alias is without this prefix. only nextJS app knows prefix because all CMS generated site living under certian directory like in your example "shop/[...slug].js".

so my question, how you solved that in drupal backend? do i miss some configuration like NextJs-Site base url? or do use use prefix in alias? but this also not works because urls for content would then have e.g. "/shop/shop/article-example" because slug consists of prefix, which makes no sense.

any hint here would be helpful, thanks! :)

**Comment by shadcn** [comment]
@devtim123 The `pathPrefix` option is used when your `[...slug].tsx` is nested under a directory in Next.js

## Example

Let's say you have an `Article` content type in Drupal with the following path pattern `/blog/[node:title]`.

Your article nodes will have path aliases as follows:

- `/blog/article-one`
- `/blog/article-two`

There are two ways you can fetch and render these pages on Next.js:

1. Root `/pages/[...slug].tsx`
2. Nested `/pages/blog/[...slug].tsx`

## 1. Root `/pages/[...slug].tsx` (Recommended - Easier)

Here `slug` will have values like:

- `/blog/article-one`
- `/blog/article-two`

There's no additional work to be done for fetching `node--article`. `getStaticPaths` and `getStaticProps` will properly handle the aliases for you.

## 2. Nested `/pages/blog/[...slug].tsx`

Here `slug` will have values like:

- `/article-one`
- `/article-two`

**Note the missing `/blog` prefix**

We have to tell `getStaticProps` about the prefix:

```ts
const node = await drupal.getResourceFromContext("node--page", context, {
  pathPrefix: "/blog" // <------- 👈,
})
```

Hope this helps. Let me know if you have any other questions.
