### ISSUE TITLE
TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object

### ISSUE THREAD

**Issue by demo-Ghost** [chapter-three/next-drupal#26]
Hi! Thanks for all the work you've put into this project. 
I'm following the quick start tutorial and have managed to set things up, after a some setbacks with simple_oauth library.

But, currently, I'm having an issue viewing my blog posts. I can see them at the home page and can also see that all their content is fetched in home page, as a collection. But once I visit a specific one (blog/first-post, as in blog/[node:title]), I get a 404 in the Network tab in Google Chrome.

And also this error.

```
 1 of 1 unhandled error

Unhandled Runtime Error
Error: Failed to load script: /_next/static/chunks/pages/404.js

Source
.next\static\chunks\main.js (83:51) @ HTMLScriptElement.script.onerror

  81 | //    executes when `src` is set.
  82 | script.onload = resolve;
> 83 | script.onerror = ()=>reject(markAssetError(new Error(`Failed to load script: ${src}`)))
     |                                           ^
  84 | ;
  85 | // 2. Configure the cross-origin attribute before setting `src` in case the
  86 | //    browser begins to fetch.
```

I guess the following error is due to not getting any data in the response.

```
error - TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
    at Function.byteLength (buffer.js:726:11)
    at ServerResponse.apiRes.end (C:\Users\trogl\Desktop\next-next-next\node_modules\next\dist\server\api-utils.js:72:41)
    at C:\Users\trogl\Desktop\next-next-next\node_modules\next-drupal\dist\index.js:566:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.apiResolver (C:\Users\trogl\Desktop\next-next-next\node_modules\next\dist\server\api-utils.js:101:9)
    at async DevServer.handleApiRequest (C:\Users\trogl\Desktop\next-next-next\node_modules\next\dist\server\next-server.js:770:9)
    at async Object.fn (C:\Users\trogl\Desktop\next-next-next\node_modules\next\dist\server\next-server.js:661:37)
    at async Router.execute (C:\Users\trogl\Desktop\next-next-next\node_modules\next\dist\server\router.js:205:32)
    at async DevServer.run (C:\Users\trogl\Desktop\next-next-next\node_modules\next\dist\server\next-server.js:841:29) {
  code: 'ERR_INVALID_ARG_TYPE',
  page: '/api/preview'
}
```

**Comment by shadcn** [comment]
Is this happening in the Drupal preview only? What happens if you visit the post directly?

**Comment by demo-Ghost** [comment]
You mean from Next.js or in Drupal?

**Comment by demo-Ghost** [comment]
On the Next site, homepage for the default-starter works great. Plus, I see all the data of the collection.
![image](https://user-images.githubusercontent.com/37753045/137018760-5bac8a3c-c2a4-48e5-afb8-86560bf577eb.png)

but if I click on one of the posts, I get this
![image](https://user-images.githubusercontent.com/37753045/137018905-13db324b-1b7d-4bc3-b5af-407ab5d75a57.png)

**Comment by demo-Ghost** [comment]
@shadcn In my case, this is a local environment in Windows, with Xampp.
Other than that, just follow the exact instructions on Quick Start guide https://next-drupal.org/docs/quick-start.
That's about it I think, the repo is the same as the basic starter.

**Comment by taku3202** [comment]
I am experiencing the same phenomenon.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
    at new NodeError (node:internal/errors:371:5)
    at Function.byteLength (node:buffer:733:11)
    at ServerResponse.apiRes.end (/opt/preview/.docker/preview/node_modules/next/dist/server/api-utils.js:72:41)
    at /opt/preview/.docker/preview/node_modules/next-drupal/dist/index.js:593:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/opt/preview/.docker/preview/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/opt/preview/.docker/preview/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/opt/preview/.docker/preview/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/opt/preview/.docker/preview/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/opt/preview/.docker/preview/node_modules/next/dist/server/next-server.js:841:29) {
  code: 'ERR_INVALID_ARG_TYPE'
```

The version I am using is as follows.
- `next-drupal: 0.16.2`
- `next.js` (Drupal Module): [1.0.0-beta5](https://www.drupal.org/project/next/releases/1.0.0-beta5)


I refer to this [code](https://git.drupalcode.org/project/next/-/commit/5700aae60a175ce63b2996d88b30314bedb2ca13),
On the Drupal side, the page loaded successfully by applying the following patch to the [subrequests](https://www.drupal.org/project/subrequests) module.

```diff
        "patches": {
+	    "drupal/subrequests": {
+                "Subrequest failed validation": "https://www.drupal.org/files/issues/2019-05-27/3029570-array-not-object.patch",
+                "Get same results on different request": "https://www.drupal.org/files/issues/2019-07-18/change_request_type-63049395-09.patch"
+            }
        },


```

**Comment by KojoEnch** [comment]
I faced the same issue. As per @taku3202 comment, applying Drupal Subrequests patches solved it :

- [Subrequest failed validation ](https://www.drupal.org/project/subrequests/issues/3029570#comment-13151631)
- [Get same results on different request](https://www.drupal.org/project/subrequests/issues/3049395#comment-13187043)

**Comment by shadcn** [comment]
@demo-Ghost Did you figure this out?

**Comment by claudiu-cristea** [comment]
I'm getting the same error in preview. My Drupal site base URL is http://localhost:8080/blog/drupal/web

**Comment by claudiu-cristea** [comment]
Also, applying the patches from https://github.com/chapter-three/next-drupal/issues/26#issuecomment-945509653 didn't help

**Comment by claudiu-cristea** [comment]
Just for debugging I've replaced the `RouterPathTranslatorSubscriber::cleanSubdirInPath()` method (see https://github.com/chapter-three/next-drupal/issues/26#issuecomment-950711871) with:

```php
  protected function cleanSubdirInPath($path, Request $request) {
    // Remove any possible leading subdir information in case Drupal is
    // installed under http://example.com/d8/index.php
    if (strpos($path, '/blog/drupal/web/') === 0) {
      $path = substr($path, strlen('/blog/drupal/web/'));
    }
    return $path;
  }
```

...and it fixes the issue.

Note that I've hardcoded my _base path_ because it seems that I couldn't get it from request. What comes from `$request->getBasePath()` is an empty string. Same is stored in `$GLOBALS['base_path']`.

However, we need permanent fix. I see there is https://www.drupal.org/project/decoupled_router/issues/3133873 but the patch over there is not resolving the issue.

**Comment by claudiu-cristea** [comment]
So this works but don't ask my why :) The Symfony request stored in `$GLOBALS['request']` contains the correct base path information. But I have no idea why they are different...

```php
  protected function cleanSubdirInPath($path, Request $request) {
    // Remove any possible leading subdir information in case Drupal is
    // installed under http://example.com/d8/index.php
    $regexp = preg_quote($GLOBALS['request']->getBasePath(), '/');
    return preg_replace(sprintf('/^%s/', $regexp), '', $path);
  }
```

**Comment by claudiu-cristea** [comment]
Ok, so I've reworked https://www.drupal.org/project/decoupled_router/issues/3133873. @demo-Ghost could you try to apply also the https://git.drupalcode.org/project/decoupled_router/-/merge_requests/3.diff patch to `decoupled_router` module and see if fixes the issue? It does for me.

(However, still don't understand why, in `cleanSubdirInPath()`, `$request` and `$GLOBALS['request']` are diverged)

**Comment by demo-Ghost** [comment]
I'll give it a shot @claudiu-cristea and I'll let you know.

**Comment by vermario** [comment]
@claudiu-cristea hi! I had the same issue described here, and your last patch fixed it!
