### ISSUE TITLE
Support for react 18

### ISSUE THREAD

**Issue by Defranos** [chapter-three/next-drupal#260]
Hello,

I'm on a project that uses this library and in the process of migrating towards React 18.
However, because of a version mismatch with this library use of React version (17), we are facing errors.

Any plans on upgrading ?

**Comment by shadcn** [comment]
@Defranos What's the error?

(We are looking into upgrading soon. I'm currently testing next 12.2.0 as well)

**Comment by JohnAlbin** [comment]
This was fixed with https://github.com/chapter-three/next-drupal/pull/387
