### ISSUE TITLE
field_media_image is not a valid relationship field name

### ISSUE THREAD

**Issue by o771e** [chapter-three/next-drupal#264]
I tried Drupal 9.4.2 and the latest basic starter project.

![image](https://user-images.githubusercontent.com/88319069/179276507-219aa743-4a94-49af-9d83-570c4232e771.png)

**Comment by shadcn** [comment]
The basic-starter is set to pull from content from https://cms.next-drupal.org (for quick start).

You can remove the fields and include when pulling from your own site.

**Comment by shadcn** [comment]
We've decided to update the basic-starter to make it work with a vanilla Drupal install instead of a custom one.

This should fix this error.

Thanks for reporting.
