### ISSUE TITLE
[next-drupal-basic-starter] TypeScript Errors in Preview API Route

### ISSUE THREAD

**Issue by backlineint** [chapter-three/next-drupal#268]
Steps to duplicate:
* Create Next for Drupal Project as outlined here: https://next-drupal.org/learn/quick-start/create-nexts-project, connecting to a Drupal Backend as configured in the documentation.
* run `yarn dev` and confirm that site functions.
* run `yarn build` which throws the following Type error:

===

yarn build
yarn run v1.22.18
$ next build
info  - Loaded env from /Users/brianperry/repos/next-for-drupal-fe-demo/.env.local
Failed to compile.

./pages/api/preview.ts:9:40
Type error: Argument of type 'import("/Users/brianperry/repos/next-for-drupal-fe-demo/node_modules/next/dist/shared/lib/utils").NextApiResponse<any>' is not assignable to parameter of type 'import("/Users/brianperry/repos/next-for-drupal-fe-demo/node_modules/next-drupal/node_modules/next/dist/shared/lib/utils").NextApiResponse<any>'.
  Property 'revalidate' is missing in type 'ServerResponse & { send: Send<any>; json: Send<any>; status: (statusCode: number) => NextApiResponse<any>; redirect(url: string): NextApiResponse<...>; redirect(status: number, url: string): NextApiResponse<...>; setPreviewData: (data: string | object, options?: { ...; }) => NextApiResponse<...>; clearPreviewData: (...' but required in type '{ send: Send<any>; json: Send<any>; status: (statusCode: number) => NextApiResponse<any>; redirect(url: string): NextApiResponse<any>; redirect(status: number, url: string): NextApiResponse<...>; setPreviewData: (data: string | object, options?: { ...; }) => NextApiResponse<...>; clearPreviewData: () => NextApiRespo...'.

   7 |   response: NextApiResponse
   8 | ) {
>  9 |   return await drupal.preview(request, response);
     |                                        ^
  10 | }
  11 | 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

===

As a temporary workaround, I removed the response from the call to Drupal.preview: https://github.com/backlineint/next-for-drupal-fe-demo/commit/3ef8faa88df6b5ce3662033c1c14764692bd24d9

**Comment by shadcn** [comment]
We've upgraded the `next` version in the starter and fixed the issue. Thank you.
