### ISSUE TITLE
Hard-coded reference to "field_image" causes 400 error when using Umami

### ISSUE THREAD

**Issue by webchick** [chapter-three/next-drupal#275]
I'm trying to play around with this project, and set up a local replica of the [demo](https://demo.next-drupal.org/) which seems to be having problems atm. Using Drupal 9.4.5 and attempting to install the Umami profile.

I followed along with your [very helpful getting started documentation](https://next-drupal.org/learn/quick-start), and all was going well until [Start Development Server](https://next-drupal.org/learn/quick-start/create-nexts-project) when I receive the error:

<img width="992" alt="Error: 400 Bad Request: `field_image` is not a valid relationship field name. Possible values: node_type, revision_uid, uid, menu_link, field_media_image, field_tags." src="https://user-images.githubusercontent.com/332535/183255666-29068e4f-b6ee-4376-8cf8-239ac082749f.png">

From the console:

```
error - JsonApiErrors: 400 Bad Request
`field_image` is not a valid relationship field name. Possible values: node_type, revision_uid, uid, menu_link, field_media_image, field_tags.
    at /usr/local/var/www/next-app/node_modules/next-drupal/dist/index.js:2493:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getStaticProps (webpack-internal:///./pages/index.tsx:97:19)
    at async Object.renderToHTML (/usr/local/var/www/next-app/node_modules/next/dist/server/render.js:368:20)
    at async doRender (/usr/local/var/www/next-app/node_modules/next/dist/server/base-server.js:906:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/usr/local/var/www/next-app/node_modules/next/dist/server/base-server.js:1011:28)
    at async /usr/local/var/www/next-app/node_modules/next/dist/server/response-cache.js:69:36 {
  errors: [
    {
      title: 'Bad Request',
      status: '400',
      detail: '`field_image` is not a valid relationship field name. Possible values: node_type, revision_uid, uid, menu_link, field_media_image, field_tags
.',
      links: [Object]
    }
  ],
  statusCode: 400,
  page: '/'
}
```

This is indeed a problem, because the Article field's name in Umami is not field_image, but rather field_media_image.

<img width="1276" alt="Screenshot of content type configuration page showing fields, including field_media_image" src="https://user-images.githubusercontent.com/332535/183255864-20317443-680f-43fd-bdf6-af56657c7655.png">

Since Drupal doesn't let you rename fields with values in them, your only recourse is to drop + re-create the field with the appropriate name, but then that _also_ drops all the gorgeous pictures in the process (which, come to think of it, might be what's going on with the demo atm :P).

ANYWAY. I can see a few different ways to handle this:

1) In addition to the other patches you have people install at https://next-drupal.org/learn/quick-start/apply-patches add another one that renames the field in Umami (would also need to swap the position of those steps, since this would only help if it was applied **before** installing Drupal)

2) In the next.js app, somehow "variable-ize" `node.field_image` to take in the name of the image field from the content type dynamically. (I know absolutely nothing about Next.js, so have no idea if this is even possible. :D Maybe via an ENV variable?)

3) Your awesome idea here! ;)

**Comment by shadcn** [comment]
Hey Angie 👋 

Are you using the basic starter?

So the basic starter is configured to work with a vanilla Drupal (which has an Article type with `field_image`). 

If you want to test the Umami profile, we have a Umami example [here]( https://github.com/chapter-three/next-drupal/tree/main/examples/example-umami) and a guide on how to run it locally: https://next-drupal.org/guides/umami-demo


The Umami demo is configured to use the `field_media_image` media reference field. 

Can you take a look and see if this helps?


Thank you.

**Comment by webchick** [comment]
Oh hey, thanks so much for the quick response! :D When you select "Standard" things do indeed seem to work! I'll try the Umami demo shortly.

If you're interested, I created PR #276 to add your helpful pointers to the getting started guide for the next person who tries to do this.
