### ISSUE TITLE
 Path translation in Umami demo does not follow  getPathsFromContext or buildPathsFromResources and got a 404 error

### ISSUE THREAD

**Issue by jeyram** [chapter-three/next-drupal#280]
Hi, I've found an  issue with the path's translation. Drupal set both  [node:title] languages, but when I switch between them in the Next SSR, it doesn't find the "/en/[node:source:title]-Spanish path" and generates a 404. 

The problem is also present  in your demo site (https://demo.next-drupal.org/es/recipes/bizcochos-veganos-de-chocolate-y-nueces) as shown below
![issue-umami-demo](https://www.dropbox.com/s/wjv6lkg41rc0q0c/isuue-drupal-next.gif?raw=1)

I'm a noob in Next.js  but I think this is related to the way the locale-switcher component is created.

I'm trying something related to this answer: 

> Maybe we can check node for system field "content_translations" somewhere in getPathsFromContext or buildPathsFromResources and return only such path which is exist in both nextjs and drupal locales?

We could. I'll look into it.

For now, I think what you could do is use two different calls for paths.

```ts
const pathsWithLocale = await getPathsFromContext("node--product", context)
const pathsWithoutLocale = await getPathsFromContext("node--blog", {})

const paths = [
    ...pathsWithLocale,
    ...pathsWIthoutLocale,
]
```

Can you give this a try and let me know?

_Originally posted by @shadcn in https://github.com/chapter-three/next-drupal/issues/147#issuecomment-1098144089_

**Comment by jeyram** [comment]
Hi, I've found an  issue with the path's translation. Drupal set both  [node:title] languages, but when I switch between them in the Next SSR, it doesn't find the "/en/[node:source:tilte]-Spanish path" and generates a 404. 

The problem is also present  in your demo site (https://demo.next-drupal.org/es/recipes/bizcochos-veganos-de-chocolate-y-nueces) as shown below
![issue-umami-demo](https://www.dropbox.com/s/wjv6lkg41rc0q0c/isuue-drupal-next.gif?raw=1)


I'm a noob in Next.js  but I think this is related to the way the locale-switcher component is created.

**Comment by shadcn** [comment]
You're right. 

For the Umami demo, we updated the path aliases to `[node:source:title]`. By sharing the path (with the `locale` prefix), we get automatic handling for localized routes on the Next.js side.

<img width="706" alt="S744jDF4" src="https://user-images.githubusercontent.com/124599/185877260-969fc901-6ee9-4b38-8783-16c61a84e335.png">

(It looks like we need to fix the CTA link in the front page hero to use the new path)

**Comment by shadcn** [comment]
Update: I fixed the path for the front page CTA. Thank you.
