### ISSUE TITLE
Drupal Preview not working

### ISSUE THREAD

**Issue by taskrider2022** [chapter-three/next-drupal#284]
Hi,

I install Drupal and a next client on basis of the Marketing/Umani example. The local next.js site will work instantly but if I try to see the preview in the Drupal backend I became an error with the following message.

```
Server Error
Error: The path alias is missing for entity with slug /home.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///xxx/node_modules/next-drupal/dist/index.js (2093:30)
processTicksAndRejections
node:internal/process/task_queues (96:5)
async Object.apiResolver
file:///xxx/node_modules/next/dist/server/api-utils/node.js (184:9)
async DevServer.runApi
file:///xxx/node_modules/next/dist/server/next-server.js (403:9)
async Object.fn
file:///xxx/node_modules/next/dist/server/base-server.js (493:37)
async Router.execute
file:///xxx/node_modules/next/dist/server/router.js (222:36)
async DevServer.run
file:///xxx/node_modules/next/dist/server/base-server.js (612:29)
async DevServer.run
file:///xxx/node_modules/next/dist/server/dev/next-dev-server.js (569:20)
async DevServer.handleRequest
file:///xxx/node_modules/next/dist/server/base-server.js (311:20)
```

In the terminal console it will try to open this path ```http://localhost:3000/api/preview?secret=secret&slug=/home&locale=de&defaultLocale=de&resourceVersion=rel%3Alatest-version```

The module pathauto is installed and will work if I use the page over http://localhost:3000

**Comment by shadcn** [comment]
Can you check if you have the required patches applied? See https://next-drupal.org/learn/quick-start/apply-patches
