### ISSUE TITLE
Preview shows 404 for unpublished

### ISSUE THREAD

**Issue by MokDevelopment** [chapter-three/next-drupal#288]
For testing purposes I installed a fresh Drupal instance + basic starter for (Next Drupal 1.4.0).

Also I set up the Bearer Authentication. I followed the guide until the end. 

Now I created an article node. Published it and can preview it in Drupal via the Frame. 

When I change the status  state to "unpublished" the Iframe shows a 404. ....weird?!

<img width="937" alt="scr1" src="https://user-images.githubusercontent.com/80107399/188286986-c55bf70b-8217-4fc6-9a7f-8df4fe887426.png">

However - even weirder... after getting the url of the iframe ...

<img width="1103" alt="scr2" src="https://user-images.githubusercontent.com/80107399/188287045-2b12f66e-b507-4357-9669-6785f0aafc22.png">

... + opening it in a fresh tab, I can access the preview fine... I just see an additional black bar telling me I am in preview, 
that is not seen when using the iFrame. 

<img width="850" alt="scr3" src="https://user-images.githubusercontent.com/80107399/188287131-b3bb6b68-724a-434b-aff3-37c022843072.png">

Outside the preview - so when using **localhost:300/blog/article-1** the route throws a  404 like expected.

**Comment by shadcn** [comment]
See `forceIframeSameSiteCookie ` on https://next-drupal.org/docs/configuration

**Comment by MokDevelopment** [comment]
I do so. Cheers !

**Comment by MokDevelopment** [comment]
It works. Thank you.
