### ISSUE TITLE
Subrequests: get same results on different request

### ISSUE THREAD

**Issue by MathiasGmeiner** [chapter-three/next-drupal#29]
For those who have problems to get the node content:

We had the same problem as described in this issue: https://www.drupal.org/project/subrequests/issues/3049395

After applying the patch https://www.drupal.org/files/issues/2019-07-18/change_request_type-63049395-09.patch the results from the subrequests are fine.

Our installations:
Drupal 9.2.7
Subrequests 3.0.3
Next 1.0.0-beta5
PHP 7.3

**Comment by shadcn** [comment]
I've updated the docs to include the patches: https://next-drupal.org/learn/quick-start/apply-patches
