### ISSUE TITLE
Module version on drupal.org not updated

### ISSUE THREAD

**Issue by GeneralBouLi** [chapter-three/next-drupal#291]
Bonjour / Hi,

_https://www.drupal.org/project/next_ is the first work source for all Drupal developer and the module's version page is not update since 1.3.0.
We knew the last security patch because we checked (or a bot) all security fix regularly in find _https://www.drupal.org/sa-contrib-2022-054_.
Can you update the page module ?

**Comment by shadcn** [comment]
Hi. The `1.3.0` is the latest release (with the security fix).

![l1LPuERZ](https://user-images.githubusercontent.com/124599/189320590-679ac85a-23f0-40dd-ae4e-b6106cebe853.png)
