### ISSUE TITLE
Why "getStaticProps" runs when I add new content to Drupal

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#296]
Doesn't "getStaticProps" only run once during build time?

Then why if I add content to Drupal in production, refresh the page, the new data will show on the page? (I call getResourceFromContext in getStaticProps.) "getStaticProps" shouldn't run after it is deployed and the new data will not be fetched. No?

Could you help me understand how it works?

**Comment by fnick851** [comment]
@shadcn 
Thanks a lot for so many information!

The on-demand ISR seems magical. Does `next-drupal` have this built in? 
I assume it's not and the developer needs to implement one of these strategies.

**Comment by shadcn** [comment]
Yes `next-drupal` has on-demand ISR built in. See the guide at https://next-drupal.org/guides/on-demand-revalidation

**Comment by fnick851** [comment]
@shadcn 
Awesome. Thanks!
