### ISSUE TITLE
Next.js sites should be environment specific or handled as content. (not as configuration)

### ISSUE THREAD

**Issue by MokDevelopment** [chapter-three/next-drupal#298]
I receive error logs as either 

1. localhost is not reachable by the production site when revalidating
2. the content does not exists on localhost (testing)
3. editors see the wrong preview 

The last one I was able to hack away by creating a custom module that modifies the form. Still kinda ugly. 

I understand that seeing "sites" as configuration makes all a bit easier, but it created a lot of issues on the other hand. Are there plans to implement hooks or settings (setting.php) in the future to kind of hide a non env specific "next js destination"?

**Comment by theodorosploumis** [comment]
One solution is to **exclude** this config values on every environment. Another one is to use one only environment entry and **override** it on settings.php.

Exclude on config.

```
$settings['config_exclude_modules'] = [
  'next.next_site.production',
  'next.next_site.stage',
  'next.next_site.localhost',
];
```

Override (eg for "localhost")

```
$next_url = "https://my-drupal-cms-domain.com";
$config['next']['next_site']['localhost']['base_url'] = $next_url;
$config['next']['next_site']['localhost']['preview_url'] = $next_url . "/api/preview";

```

**Comment by shadcn** [comment]
@MokDevelopment I was going to suggest what @theodorosploumis said. 

Keep your sites configured for your prod environments then in override the values in your `settings.local.php`.

**Comment by MokDevelopment** [comment]
Seems that $settings ['config_exclude_modules'] is not for excluding configs. It is for excluding "modules"

https://drupal.stackexchange.com/questions/291639/how-does-the-new-config-exclude-modules-setting-work-exactly

**Comment by backlineint** [comment]
Closing as stale. And based on the discussion here this should be possible with config ignore, config split, settings.php overrides, or some combination of those approaches.
