### ISSUE TITLE
Is there a way to use subrequests with next-drupal?

### ISSUE THREAD

**Issue by YahyaAhmad** [chapter-three/next-drupal#299]
Hello, I was wondering if I can use subrequests while getting resources, for example, using a custom rest resource and getting a resource using 'getResource' function simultaneously. It seems that the subrequests feature is only internal in the package. Is there a way to use any other request while using next-drupal internal functions like 'getResource'?

**Comment by shadcn** [comment]
You can't use `getResource` in a subrequests but you can use `drupal.fetch` to make subrequests call. It will looks like this:

```ts
// 1️⃣ Construct the /subrequests URL.
const url = drupal.buildUrl("/subrequests", {
  _format: "json",
})

// 2️⃣ Create the payload.
const payload = [
  {
    requestId: "rest",
    action: "view",
    uri: `/path-to-rest-resource`,
  },
  {
    requestId: "jsonapi",
    action: "view",
    uri: `/jsonapi/node/article/0557fb1e-8f4b-413e-9589-46b7ae564cdc`,
    headers: { Accept: "application/vnd.api+json" },
  },
]

// 3️⃣ Make the request.
const response = await drupal.fetch(url.toString(), {
  method: "POST",
  redirect: "follow",
  body: JSON.stringify(payload),
})

const json = await response.json()

```

**Comment by YahyaAhmad** [comment]
Ok, this is what I needed, thank you @shadcn
