### ISSUE TITLE
Filter fields by multiple values (SearchAPI).

### ISSUE THREAD

**Issue by mmedinam1600** [chapter-three/next-drupal#303]
I am using the [SearchAPI](https://next-drupal.org/guides/search-api) guide, along with the [advanced example](https://github.com/chapter-three/next-drupal/blob/main/examples/example-search-api/pages/advanced.tsx).

And modify the input radio to input checkbox, to filter by multiple fields, but I still don't know how to do it.

To filter by multiple fields I have tried sending an:
* Array
* Using OR operators
But none of them work

```javascript
const params = {
  fields: {
    "node--property_listing":
      "id,title,field_status,field_images,field_location",
  },
  filter: {
    "field_type": "rent"
    //"field_type": ["rent", "sell"] //Not work
    //"field_type": "rent,sell" //Not work
    //"field_type": "rent OR sell" //Not work
    //"field_type": "rent || sell" //Not work
  },
}
```
In the above example I want to filter a field with multiple values, but I have not been able to achieve this.
I hope you can help me to find a way to do it.

![image](https://user-images.githubusercontent.com/29582013/192330571-20e5202c-da99-49ca-903e-148594314b02.png)

**Comment by shadcn** [comment]
To use OR conjunction, you will need to use a group.

1. Create a group. Group can have `OR` or `AND` conjunction.
2. Then add filters to the group.

```js
const params = {
  fields: {
    "node--property_listing": "id,title,field_status,field_images,field_location",
  },
  filter: {
    type: { group: { conjunction: "OR" } },
    type_rent: { condition: { path: "type", value: "rent", memberOf: "type" } },
    type_sell: { condition: { path: "type", value: "sell", memberOf: "type" } },
  },
}
```

If you're using [drupal-jsonapi-params](https://github.com/d34dman/drupal-jsonapi-params), this is a bit easier to create:

```js
import { DrupalJsonApiParams } from "drupal-jsonapi-params"

const params = new DrupalJsonApiParams()
  .addGroup("type", "OR")
  .addFilter("type", "rent", "=", "type")
  .addFilter("type", "sell", "=", "type")
  .getQueryObject()
```

**Comment by KemaneWright** [comment]
I have a similar set up and am using a taxonomy field 'education_level' as a facet and rendering it as checkbox in nextjs. If I select one value my params are
`params = {
  filter: {
    education_level: 27
  }
}`
And the results are filtered properly. If more than one value is selected I map through the array of values and convert it to the following format:
`params = {
  filter: {
    education_level: {
      group: { conjunction: "OR" },
    },
    education_level_27: {
      condition: {
        path: "education_level",
        value: 27,
        memberOf: "education_level",
      },
    },
    education_level_28: {
      condition: {
        path: "education_level",
        value: 28,
        memberOf: "education_level",
      },
    },
  },
};`
Which seems to break the filter. Any ideas why that might not be working?
The SearchAPI field for education_level is indexed as string and the only facet setting I changed was enabling "Transform entity ID to label"

**Comment by KemaneWright** [comment]
Hi not sure if I should open a new issue or ask this here but I have a similar set up and tried implementing your solution but no luck.

I'm using a taxonomy field 'education_level' as a facet and rendering it as checkbox in Nextjs. The SearchAPI field for education_level is indexed as string and the only facet setting I changed was enabling "Transform entity ID to label"

If I select one value my params are

`params = {
  filter: {
    education_level: 27
  }
}`

And the results are filtered properly. If more than one value is selected I map through the array of values and convert it to the following format:

`params = {
  filter: {
    education_level: {
      group: { conjunction: "OR" },
    },
    education_level_27: {
      condition: {
        path: "education_level",
        value: 27,
        memberOf: "education_level",
      },
    },
    education_level_28: {
      condition: {
        path: "education_level",
        value: 28,
        memberOf: "education_level",
      },
    },
  },
};`

Which seems to break the filter. Any ideas why that might not be working?
Thank you!

**Comment by shadcn** [comment]
Hi @KemaneWright I can't seem to reproduce this. I'm testing with a `property_listing` content type which has a taxonomy reference field called `field_location`.

Here's what my filter looks like:

```ts
const properties = await drupal.getSearchIndex("property", {
  params: {
    "fields[node--property_listing]": "title",
    filter: {
      location: {
        group: { conjunction: "OR" },
      },
      location_1: {
        condition: {
          path: "field_location",
          value: 4,
          memberOf: "location",
        },
      },
      location_2: {
        condition: {
          path: "field_location",
          value: 6,
          memberOf: "location",
        },
      },
    },
  },
})
```

I've attached my config for the facet.

![next-drupal test_admin_config_search_facets_location_edit](https://user-images.githubusercontent.com/124599/196102748-dee0b633-97da-4c2e-9e61-f21728716847.png)

**Comment by KemaneWright** [comment]
I see now 'path' has the be the field name from the node not the filter name from facets.
Thank you so much!
