### ISSUE TITLE
Drupal 10 compatibility fixes 

### ISSUE THREAD

**Issue by apathak18** [chapter-three/next-drupal#314]
While scanning the next contributed module using upgrade status we found total 6 issues in which I have resolved 5 and 1 is remaining.
**@internal** tagged in the annotation of class won't allowed to extend.
Below is the attached screenshot of remaining error.

Reference link: https://www.drupal.org/about/core/policies/core-change-policies/bc-policy#internal

**Comment by shadcn** [comment]
Let's move discussion to the PR: https://github.com/chapter-three/next-drupal/pull/313

Closing this. Thank you.
