### ISSUE TITLE
Docs: Unami Demo Local setup suggestion/question

### ISSUE THREAD

**Issue by brentrobbins** [chapter-three/next-drupal#316]
Would it be more consistent to remove the PHP script and just mention to select the Umami installation profile option when initially setting up Drupal This is how it's handled with the Quick Start. Also when I followed those instructions it messed with my ddev configuration. For example, I was unable to run `ddev exec drush cr` after it's setup with the PHP script.

**Comment by shadcn** [comment]
Agreed. I've updated the guide. https://next-drupal.org/guides/umami-demo

<img width="673" alt="soJndgAT" src="https://user-images.githubusercontent.com/124599/195802888-94ac4e3b-61ec-423a-863f-eb8b0fa7f1bf.png">

Thank you
