### ISSUE TITLE
generating pages only for one locale

### ISSUE THREAD

**Issue by violabg** [chapter-three/next-drupal#320]
in the context of [...slug]page, is it possible to statically generate (getStaticPaths) only the content on the default locale, and have other locales generated on demand?

another question, we have a site that is localised only for the Next.js label, I'm using next-translate,  but not on content level, on the Drupal side (don't ask why :)).
In Drupal however, every content fallback to the default locale without having an actual translation, so for each content you ask through locale/path you get the default localisation of the content.
When I build the next site, I'm getting an error (in getStaticPaths) for the missing locales, is there any solution for this? or the only option is to actually translate each content?

**Comment by backlineint** [comment]
Closing as stale. Hoping the answer above helped.
