### ISSUE TITLE
Question about getResourceFromContext and getResourceCollectionFromContext

### ISSUE THREAD

**Issue by spiderneo** [chapter-three/next-drupal#331]
Hi,

I try to use **getResourceFromContext** and **getResourceCollectionFromContext**, are there supposed to do the same thing ? 

For example, i want to retrieve a specific node by **nid**. 
With **getResourceCollectionFromContext**, this is fine, i get an array with the node in it.
```tsx
const node = await drupal.getResourceCollectionFromContext<DrupalNode[]>("node--page", context, {
  params: getParams("node--page").addFilter("nid", "2").getQueryObject(),
})
``` 

but if i do the same thing with **getResourceFromContext**, i got null response
```tsx
const node = await drupal.getResourceFromContext<DrupalNode>("node--page", context, {
  params: getParams("node--page").addFilter("nid", "2").getQueryObject(),
})
```

**Comment by shadcn** [comment]
1. `getResourceFromContext` is for fetching **one resource** and it uses the slug and locale values in context.

```ts
// Let's say context is the following:
const context = {
  params: {
    slug: ['about', 'page-one']
  },
  locale: 'en'
}

// This will return the node--page that has path alias /about/page-one
const page = await getResourceFromContext("node--page", context)
```


2. `getResourceCollectionFromContext` is for fetching **a collection of resources** and it uses the locale value in context.

```ts
// Let's say context is the following:
const context = {
  locale: 'en'
}

// This will return all node--page with locale `en`.
const pages = await getResourceCollectionFromContext("node--page", context)
```

### 💡 Tip
- The `filter` param will not work for `getResourceFromContext` since you're only ever returning one resource.
- Use `filter` when you're fetching a collection of resources

**Comment by spiderneo** [comment]
OK, thank you, this is very clear :) 

So the main thing to search for a particular node is his `path` and not his `nid`.  

If i understand correctly, this should work ? But it returns `null`

```tsx
context = {
  params: {
    slug: ['node','2']
  },
  locale: 'fr'
}
const node = await drupal.getResourceFromContext("node--page", context)
// node return null.
```
Even if i take the current path (`slug: ['welcome']`) in Drupal it doesn't work. 
Not sur what i do wrong.

**Comment by shadcn** [comment]
You can use the node `uuid` in `getResource`:

```ts
const node = await drupal.getResource(
  "node--page",
  "07464e9f-9221-4a4f-b7f2-01389408e6c8"
)
```

See https://next-drupal.org/docs/reference/getresource

**Comment by spiderneo** [comment]
Yes I saw that but sometimes I need to use a `nid` :) i'll do with collection it works fine ;)

I just can't manage to get the node by slug / alias with `getResourceFromContext` which is weird :)

Thank you anyway for your answers and Work on this !  For now i manage to do what i want with this module !

**Comment by shadcn** [comment]
Yeah a `getResourceCollection` with a `filter` should do the trick.

```ts
const pages = await drupal.getResourceCollection("node--page", {
  params: {
    "filter[drupal_internal__nid]": 1,
  },
})

const [page] = pages
```
