### ISSUE TITLE
Authenticated user information

### ISSUE THREAD

**Issue by KemaneWright** [chapter-three/next-drupal#337]
What is the best way to go about getting the currently signed in user's information? Like name, email, and possibly custom fields.

I started at this [issue](https://github.com/chapter-three/next-drupal/issues/222) and built my login flow / authentication exactly like in the example-umami but when trying to get user information from the decoded token user ends up an empty object.
/pages/api/auth/[...nextauth].js
```js
        const decoded = jwt_decode(accessToken.access_token);
        session.user.id = decoded.id;
        session.user.email = decoded.email;
        session.user.name = decoded.name;
```

This also occurs following this [guide](https://next-drupal.org/guides/umami-demo).
Any help would be greatly appreciated. Thank you!

**Comment by KemaneWright** [comment]
Hey @shadcn do you have any info or tips on this? I've been searching everywhere and can't find much with a similar set up. I just started looking into different authentication solutions but wanted to try this one more time.

**Comment by shadcn** [comment]
@KemaneWright Sorry I did not see this issue. You mean `const decoded = jwt_decode(accessToken.access_token);` returns null?

**Comment by shadcn** [comment]
For the Umami example, I'm using `hook_simple_oauth_private_claims_alter` to add the user details to the payload. Here's my implementation:

I have a custom Drupal module `umami_next`:

```php
// in umami_next.module

/**
 * Implements hook_simple_oauth_private_claims_alter().
 */
function umami_next_simple_oauth_private_claims_alter(&$private_claims, AccessTokenEntity $access_token_entity) {
  $user_id = $access_token_entity->getUserIdentifier();
  /** @var \Drupal\user\UserInterface $user */
  $user = User::load($user_id);

  $private_claims = [
    'id' => $user->uuid(),
    'email' => $user->getEmail(),
    'name' => $user->getAccountName(),
  ];
}
```

This will add the `email` and `name` to the token.

We then decode this in Next.js using:

```ts
const decoded = jwt_decode<User>(accessToken.access_token)
session.user.id = decoded.id
session.user.email = decoded.email
session.user.name = decoded.name
```

**Comment by KemaneWright** [comment]
No worries I figured it just got missed in the list of other questions. Awesome this is exactly what I needed! Thank you so much! I don't think there's mention of the custom module in any of the docs/guides

**Comment by amit-mall** [comment]
@KemaneWright did you fixed this?? I'm still not able to fix this, even the hook is not working
