### ISSUE TITLE
umami: error creating new article

### ISSUE THREAD

**Issue by violabg** [chapter-three/next-drupal#339]
when I try to create a new article on the umami demo I get this error, even is they are set on the permission page:

The current user is not permitted to upload a file for this field. The following permissions are required: 'administer media' OR 'create media' OR 'create image media'.

**Comment by shadcn** [comment]
@violabg Everything should work with Drupal's access control with roles and permissions.

Is this not working as expected?

**Comment by violabg** [comment]
> Is this not working as expected?

we had to give permission to authenticated user,
event by using a user with administrator role wasn't enough, for us (using the Drupal umami starter example) the only way was  to give permission to authenticated user, it woks even on anonymous user, but not by roles.
maybe we need to add this module? 
https://www.drupal.org/project/jsonapi_role_access
