### ISSUE TITLE
Possible ways to hide node pages on Drupal side

### ISSUE THREAD

**Issue by fnick851** [chapter-three/next-drupal#341]
If I create a content type on the Drupal side, it's content will have a node page generated by default like http://site/node/6221

I just need to retrieve data from this node. But when visitor visits this node page on Drupal, they will see an unstyled ugly page. Is there a way to hide these node pages? Thanks.

**Comment by twfahey1** [comment]
I’ve personally approached this by keeping the content locked down Drupal side with [node_view_permissions](https://www.drupal.org/project/node_view_permissions) , and only my Next specific configured user role has access to view the specific content types, which generally keeps my /node content unavailable to the public. Curious what others approaches might be.

**Comment by fnick851** [comment]
@twfahey1 I think we could also tell Drupal site search engine to not index the node page & create a robots.txt to tell public search engines to not index the page. Effectively, the page is hidden from the public who do not have the URL. But this is just a good-will/soft approach.

**Comment by shadcn** [comment]
@fnick851 Another option that we've been using is the [Require Login](https://www.drupal.org/project/require_login) module. You can use this to lock down all pages behind a login.

Note: If you're using this module, you will need to whitelist a few paths:

```
/jsonapi
/jsonapi/*
/oauth
/oauth/*
/next/preview-url
/router/*
/subrequests
```
