### ISSUE TITLE
SEO for Next.js-Drupal

### ISSUE THREAD

**Issue by sing78** [chapter-three/next-drupal#347]
Hi,
I would like to ask,if is this possible to use standard drupal SEO modules with Next.js.
For example,the modules Metatag,Pathauto,XML Sitemap,SEO Checklist.
Any help would be great,
Thanks

**Comment by shadcn** [comment]
You can use the metatag module and pull the meta information using JSON:API. Pathauto works with next-drupal as well.

As for XML Sitemap, there are a few ways you can handle this. You can generate the sitemap on Drupal and point your Next.js site to it.

**Comment by sing78** [comment]
@shadcn Thank you very much

**Comment by KemaneWright** [comment]
Hey @shadcn,
Sorry to comment on a closed issue but can you please elaborate a little on how to go about this?
I have the metatag module installed. when I console.log my node in Next.js the field_meta_tags & metatag are `null`
![Screenshot 2023-03-22 at 2 49 12 PM](https://user-images.githubusercontent.com/20935938/227055750-5a8c684e-4020-40eb-8b62-085c25b11f4a.png)
This is from the Drupal edit node page
<img width="588" alt="Screenshot 2023-03-22 at 2 51 49 PM" src="https://user-images.githubusercontent.com/20935938/227056237-1837f625-8a00-42b0-8750-ac960574748d.png">
<img width="586" alt="Screenshot 2023-03-22 at 2 52 51 PM" src="https://user-images.githubusercontent.com/20935938/227056240-2cfc05cd-762f-46c0-b2d7-c026b2dfb044.png">

My Next.js site uses a combination of the Umami & Marketing examples
In `pages/[[...slug]].jsx`
```jsx
const PageRouter = ({ global, node }) => {
  return (
    <Layout meta={{ title: node.title }} global={global} slug={node.slug}>
      <Node node={node} />
    </Layout>
  );
};
```
`layout.jsx`
```jsx
<Meta {...meta} />
```
`meta.jsx`
```jsx
    <Head>
      <link
        rel="canonical"
        href={absoluteURL(router.asPath !== "/" ? router.asPath : "")}
      />
      <title>{`${title} | ${siteConfig.name}`}</title>
      <meta name="description" content={description || siteConfig.slogan} />
      <meta
        property="og:image"
        content={`${siteConfig.baseUrl}/images/meta.jpg`}
      />
      <meta property="og:image:width" content="800" />
      <meta property="og:image:height" content="600" />
    </Head>
    ```
