### ISSUE TITLE
Preview not working for Drupal Commerce Products

### ISSUE THREAD

**Issue by yogglio** [chapter-three/next-drupal#351]
The Iframe preview mode doesn't work for Drupal Commerce Products.
The issue seems to be that Products don't have revisions.
```
Error: 501 Not Implemented
Resource versioning is not yet supported for this resource type.
```

I tried setting isVersionable to false, but it has no effect:
```
 const entity = await drupal.getResourceFromContext<DrupalNode>(
    path,
    context,
    {
      params: getParams(path.jsonapi.resourceName),
      isVersionable: false,
    },
  );
```

**Comment by shadcn** [comment]
I'll take a look at this and report back. Thank you.

**Comment by yogglio** [comment]
When I manually remove the 'resourceVersion' URL parameter in the iframe src, then the iframe loads correctly.

**Comment by shadcn** [comment]
What’s the value of resourceVersion in the query?

**Comment by yogglio** [comment]
It has no value
```
<iframe src="http://localhost:3000/api/preview?slug=/de/gutscheine/gutschein-wert-frei-waehlbar&amp;scope=administrator&amp;timestamp=1667917368&amp;secret=bblSpo6wzMfuAkZl5W3UvXFKlBNYWquOew2hCl0ZWSo&amp;plugin=simple_oauth&amp;locale=de&amp;defaultLocale=de&amp;resourceVersion" allowtransparency="" class="next-site-preview-iframe ready" width="100%" frameborder="0"></iframe>
```

**Comment by shadcn** [comment]
@yogglio I pushed a fix for this in #352 

Can you update to the latest dev release and see if it works?

```
composer require 'drupal/next:1.0.x-dev@dev'
```

(I'll keep this issue open for now)

**Comment by yogglio** [comment]
The dev release works for me.  
I didn't have to set the `isVersionable` option, it worked automatically which is great.
This is already part of the 1.4 release right?

Thank you very much

**Comment by shadcn** [comment]
Yes. Tagged and released today.

**Comment by yogglio** [comment]
We discovered another issue with resourceVersion in the preview.

Steps to reproduce:
- open a Content Type in Preview Mode, which supports revisions
- While in Preview Mode navigate to a Product (which doesn't support revisions)
- Fails to load with error message:
```
Error: 501 Not Implemented
Resource versioning is not yet supported for this resource type.
```

The URL parameters from the json API call, when navigating from node to product page: 
```fields%5Bproduct--voucher%5D=title%2Cstatus%2Cfield_description%2Cfield_image%2Cdefault_variation%2Cvariations%2Cpath%2Cfield_metatag_title%2Cfield_metatag_description%2Cfield_indexiert&include=%0A%20%20%20%20%20%20%20%20%20%20field_image%2C%0A%20%20%20%20%20%20%20%20%20%20field_image.field_media_image%0A%20%20%20%20%20%20%20%20%20%20&resourceVersion=rel%3Alatest-version```

The resourceVersion gets added to the API call, which leads to the error.

**Comment by shadcn** [comment]
Hmm interesting. I tested this when we added the fix for above. Here's a test I added:

https://github.com/chapter-three/next-drupal/blob/846b1463dc0e899d501e8b6b2611e2b6ff617067/modules/next/tests/src/Kernel/Entity/NextSiteTest.php#L65-L70

Did I miss something? Can you open a new issue please? I'll follow up.

**Comment by yogglio** [comment]
Hi @shadcn 
I created a new Issue and added some clarifications there. I think the test is not covering when you first open a node which contains `resourceVersion` and then navigate to a user entity. 
The `resourceVersion` parameter is getting passed on somehow
