### ISSUE TITLE
How to create a media with remote video

### ISSUE THREAD

**Issue by violabg** [chapter-three/next-drupal#357]
I need to create e media of type remote video by passing the youtube url, is it possible?

**Comment by shadcn** [comment]
Yes. 

1. Make sure the role has the **Remote video: Create new media** permission available.
2. Then make the following call:

```ts
const video = await drupal.createResource("media--remote_video", {
  data: {
    attributes: {
      name: "Name of video",
      field_media_oembed_video:
        "https://www.youtube.com/watch?v=sG0rVJT_MT0",
    },
  },
})
```

**Comment by violabg** [comment]
great thanks a lot
