### ISSUE TITLE
Incomplete type definition for translatePathFromContext

### ISSUE THREAD

**Issue by martdavidson** [chapter-three/next-drupal#359]
`translatePathFromContext` says it returns a `Promise<DrupalTranslatedPath>`

If you look at the code for that method, it returns:

```
return await this.translatePath(path, {
      withAuth: this.getAuthFromContextAndOptions(context, options),
    })
```

`translatePath` says it also returns a `Promise<DrupalTranslatedPath>`, but in fact can also return null:

```
if (!response?.ok) {
      // Do not throw errors here.
      // Otherwise next.js will catch error and throw a 500.
      // We want a 404.
      return null
    }
```
In our app code, with `no-unnecessary-condition` enabled, this causes a problem:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/8870176/202210102-41b936f9-4e57-43b5-9027-b79615e03f03.png">

Typescript rightly doesn't think path can be null, because it's being told `translatePathFromContext` will always resolve to a `DrupalTranslatedPath`.

I imagine there are other signatures like this that are also not complete enough, any thoughts?

**Comment by shadcn** [comment]
Hmmm this does look like a bug. Let me look into it.

I wonder if I missed this because I have strict mode turned off.

**Comment by shadcn** [comment]
@martdavidson Can you try one of the releases from https://github.com/chapter-three/next-drupal/pull/377#issuecomment-1339229123 and see if this fixes the type issue?

**Comment by martdavidson** [comment]
Hey @shadcn sorry for the long delay - yes, it now returns `Promise<DrupalTranslatedPath | null>`.

That being said, there is at least one other instance of this same kind of thing: `getResourceFromContext` returns `Promise<T>`, but that method calls `this.getResourceByPath` which can also return `null`:

```
const json = await response.json()

    if (!json?.["resolvedResource#uri{0}"]?.body) {
      if (json?.router?.body) {
        const error = JSON.parse(json.router.body)
        if (error?.message) {
          this.throwError(new Error(error.message))
        }
      }

      return null
    }
    ```
    
I'm not 100% this is the right approach, but I would expect `getResourceFromContext` to return `Promise<T | null>` which would force us to handle the case where the resource can't be fetched.

If I try to do something like: `const resource = await drupal.getResourceFromContext<DrupalNode | null>(...)` that causes a typescript error of:

```
TS2344: Type 'DrupalNode | null' does not satisfy the constraint 'JsonApiResource'.   Type 'null' is not assignable to type 'JsonApiResource'
```

So I can't even tell it I know better. Anyway whether this is expected or should be a new ticket or you want to handle here, totally up to you!

**Comment by shadcn** [comment]
> I would expect getResourceFromContext to return Promise<T | null> which would force us to handle the case where the resource can't be fetched.

Agreed on this. We should update the return type here as well.

@martdavidson Is this a blocker for you right now? If not, I'm planning to turn on strict mode when I get back in January and improve all the type definitions.

**Comment by martdavidson** [comment]
Not a blocker, and also heading into vacation so no worries! Happy holidays!
