### ISSUE TITLE
show unpublished content on next js

### ISSUE THREAD

**Issue by violabg** [chapter-three/next-drupal#360]
We have a page based on a content type, that needs to be visible on next js side, because the user can publish and unpublish it from the front end.
is this possible to activate preview mode on the client by using a specific user even if the we have a static page generated with getStaticProps?

the preview mode in Drupal via iframe is working, I need it on the front end site.

**Comment by shadcn** [comment]
Do you have user authentication on the Next.js site?

**Comment by violabg** [comment]
> Do you have user authentication on the Next.js site?

Yes I do.
I was able to solve it by switching to getServerSideProps and passing the user that create the content, but I wonder if there is a solution using getStaticProps and preview.

**Comment by shadcn** [comment]
I think you could solve this with Preview URLs or using a custom page and getServerSideProps.

1. When you view a page in Drupal, there's a `View` button on top of the iframe. You can click to open the preview on the Next.js site. This URL is generated by a preview url generator. You could use these URLs to share with the front-end team for content review. The preview URLs have an expiration date which you can configure.

2. The other solution that could work is a custom page on your Next.js site which is behind authentication. It can use getServerSideProps to pull in unpublished content.

Something like this:

```ts
// pages/preview.tsx
export default function PreviewPage({ node }) {
  // render preview content type here
}

export async function getServerSideProps(context) {
  // Check for auth.
  if (!notAuth) {
    return {
      redirect: ...
    }
  }

  // Load node from ?path query.
  const path = context.query.path
  const node = await drupal.getResourceFromContext(path, context)

 return {
   props: {
     node,
   }
 }
}
```

Then visiting `https://nextjs-site.com/preview?path=/foo/bar` will allow the logged in user to view `/foo/bar` on Next.js

**Comment by violabg** [comment]
Thank you very much, always very helpfull
