### ISSUE TITLE
Type Error after update from next 13.0.3 to 13.0.5 with NextApiResponse

### ISSUE THREAD

**Issue by taskrider2022** [chapter-three/next-drupal#368]
In the latest version of next (13.0.5) they removed the `unstable_revalidate` function from the `NextApiResponse` interface.

I became so now a compile error if I use the preview mode of next-drupal, because it has next in version 12 as dependency.
The following code create this error, I think that `drupal.preview` check this type with the dependency.

```
import { drupal } from 'lib/drupal';
import type { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse
) {
  return drupal.preview(request, response);
}
```

```
Argument of type 'import("node_modules/next/dist/shared/lib/utils").NextApiResponse<any>' is not assignable to parameter of type 'import("node_modules/next-drupal/node_modules/next/dist/shared/lib/utils").NextApiResponse<any>'.
  Property 'unstable_revalidate' is missing in type 'ServerResponse<IncomingMessage> & { send: Send<any>; json: Send<any>; status: (statusCode: number) => NextApiResponse<any>; redirect(url: string): NextApiResponse<...>; redirect(status: number, url: string): NextApiResponse<...>; setPreviewData: (data: string | object, options?: { ...; }) => NextApiResponse<...>; cl...' but required in type '{ send: Send<any>; json: Send<any>; status: (statusCode: number) => NextApiResponse<any>; redirect(url: string): NextApiResponse<any>; redirect(status: number, url: string): NextApiResponse<...>; setPreviewData: (data: string | object, options?: { ...; }) => NextApiResponse<...>; clearPreviewData: (options?: { ...; ...'.ts(2345)
utils.d.ts(225, 5): 'unstable_revalidate' is declared here.
```

**Comment by shadcn** [comment]
I'm working on adding support for Next.js 13 this week. I'll update here when done. Thank you.

**Comment by martdavidson** [comment]
Hey @shadcn - that also involves moving this project to react 18, yeah? Excited to hear this is being worked on, I'm running into a few issues that Next 13 has solutions for.

Thanks in advance!

**Comment by shadcn** [comment]
@taskrider2022 @martdavidson I've started working on it. See https://github.com/chapter-three/next-drupal/pull/387

Would you like to help me test it? See the **How to test** section in the PR.

Thank you

**Comment by martdavidson** [comment]
I would love to! I'll bring it into our project and see what happens.

**Comment by martdavidson** [comment]
I'm working off that branch and updated things according to the next 13 migration guide. In my rigorous "click around a bunch" testing, it seems to work! No typescript or eslint errors and no console warnings.

Anything in particular I should watch out for beyond obvious issues? We'll likely start using this immediately since our deadline is a few months out and we definitely need some Next 13 features.

Thanks so much.

**Comment by shadcn** [comment]
@martdavidson Thanks for your helping testing this. I've merged the PR. This will be in the `1.6.0` release.
