### ISSUE TITLE
Preview error when Navigating from Versionable Entity to Non-Versionable Entity

### ISSUE THREAD

**Issue by yogglio** [chapter-three/next-drupal#371]
This is a follow up of #351.

Steps to reproduce:

- Open a Entity in Preview Mode, which supports revisions 
- While in Preview Mode navigate to an Entity which doesn't support revisions
- Fails to load with error message:
```
Error: 501 Not Implemented
Resource versioning is not yet supported for this resource type.
```
The URL parameters from the json API call, when navigating from node to product page:
`fields%5Bproduct--voucher%5D=title%2Cstatus%2Cfield_description%2Cfield_image%2Cdefault_variation%2Cvariations%2Cpath%2Cfield_metatag_title%2Cfield_metatag_description%2Cfield_indexiert&include=%0A%20%20%20%20%20%20%20%20%20%20field_image%2C%0A%20%20%20%20%20%20%20%20%20%20field_image.field_media_image%0A%20%20%20%20%20%20%20%20%20%20&resourceVersion=rel%3Alatest-version`

The resourceVersion gets added to the API call, which leads to the error.

The Error only occurs, when you **preview a revisonable Entity and then navigate to a non-revisionable Entity** while in Preview Mode. 
**Directly Previewing a non-revisionable Entity works fine.** (opening it from the Drupal backend)

I guess `resourceVersion` parameter gets somehow saved and passed on in the following requests.

**Comment by shadcn** [comment]
Thanks for the clear steps. I've been able to reproduce this. I can confirm the bug. 

This is what's happening:

1. When you visit the preview of a versionable entity, we're setting the `resourceVersion` in the previewData:

```ts
previewData: {
  resourceVersion: 'rel:latest-version',      
}
```

2. When you navigate to another entity, say a non-versionable one, the `resourceVersion` is still around in the `previewData`. The following code in `DrupalClient.getResourceFromContext` is picking up the `resourceVersion`:

```ts
const _options = {
  deserialize: options.deserialize,
  isVersionable: options.isVersionable,
  locale: context.locale,
  defaultLocale: context.defaultLocale,
  withAuth: options?.withAuth,
  params: {
    resourceVersion: previewData?.resourceVersion, // <------ 👈
    ...options?.params,
  },
}
```

We need a check here to ensure the request resource type is versionable before setting the `resourceVersion`. Something like:

```ts
if (options.isVersionable) {
  options.params.resourceVersion = previewData?.resourceVersion
}
```

I'm going to look into this and push a fix.

**Comment by shadcn** [comment]
@yogglio I just tagged `next-drupal@1.5.1` with the fix. Thanks for your help on this issue. Appreciate it.

**Comment by yogglio** [comment]
@shadcn Thank you!
