### ISSUE TITLE
Only one user can be logged in at a time

### ISSUE THREAD

**Issue by KemaneWright** [chapter-three/next-drupal#376]
Hi @shadcn,

I'm curious if you've ran into this bug/situation before.
User1 logs in to nextjs site, everything works fine, content is filtered to that user. 
User2 logs in to nextjs in a different browser and now User1 is logged in as User2.

I just set up a new test site following the [umami guide](https://next-drupal.org/guides/umami-demo) to see if maybe my site was set up incorrectly but I experience the issue here as well when testing with an incognito browser.

Thank you in advance!

**Comment by shadcn** [comment]
@KemaneWright Yep. The implementation of the cache is incorrect. We ended up with a shared cache. I'll push a fix for it.

**Comment by shadcn** [comment]
@KemaneWright I pushed a fix for it. Can you update your local repo and try again?

**Comment by KemaneWright** [comment]
You sir are a legend! Thank you so much!
