### ISSUE TITLE
Missing @group annotation in Drupal\Tests\next\Kernel\Event\EntityRevalidatedEventTest

### ISSUE THREAD

**Issue by jrockowitz** [chapter-three/next-drupal#400]
The Schema.org Blueprints module's tests are [failing on Drupal.org](https://www.drupal.org/pift-ci-job/2540222
) with the below error.

> Drupal\Core\Test\Exception\MissingGroupException: Missing @group annotation in Drupal\Tests\next\Kernel\Event\EntityRevalidatedEventTest in /var/www/html/core/lib/Drupal/Core/Test/TestDiscovery.php:362

I think the solution is to add @group next to the below tests
\Drupal\Tests\next\Kernel\Event\EntityRevalidatedEventTest
\Drupal\Tests\next\Kernel\Event\EntityActionEventTest

**Comment by shadcn** [comment]
@jrockowitz I've created a PR. Thank you.

Do you require a patch release or are the Schema.org tests based on the dev snapshot?

**Comment by shadcn** [comment]
@jrockowitz Fixed in https://www.drupal.org/project/next/releases/1.6.1

**Comment by jrockowitz** [comment]
@shadcn Thanks.
