### ISSUE TITLE
Question: Preview mode for editors

### ISSUE THREAD

**Issue by KemaneWright** [chapter-three/next-drupal#401]
Hi @shadcn,

Do you know what might be the issue here?

On the Drupal side of the site I want the "Editor" role to be able to approve/publish job postings but when I try to preview them I get a 500 error response from JSON API "The current user is not allowed to GET the selected resource."
The "Editor" role has what I believe to be all the right permissions:
Bypass content access control, View any unpublished content, Administer users, and some more.

Each Job Posting (node) references an Author (user), Employer (node), and some taxonomies.

Logged in as a Drupal Admin everything works fine. Maybe i'm missing a required permission for the "Editor"?
I also tried adding the "Editor" role to the scope of the Oauth Client, no luck.

<img width="360" alt="drupal-admin" src="https://user-images.githubusercontent.com/20935938/208029171-efa79837-ce53-471d-955d-cc6d9a6d8843.png">
<img width="360" alt="drupal-editor" src="https://user-images.githubusercontent.com/20935938/208029183-bb0c378e-0286-42fb-adf1-13444eb50636.png">

Thank you!

**Comment by shadcn** [comment]
Hi. In the Drupal log where it says "The current user is not allowed to GET the selected resource.", can you check which user/role is this logged under?
