### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by simon-olsen** [chapter-three/next-drupal#41]
`warning " > next-drupal@0.15.0" has incorrect peer dependency "next@^10.0.0".`

I've noticed that the above turns up in my Terminal. Everything seems to run fine, but do I need to adjust anything in my project?

My Next version is the following:

`"next": "^11.1.2",`

**Comment by shadcn** [comment]
@simon-olsen Is this still an issue?

**Comment by simon-olsen** [comment]
All good to close this issue. My recent versions are

```
    "next": "^12.0.7",
    "next-drupal": "^1.1.1",
```

and there hasn't bee this warning since.
