### ISSUE TITLE
Patch fails to apply on drupal/decoupled_router

### ISSUE THREAD

**Issue by dottodot** [chapter-three/next-drupal#410]
I've recently noticed that I'm getting an error when applying one of the recommended patches

```
    https://www.drupal.org/files/issues/2021-05-05/3111456-34.patch (Unable to resolve path on node in other language than default)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2021-05-05/3111456-34.patch
```

I've not noticed any issues though.

**Comment by shadcn** [comment]
I've updated the patch for decoupled_router and also added a note when not using multilingual features.

Thanks for the heads up.

Marking this as completed.
