### ISSUE TITLE
Show content only in Preview mode

### ISSUE THREAD

**Issue by iamfredrik** [chapter-three/next-drupal#411]
I have a special use case where the content on the Next.js site should only be visible from within the Preview mode in Drupal. The Next.js site does not have any authentication. I was able to fake it the following way when clicking the View button, but it does not work in the iframe. Any ideas?

```
const { isPreview } = useRouter();
if (!isPreview) return null;
```

**Comment by iamfredrik** [comment]
Same problem with context.preview. It doesn't work in the iframe.

**Comment by iamfredrik** [comment]
It's only in development that context.preview does not work, so I'm closing this as it works in production.

**Comment by shadcn** [comment]
@iamfredrik See https://next-drupal.org/docs/configuration#forceiframesamesitecookie

**Comment by iamfredrik** [comment]
> @iamfredrik See https://next-drupal.org/docs/configuration#forceiframesamesitecookie

Thanks, but it did not work for me. It broke the View link as well which works without it.
