### ISSUE TITLE
Next.js JSON:API helper module breaks `fields` parameter

### ISSUE THREAD

**Issue by RaspberryBlack** [chapter-three/next-drupal#412]
If the `next_jsonapi` module is enabled, I can't request sparse fieldsets, eg `[localhost]/jsonapi/node/article?fields[node--article]=title`. If the module is disabled, it works as expected.

The error I get is a Bad Request (400) "Input value \"fields\" contains a non-scalar value."

To reproduce just follow the JSON:API quickstart guide on https://next-drupal.org/

drupal/core-recommended v10.0.1
drupal/next v1.6.1

**Comment by shadcn** [comment]
@RaspberryBlack I pushed a fix for this in #404 

Can you try the dev release and see if it works?

```sh
composer require 'drupal/next:1.0.x-dev@dev'
```

**Comment by RaspberryBlack** [comment]
@shadcn thanks a lot for the quick fix, this is working for me now :)
