### ISSUE TITLE
Duplicate Meta-Tags when overwriting with Next.JS <Head> component

### ISSUE THREAD

**Issue by PierreRe** [chapter-three/next-drupal#416]
Next.JS` <Head> component is able to extend and replace meta information predefined in a higher component with information defined in child-components. With the current implementation, rewriting tags may lead to duplicate tags in the rendered HTML.

Adding keys to the meta-, title- and link-tags prevents duplicate tag-rendering when overwriting information already set by a higher component.

I do have a best-practice example ready for a PullRequest

**Comment by shadcn** [comment]
@PierreRe This is interesting. Is there a link where I can read more about how this works please? Thank you.

**Comment by PierreRe** [comment]
@shadcn https://nextjs.org/docs/api-reference/next/head
> To avoid duplicate tags in your head you can use the key property, which will make sure the tag is only rendered once...
