### ISSUE TITLE
Webform - get fields type and label; then handle submission

### ISSUE THREAD

**Issue by HasinaNjaratin** [chapter-three/next-drupal#424]
Hello, 

How to retrieve all the {type, label} fields of an webform?
Then, I want to manage the submission?

Thx

**Comment by p0zi** [comment]
There is Rest module for interacting with Drupal Webform:
https://www.drupal.org/project/webform_rest

For me completely fine works embeeding Webforms via iframe, thanks to this i can manage/change easily webform in Drupal. This techniquie requires some JS script to be running on Drupal as well to make iframe adjust properly to wrapper size. Consider also enabling Jquery Validation plugin for Webform to make client + server side validation.

Enable module in Drupal
![Screenshot from 2023-02-08 14-54-30](https://user-images.githubusercontent.com/22954481/217549567-7e935544-fbe9-4012-908c-b509d703dedd.png)

Configure certain Webform to be shared:
https://www.youtube.com/watch?v=oMgOprfJTWA

React Component for embeeding Webforms within iframe:
![Screenshot from 2023-02-08 14-52-55](https://user-images.githubusercontent.com/22954481/217549923-b1f5658c-3958-4e29-a77e-69396ffc03b4.png)

**Comment by JohnAlbin** [comment]
Please open a new issue if this is still an unanswered question for you. Thanks!
