### ISSUE TITLE
404 after language switch

### ISSUE THREAD

**Issue by Kerchik** [chapter-three/next-drupal#428]
For example I have a node, that originally was created with in English, with URL alias /lorem . I translated this page to FR language, and this treanslated page has URL alias: /lorem-fr.

I have my language selectors configured, just as in Umami demo:
```
<Link key={index} href={asPath} locale={language} passHref>
              <a className="text-black-1 text-secondary-color uppercase text-sm font-medium">
                {language}
              </a>
  </Link>
```

Everything works fine, if I try to change language to FR, when I am at /lorem page. But when I stay at /lorem-fr page and I am trying to change language to EN, I get 404. I assume, this happends, because after lagnuage change my URL looks like this: /en/lorem-fr and obvously it cannot translatePathFromContext() and return null. Is there any way I can fix it? Perhaps Ishould use differennt language switcher logic?

**Comment by spiderneo** [comment]
Hi, the Unami demo is different of what you want to do i think. 

Url are the same in ES or EN, so it's ok for the engine to just change the local. 
But a real drupal don't work like this and you will have a different URL for EN and FR for example. 

For me you have to get the resource from [...slug] which have the `content_translations` attribute. 

```
content_translations: [
    { label: 'page FR ', path: '/fr/lorem', langcode: 'fr' },
    { label: 'page EN', path: '/en/lorem-version-en', langcode: 'en' }
  ],
```

All node translation for a node are here, so you can then do a simple mapping of locale between this result and the node

**Comment by Kerchik** [comment]
Yeah, I already implemented it by using requests to Drupal, and getting correct aliases using getAliasByPath() function, so I guess this problem is already solved.
