### ISSUE TITLE
JSON:API Includes compatible ?

### ISSUE THREAD

**Issue by GeneralBouLi** [chapter-three/next-drupal#432]
Hello,

We start to develop a nex site with next-drupal and I want to know if we can use  [JSON:API Includes](https://www.drupal.org/project/jsonapi_include) to reduce the verbose API return ?

Thanks.

**Comment by shadcn** [comment]
Yes. You can use JSON:API Includes for collections.

**Comment by GeneralBouLi** [comment]
Thanks @shadcn for this quick reply.
Have a good day.
