### ISSUE TITLE
Question: Possible way to disable revalidation for specific operations?

### ISSUE THREAD

**Issue by yobottehg** [chapter-three/next-drupal#443]
First of all thanks for this very good distribution. It works amazingly well!

I ran into a small problem with my drupal site which i wanted to quickly ask if this is "only me" or a general thing we could do.

I install Drupal from scratch locally using exported config and default content. Everything works but when installing the custom module with the default content the revalidation are triggered for the created content.

Is there a way to disable revalidation for this purpose? The revalidations will throw red errors in the console if the local client is not running and therefore the url is not reachable.

**Comment by shadcn** [comment]
Hmm, I guess disabling revalidation for each entity types and then re-enable after import could work but let me see if there's an easier way.

**Comment by shadcn** [comment]
OK I think I found a way. If you're using the `Path` plugin for revalidation, you can replace the plugin with one that does not actually do the revaldation.

## Step 1: Implement hook_next_revalidator_info_alter()

```php
// modules/custom/CUSTOM_MODULE/CUSTOM_MODULE.module
/**
 * Implements hook_next_revalidator_info_alter().
 */
function CUSTOM_MODULE_next_revalidator_info_alter(array &$info) {
  $info['path']['class'] = \Drupal\custom_module\Plugin\Next\Revalidator\Path::class;
}
```

## Step 2: Create a custom `Revalidator` plugin:

The plugins should be placed at `modules/custom/custom_module/src/Plugin/Next/Revalidator/Path.php`.

```php
<?php

namespace Drupal\example_auth\Plugin\Next\Revalidator;

use Drupal\next\Event\EntityActionEvent;
use Drupal\next\Plugin\Next\Revalidator\Path as NextPath;
use Drupal\next\Plugin\RevalidatorInterface;

/**
 * Provides a null revalidator.
 *
 * @Revalidator(
 *  id = "custom_path",
 *  label = "Path (custom)",
 *  description = "Provides a null revalidator"
 * )
 */
class Path extends NextPath implements RevalidatorInterface {

  /**
   * {@inheritdoc}
   */
  public function revalidate(EntityActionEvent $event): bool {
    return false; // <------ 👈 No revalidation
  }

}
```

That's it. This will replace the default `Path` revalidator. You can now safely import content without triggering revalidation.

**Comment by yobottehg** [comment]
Thanks, i was also thinking about a decorator but thought i'll ask first if there is an out-of-the-box solution :)

For completeness sake, here the revalidator that decorates the normal Path revalidator and early returns if it is called in that exact use case `drush pm:install your_default_content`

```PHP
<?php

namespace Drupal\default_content_path_revalidator\Plugin\Next\Revalidator;

use Drush\Drush;
use Drupal\next\Event\EntityActionEvent;
use Drupal\next\Plugin\Next\Revalidator\Path as NextPath;
use Drupal\next\Plugin\RevalidatorInterface;

/**
 * Provides a revalidator that is not triggered by default_content.
 *
 * @Revalidator(
 *  id = "default_content_path_revalidator",
 *  label = "Path (Custom)",
 *  description = "Revalidator that is not triggered by default_content"
 * )
 */
class Path extends NextPath implements RevalidatorInterface {

  public const MODULE_INSTALL_TO_IGNORE = 'your_default_content';

  /**
   * {@inheritdoc}
   */
  public function revalidate(EntityActionEvent $event): bool {
    if (PHP_SAPI !== 'cli') {
      return parent::revalidate($event);
    }

    $commandName = Drush::input()->getFirstArgument();

    if ($commandName === NULL) {
      return parent::revalidate($event);
    }

    $fullCommandName = Drush::getApplication()->find($commandName)->getName();

    if ($fullCommandName !== 'pm:install') {
      return parent::revalidate($event);
    }

    $modulesToEnable = Drush::input()->getArgument('modules');

    if (in_array(self::MODULE_INSTALL_TO_IGNORE, $modulesToEnable)) {
      return TRUE;
    }

    return parent::revalidate($event);
  }

}
```
