### ISSUE TITLE
Kernel::TERMINATE over drupal_register_shutdown_function

### ISSUE THREAD

**Issue by mglaman** [chapter-three/next-drupal#444]
`drupal_register_shutdown_function`calls to `register_shutdown_function` which will run after the HTTP kernel has been terminated and could cause interaction with a partially disassembled service container.

There is a paradigm for this in the terminate process of the request. This is documented here: https://symfony.com/doc/current/components/http_kernel.html#8-the-kernel-terminate-event

**Comment by shadcn** [comment]
Thanks for the link Matt. I'll check it out.

**Comment by mglaman** [comment]
This is preventing the ability to write tests. I notice that https://github.com/chapter-three/next-drupal/blob/main/modules/next/tests/src/Kernel/Event/EntityActionEventTest.php is explicitly invoking `_drupal_shutdown_function` but tests which do not fail

**Comment by JohnAlbin** [comment]
@mglaman Quick question.

What's the difference between the approach suggested by the Symphony docs and the `drupal_register_shutdown_function` deprecation notice that suggests using `Drupal\Core\Shutdown\ShutdownHandler`?

https://www.drupal.org/node/3053808

**Comment by mglaman** [comment]
It's mostly about _when_ things execute.

The shutdown process happens after _all_ code has been executed and PHP is "shutting down". Let's take `index.php`

```php
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();

$kernel->terminate($request, $response);
```

The `terminate` is an explicitly part of the HTTP kernel life cycle for things to do once a response has been sent to the browser. Drupal built an API around this with `DestructableInterface`. 

The shutdown functions happen _after_ the `$kernel->terminate()` call has finished and PHP has finished executing the code in `index.php`. Or, in terms of the test failures seen in #547, when PHPUnit has finished executing the tests. It just happens to work. 

The state of Drupal is in flux. The service container and other parts of the system cannot be guaranteed in the shutdown. They could-ish in Drupal 7 because we only had the shutdown handler. Now we have the termination of the HTTP kernel.
