### ISSUE TITLE
OAUTH User Authentication Token lacks user data

### ISSUE THREAD

**Issue by MokDevelopment** [chapter-three/next-drupal#449]
I managed to setup an OAuth user authentication via NextAuth. I can login and tokens are created. YAY :) 

However the returned accessToken does not provide the current user information. 
I am sure it is a permission thing in Drupal but I could be wrong. 

![image](https://user-images.githubusercontent.com/80107399/220455487-c5a398e6-098f-4bca-b154-6ded86b160eb.png)

![image](https://user-images.githubusercontent.com/80107399/220455602-0065200d-e481-48a5-bec3-cebaef7304ae.png)

For testing purposes I provided permission for "view user information" and OAuth Token informations to all roles - but that does not seem to be enough. 

How do I return at least the user id?
The uuid would be even better ... but I can do another request.  

<img width="661" alt="image" src="https://user-images.githubusercontent.com/80107399/220456239-b315e813-9c00-43ab-93d6-f4863a0e2ca8.png">

_______________________________________
_______________________________________
_______________________________________

I am not sure. It might be also a jwt_decode() issue as the token itself seems to deliver at least the user id before it is decoded into an object (sub === user_id 8).

![image](https://user-images.githubusercontent.com/80107399/220459945-515d155d-1c0e-436e-bd68-1dffbb7c9749.png)

![image](https://user-images.githubusercontent.com/80107399/220459419-baf68d8c-420d-498e-b40b-2076562cd4f4.png)

I am slightly irritated  :) Any ideas?

Thanks again

**Comment by shadcn** [comment]
@MokDevelopment Did you figure it out? What was the issue?

**Comment by MokDevelopment** [comment]
Yes, thanks for checking :)
I found your hook in the module :) after some digging.

While searching for a solution of the problem I also upgraded OAuth to the newest release 6.0@beta . Its important to install an extension module called:
simple_oauth_password_grant. Without it a Drupal user can not be authorized due to the removal of the password grant_type feature. The module brings it back. 
 
 I wonder what is now (without the module) an expected workflow? Making each time double requests? 

However all is fine now... almost... Now I have issues with the preview ```
"log.ts:18 error - Error: The requested scope is invalid, unknown, or malformed
    at client.ts:1437:13"
```

I create a new support issue.

**Comment by MokDevelopment** [comment]
Never mind... :) I updated the previewer in NextJs with the SessionAuth and we are back to normal :)

```
// import { drupal } from "lib/next/drupalClient"
import { NextApiRequest, NextApiResponse } from "next"
import { getSession } from "next-auth/react"
import { DrupalClient } from "next-drupal"

const session = getSession()

export const drupal = new DrupalClient(
  process.env.NEXT_PUBLIC_DRUPAL_BASE_URL,
  {
    previewSecret: process.env.DRUPAL_PREVIEW_SECRET,
    auth: session['accessToken'],
  }
)
export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse
) {
  return await drupal.preview(request, response)
}
```
I hope this is the expected way to do this?
