### ISSUE TITLE
Error with JWT and using 'withAuth' in drupal.getResourceCollection() since upgrade

### ISSUE THREAD

**Issue by championlife** [chapter-three/next-drupal#450]
I'm having auth issues since upgrading to

* Simple OAuth -  5.2.3
* next-drupal  - 1.6

Making a call such as this used to work: 
`
const articles = await drupal.getResourceCollection("node--article", {
    withAuth: session.accessToken,
  });
`  

Now it produces a 500 error and Drupal logs show
_Lcobucci\JWT\Signer\InvalidKeyProvided: Key cannot be empty in Lcobucci\JWT\Signer\InvalidKeyProvided::cannotBeEmpty() (line 34 of /app/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php)._

The accessToken is valid when I console.log(session.accessToken). I'm wondering if it is related to [](https://www.drupal.org/project/simple_oauth/issues/3339684 )or if anyone else has experienced this?

**Comment by championlife** [comment]
Just leaving a comment that when I use Postman to make a request with "Authorization: Bearer [token]' it fails with the above error too. @shadcn are you able to post new nodes using this version of simple_oauth?

**Comment by shadcn** [comment]
@championlife I actually just set up a new site yesterday. I couldn't reproduce this error. Anything else in your composer.json we could take a look at?

**Comment by championlife** [comment]
I'll post info from my  composer.json when I'm back in the office
(Australia time). Thanks. Are you using the same version of simple_oauth?
Or explicitly declaring any overrides of dependencies for jwt etc?

I'm on Pantheon, and locally use Docker/lando. Don't know if it's an issue
with my keys stored in simple_oauth but it was fine in the past. It's
probably not anything to do with Next.js since attempting a test POST
request with Postman yields the same error. Driving me a bit up the wall
though!

**Comment by shadcn** [comment]
Yes using the same versions.

**Comment by championlife** [comment]
Ok. What about the settings you can  toggle in simple oauth for 'implicit
grant' or confidential, 3rd party etc? I'm on PHP 8.1 too, can't remember
if I mentioned it.

**Comment by championlife** [comment]
Here's my current composer.json
I had added in a specific version of "lcobucci/jwt" to see if that would fix it but no dice.

```
"require": {
        "cweagans/composer-patches": "^1.7",
        "drupal/consumers": "^1.15",
        "drupal/entity": "^1.4",
        "drupal/gin": "^3.0@beta",
        "drupal/gin_gutenberg": "^1.0",
        "drupal/gin_login": "^1.2",
        "drupal/jsonapi_extras": "^3.20",
        "drupal/jsonapi_menu_items": "^1.2",
        "drupal/jsonapi_node_preview_tab": "^1.0@beta",
        "drupal/jsonapi_views": "^1.0",
        "drupal/jwt": "^1.0",
        "drupal/next": "^1.3",
        "drupal/purge": "^3.2",
        "drupal/raven": "^3.2",
        "drupal/restui": "^1.20",
        "drupal/simple_oauth": "^5.2",
        "drupal/upgrade_status": "^3.18",
        "drush/drush": "^10",
        "lcobucci/jwt": "4.1.5",
        "league/oauth2-server": "^8.4",
        "pantheon-upstreams/upstream-configuration": "*"
    },


```

**Comment by championlife** [comment]
Okay this is a "me" problem. I spun up a new local Drupal 9 install and it worked fine, once I configured lando to use PHP 8.1 in lando.yml

What I think was the problem was I _thought_ I updated the `drupal/next` version - and I see now that from above it was still only v1.3 not v1.6. I removed the custom overrides to `lcobucci/jwt` and `league/oauth2-server`

`lando rebuild` seems to have done the trick after re-running composer
