### ISSUE TITLE
Question: NextAuth & DrupalClient Setup for Members

### ISSUE THREAD

**Issue by MokDevelopment** [chapter-three/next-drupal#455]
Hi there.

Please help me to understand the dependencies of consumer scopes, Drupal roles and the default nextJs role / consumer

I  need to setup a small public shop with a private member area, which allows members to create/edit/delete entities in the frontend. 

Apart from the member section all the other contents should be delivered by the nextJs role / default consumer via bearer.

### **I understand, that when using sessions via nextAuth you are able to inject the session token into a drupal client/ or fetch command.** 

> 
> 1. So a fetch call does act then in the role scope of the current user?
> 2. Or is the user role respected that was chosen in the consumer scope?
> 3. Could I even have dynamic access rules depending on a user field / flag? 
> 4. The Next JS Frontend should not run via sessions (we want bearer to create general content, correct?)
> 5. Does it make sense to create then a separate drupalClient to just deal with member sessions all together?

>6. When doing so would  that ensure, that you follow the user role permission / access rules, that are defined for the currently logged in user / user role. - Is that correct? So would a fetch for an entity of another user return an access error or null results - at least if the permission set of the user was setup like that within Drupal?

Also I must say, that I got issues to understand which role the OAUTH consumer plays in this scenario. Is it wise to create a specific consumer for each user role?  In my case they would be:

> - "Buyer" (can edit his/her message and bookmark entities ) 
> - "Seller" (can edit his/her message and product entities  )
> - "NextJS Default" (general root access via api endpoints and public content deliverer  )

Maybe I should just use the session for authentication to allow api calls. In this case the default consumer takes action.  - Instead of dealing with the Drupal permission logic. In this case Node would deal with the access logic following static rules, that are defined within the api itself. 

I hope this does not sound totally stupid? Sorry for all these questions.

Thanks again for clarifying and having the ability to deal with these headless issues in Drupal in general :)

**Comment by MokDevelopment** [comment]
closed... project / team moved away from Drupal to node.js @Strapi

**Comment by p0zi** [comment]
Have a look at:
https://www.youtube.com/watch?v=rTcC0maPLSA&list=PLZOQ_ZMpYrZtqy5-o7KoDhM3n6M0duBjX
