### ISSUE TITLE
Missing content_translations

### ISSUE THREAD

**Issue by mikegikas** [chapter-three/next-drupal#459]
Hello,

I have created a new content type and configured the URL alias, but when I go to the page, I can't see the content translations at the node.

When I click on another content type, the content translations exist at the node. Can anyone tell me what I'm missing?

**Comment by p0zi** [comment]
Hello,
1) Try "drush cr"
2) Try installing patch from https://www.drupal.org/project/drupal/issues/3274419
3) If this is taxonomy term, check this out: https://github.com/chapter-three/next-drupal/pull/425

**Comment by mikegikas** [comment]
Thank you p0zi!

The problem was resolved by installing the patch.
By the way, I am the author of the third option. :P
