### ISSUE TITLE
getStaticPathsFromContext() Returns an Empty Array at Build Time

### ISSUE THREAD

**Issue by ui-jb** [chapter-three/next-drupal#464]
Hello,

For a multilingual site that I'm working on, I have a dynamic route at `pages/[...slug].tsx`.
I want to run getStaticPaths with the `fallback` property set to `false` so that only the pages present at build time are created. The code for my `getStaticPaths` function looks like this:
```
export async function getStaticPaths(context: any) {
  const paths = await drupal.getStaticPathsFromContext(
    ["node--page"],
    context,
    }
  );
  return {
    paths,
    fallback: false,
  };
}
```

The problem is that getStaticPathsFromContext always returns an empty array at build time. This means that the pages pulled in from Drupal aren't being built.

The catch is that if I set `fallback` to `'blocking'`, we can access those pages.

**Comment by ui-jb** [comment]
I'm closing this issue as it's the result of an issue in Drupal. We found that the `path` attribute was not being returned in the JSON API response for our pages.

**Comment by iamfredrik** [comment]
Did you figure out what the problem was? I'm having the same problem after updating Drupal.

**Comment by MartinDavi** [comment]
Yes @ui-jb please update us when you can with the Drupal issue link if you have it, I'm having the same issue.

**Comment by MartinDavi** [comment]
Fantastic, I suspected it was that second ticket! Thanks so much for confirming - we'll be applying that patch today.

**Comment by iamfredrik** [comment]
> @iamfredrik @MartinDavi I'm the frontend dev, but the Drupal dev who resolved the issue explained it like this:
> 
> > It was an issue generated by the Multilingual system, which generates some overrides to base fields. The `path` is one of those overridden fields (a new setting is attached to the field to indicate whether the path is translatable). Once a field is overridden, it is under the control of the class `BaseFieldOverride` and that class was inheriting its `isInternal()` method from `FieldConfigBase`, _so that any computed field becomes internal though initially the field might be non-internal_. And, fields marked as internal are not shown in the API.
> 
> He also provided these two drupal issues for more context: https://www.drupal.org/project/jsonapi/issues/3012019 https://www.drupal.org/project/drupal/issues/3274419

I have already tried the patch and the proposed solutions, but alas, none of them worked for me.

**Comment by MartinDavi** [comment]
I had to add `path` to the requested fields from the json:api to get the path to show up, which was new behaviour I think:

```
  const params = new DrupalJsonApiParams();

  RESOURCE_TYPES.map((resourceType) =>
    params.addFields(resourceType, ['path'])
  );
```

Something like that assuming you're using `DrupalJsonApiParams` - I didn't need to do this prior.
