### ISSUE TITLE
fetch requests fail sometimes

### ISSUE THREAD

**Issue by trickreich** [chapter-three/next-drupal#47]
![image](https://user-images.githubusercontent.com/16644200/142226130-97d48027-5177-4f27-a016-6555b4522f70.png)

![image](https://user-images.githubusercontent.com/16644200/142226259-11113a71-2feb-46b0-b1f4-76a6b6ec2409.png)

Sometimes our fetch requests fail and I have no clue why. It's also not the same request which is failing.
Maybe someone could give me a hint where I could dig deeper.

**Comment by shadcn** [comment]
@trickreich hmm this might be a hard one to debug. How big is the site? What does the build time look like?

**Comment by trickreich** [comment]
@shadcn this is just a one pager therefore just one page in drupal.. sadly there's no option to debug `node-fetch` I think

**Comment by scotthooker** [comment]
Are you on a Mac m1? / Which version of node you using locally?

It seems to work for me now when using nvm 14

**Comment by backlineint** [comment]
Closing as stale due to age. But if this (or something like it) is still relevant, let us know.
