### ISSUE TITLE
Accessing Drupal included

### ISSUE THREAD

**Issue by jdrew-byte** [chapter-three/next-drupal#487]
I'm not sure if I'm using the correct method, but when I make a call using the getResourceFromContext the body.data is returned. The issue is drupal is returning the "included" data outside of the data object in the response. Do I just need to create my own fetch to access that data, or should the included in inside the data object in the response? The reason for this is to access paragraphs and its attributes. 

<img width="957" alt="Screen Shot 2023-04-25 at 1 57 17 PM" src="https://user-images.githubusercontent.com/106710719/234403588-ebe3e40c-5cb9-433e-8217-e4c8fd169875.png">
<img width="1046" alt="Screen Shot 2023-04-25 at 1 58 12 PM" src="https://user-images.githubusercontent.com/106710719/234403593-02def45f-4562-4fb4-bbc7-b3521fa32221.png">

**Comment by p0zi** [comment]
Hello, you must understand idea behind serialization and deserializartion, please follow library that is used by next-drupal:
https://github.com/olosegres/jsona

**Comment by shadcn** [comment]
@jdrew-byte Visiting /jsonapi on your Drupal site will show `included` but when you fetch using one of the methods on the client: `getResource`, `getResourceCollection` or `getResourceFromContext`, `next-drupal` will automatically deserialize the data for you.

**Comment by jdrew-byte** [comment]
@shadcn Thank you, looks like it was actually a permissions/oauth issue. So it wasn't attaching the data I needed.
