### ISSUE TITLE
404s for nodes created in non-default language in multilingual Drupal site

### ISSUE THREAD

**Issue by alain0** [chapter-three/next-drupal#49]
I've just started with your basic starter and an existing multilingual Drupal site and I am able to fetch all nodes on the index page (with getResourceCollectionFromContext) 

But for individual nodes I get 404s for some of them, getResourceFromContext returns null. 
I found out that the nodes that can't be found are nodes which were create in the second language of the site instead of the default. 

Any thoughts on what I can do to make it work?

**Comment by shadcn** [comment]
Sure. Can you share the code for `getResourceFromContext` / `getStaticProps`?

The `example-marketing` site is a multilingual site. You can take a look at the codes here: https://github.com/chapter-three/next-drupal/tree/main/examples/example-marketing

**Comment by alain0** [comment]
Thanks, had a quick look at marketing example. I'm not spotting differences I think are relevant for my problem. I saw the params for getResourceFromContext are set with drupal-jsonapi-params so I tried to do that as well, without success.

Code below is from [...slug].tsx. It's almost unchanged from what is in the starter except that I changed the params part (for other node type and now with drupal-jsonapi-params)
```typescript
export async function getStaticProps(
  context
): Promise<GetStaticPropsResult<NodePageProps>> {
  const type = await getResourceTypeFromContext(context)
  //const type = 'node--event' // --> if I set this manually node fetching still fails

  if (!type) {
    //console.log('type', type)
    return {
      notFound: true,
    }
  }

  const apiParams = new DrupalJsonApiParams()

  if (type === "node--event") {
    apiParams.addInclude(["field_media", "uid"])
  }

  const node = await getResourceFromContext<DrupalNode>(type, context, {
    params: apiParams.getQueryObject(),
  })

  if (!node?.status) {
    //console.log('node', node)
    return {
      notFound: true,
    }
  }

  return {
    props: {
      preview: context.preview || false,
      node,
    },
    revalidate: 60,
  }
}
```

**Comment by shadcn** [comment]
Can you visit one of the translated node paths and see what's in `context`? `console.log(context)`

**Comment by shadcn** [comment]
We are looking for something like this in `context`:

```
{
  params: { slug: [ 'post', 'un-autre-article' ] },
  locales: [ 'en', 'fr' ],
  locale: 'fr',
  defaultLocale: 'en'
}
```

**Comment by alain0** [comment]
Thanks for all the help, much appreciated!

So logging context for both working and non working nodes gives undefined locales:

```javascript
{
  params: { slug: [ 'event', 'biohack-academy-2022' ] },
  locales: undefined,
  locale: undefined,
  defaultLocale: undefined
}
```

Something wrong with my Drupal site?

**Comment by shadcn** [comment]
Do you have i18n configured in `next.config.js`?

https://github.com/chapter-three/next-drupal/blob/ba037c3e48b730e1cfa1a97ab81ef6e78e669512/examples/example-marketing/next.config.js#L2

**Comment by alain0** [comment]
I didn't. I now have. And issue fixed!
Sorry for not spotting that in the example you've sent me right away...
Thanks!

**Comment by shadcn** [comment]
No worries. Happy you got it sorted out. I'm going to close this issue.

If you need help with anything else, you can open a new issue or ping me on [Drupal Slack](https://drupal.slack.com/archives/C01E36BMU72).
