### ISSUE TITLE
Support for T3 / tRPC

### ISSUE THREAD

**Issue by timmyjs** [chapter-three/next-drupal#498]
Hi there 👋 

I hope this is the right place asking for it, but couldn't find anything else 🙂 

Does this plugin support a [T3](https://create.t3.gg/) based setup (especially [tRPC](https://trpc.io/docs/nextjs/setup) based API routes) out of the box as well? Alternatively, are there any guides how to make that work?

**Comment by robdecker** [comment]
We are using a combo of tRPC/Zod internally on client projects. This works out of the box. We don't have any guides/examples at the moment, but we will consider adding those in the near future.
