### ISSUE TITLE
Example code of getResourceByPath is invalid

### ISSUE THREAD

**Issue by sakkelaaksonen-siili** [chapter-three/next-drupal#50]
https://next-drupal.org/docs/reference#getresourcebypath

Example uses extra **first** parameter "**type**" , which is  not found in the actual implementation.

**Comment by shadcn** [comment]
Ah you're right. I'll fix. Thank you.

**Comment by shadcn** [comment]
Done. https://next-drupal.org/docs/reference#getresourcebypath

Thank you.
