### ISSUE TITLE
Support for Next.js draft mode

### ISSUE THREAD

**Issue by JohnAlbin** [chapter-three/next-drupal#502]
The new App Router feature of Next.js 13.4 doesn't work with the old Preview Mode API. Instead Next.js apps that use the App directory need to use the new Draft Mode feature.

Here's a blog post mentioning the Draft Mode feature (under "other improvements") included with Next.js 13.4: https://nextjs.org/blog/next-13-4#other-improvements

And here is [Next.js' Draft Mode documentation](https://nextjs.org/docs/app/building-your-application/configuring/draft-mode)

This request is related to #442, but that issue specifically mentions the Server Components part of the App Router feature and Draft Mode isn't related to Server Components.

**Comment by dottodot** [comment]
Draft mode is also recommended for pages too https://nextjs.org/docs/pages/building-your-application/configuring/draft-mode but the implementations are slightly different which would need to be taken into account.

Also there doesn't seem to be a replacement for `setPreviewData` so revisions will need a rethink.

**Comment by JohnAlbin** [comment]
@dottodot Thanks so much for the link!

Somehow I had missed that Draft Mode was recommended for pages router. That simplifies what next-drupal needs to support when a website is only partially migrated from pages router to app router.

**Comment by JohnAlbin** [comment]
Fixed with #670
