### ISSUE TITLE
When displaying a past revision of a node with paragraph, the paragraphs are displayed at their latest revision

### ISSUE THREAD

**Issue by vermario** [chapter-three/next-drupal#509]
The issue: 

If you have: 

* a node with a paragraph field
* revisions enabled on the content type
* the next.js preview setup

When viewing a _past_ revision of the node, the paragraphs will be shown at their last revision, so the preview will have incorrect data.

Here's a screencast to explain the issue: 

[output.webm](https://github.com/chapter-three/next-drupal/assets/185412/f26edb25-61de-456f-97a0-e8d73e07c7c5)

I suspect this could be a limitation of jsonapi + paragraphs, but I wanted to ask if this actually works in @shadcn 's marketing example, where paragraphs are also used.

**Comment by dgsiegel** [comment]
@vermario would you mind trying the patch on this issue https://www.drupal.org/project/drupal/issues/3088239 and see if the problem persists?

**Comment by vermario** [comment]
Hi! 

The patch at https://www.drupal.org/project/drupal/issues/3088239#comment-14708895 seems to fix the issue: 

![image](https://github.com/chapter-three/next-drupal/assets/185412/5af3c454-5450-4d42-b171-873c2756ae32)


 Thank you very much for the pointer! We will add it to our template.

**Comment by iamfredrik** [comment]
I'm experiencing a similar issue, but the patch did not work in my case. Instead the paragraph fields became completely inaccessible on translated content after applying the patch. Reverting the patch made the fields accessible again, but they are showing the wrong revision. Any workaround for use with translations?
