### ISSUE TITLE
[Docs] Update Webform guide with necessary Drupal module

### ISSUE THREAD

**Issue by blyme** [chapter-three/next-drupal#510]
In step 2 under installation on https://next-drupal.org/guides/webform, it is needed to go to `/admin/config/services/rest` and enable the Webform Submit resource. That route is only a part of the https://www.drupal.org/project/restui module and I think it should be documented that the module is needed in order for that route to be there or how we can enable the resource without it 😄 

If I can make a PR to the docs, I'll happily do it but it doesn't seem like the docs are publicly available as a repo?

**Comment by theRuslan** [comment]
> If I can make a PR to the docs, I'll happily do it but it doesn't seem like the docs are publicly available as a repo?

All the docs in this repo, you can find it in www > content
