### ISSUE TITLE
[Docs] next-drupal-query package

### ISSUE THREAD

**Issue by taskrider2022** [chapter-three/next-drupal#512]
I have started to write a boilerplate that I will use as a starter for future projects. I like the example with the next-drupal-query package.

What I haven't found is documentation for the package. Can you possibly provide a guide or an extended documentation for it.

And do you think that this package will be developed further?

**Comment by robdecker** [comment]
The next-drupal-query package was a prototype we used on a couple projects, but we found that utilizing a combination of [tRPC](https://trpc.io) and [Zod](https://zod.dev) works quite well. They are both very popular tools that many developers already have experience with.

There was a good amount of overlap between next-drupal-query and tRPC/Zod, so we're standardizing on the tRPC/Zod combo internally. 

At this time, we have no plans to further develop next-drupal-query.
