### ISSUE TITLE
Error: Call to a member function getSitesForEntity() on null in Drupal\next\Render\MainContent\HtmlRenderer->prepare()

### ISSUE THREAD

**Issue by pookmish** [chapter-three/next-drupal#517]
When I attempt to configure an Next entity type for an on demand revalidation for certain entity types, I receive the error: `Call to a member function getSitesForEntity() on null in Drupal\next\Render\MainContent\HtmlRenderer->prepare()`.

I see the interface defines the return type as `?SiteResolverInterface` indicating the return value could be null. The HtmlRenderer should handle null values from the method `getSiteResolver`.

This is reproduced by configuring a revalidation on a redirect entity type.

**Comment by jeffschuler** [comment]
We're experiencing this, too, as I described in #495.
#480 + #481 are essentially the same issue and fix.
