### ISSUE TITLE
Status of Next Drupal

### ISSUE THREAD

**Issue by dottodot** [chapter-three/next-drupal#520]
Hello just wondering what the status of this project is as it seems to have gone a bit quite recently, there as some issues such https://github.com/chapter-three/next-drupal/issues/488 which prevent updating Nextjs, so this is really just to get a gauge on when and if they might be fixed, or if I should start to look at finding a fix myself, just don't want to waste time working on it if something is in the pipeline.

**Comment by MartinDavi** [comment]
Would be great to know - @shadcn looks to have joined Vercel. Is someone carrying the torch at chapter-three or should we start forking?

**Comment by dottodot** [comment]
@robdecker thanks for the update will definitely try and help out as and when I get the time

**Comment by JohnAlbin** [comment]
See #692
