### ISSUE TITLE
Calling getView() and getting relationship data

### ISSUE THREAD

**Issue by SmokeSouls** [chapter-three/next-drupal#524]
Hi,

I had a quick question relating to the getView function. How can I get a
field if that field uses a relationship?

So far I have this:

```
const companies_carousel = await drupal.getView(
      "companies--homepage_companies_carousel",
      {
        locale: "en",
        defaultLocale: "el",
        params: {
          include: "field_company_logo.field_media_image",
        },
      }
    );
```
This allows me to get the company logo but I need another field which are the
number of job vacancies this company has. The Job content type has a
field_company entity reference field and in Views I simply add that as a
relationship to get Job fields related to each company. I can get this just
fine using Views but I don't know how to send it through Next.js for Drupal.
Would appreciate any help you can give me.

**Comment by robdecker** [comment]
This question has been answered in the Drupal module's [issue queue](https://www.drupal.org/project/next/issues/3386110#comment-15235238).
