### ISSUE TITLE
setup using docker?

### ISSUE THREAD

**Issue by himbolion** [chapter-three/next-drupal#54]
Would it be possible to add a Guide on how to set this up using Docker? 
I tried to just "Extend" using the .tar.gz file I can download from the drupal.org site, but said file doesn't include it's needed modules. 

Having a next-drupal docker image that includes composer, would be neat imo

**Comment by himbolion** [comment]
I tried to just "Extend" using the .tar.gz file I can download from the drupal.org site, but said file doesn't include it's needed modules

![image](https://user-images.githubusercontent.com/20520193/144738868-a97aad2a-ad58-41b4-b350-cb1a60989e8a.png)

**Comment by shadcn** [comment]
Can you use composer? It will pull the dependencies for you.

**Comment by himbolion** [comment]
Ah, it turns out I didn't try using the CLI. composer is already included in the drupal docker image
