### ISSUE TITLE
getPathsFromContext for taxonomy terms

### ISSUE THREAD

**Issue by alain0** [chapter-three/next-drupal#56]
Is it possible to use the getPathsFromContext for taxonomy terms?

I'm using it like so:

```js
const paths = await getPathsFromContext(
  ["taxonomy_term--themes"],
  context,
  { params: { 
    "filter[status]": "1"
  } }
)
```
This does return an array (with the correct amount of items) but the slugs are undefined:

```js
{ 
  params: { 
    slug: [ 'undefined' ]
  },
  locale: 'en'
}
```
I couldn't find the use of getPathsFromContext for taxonomy terms in the examples so maybe it's just not implemented or am I doing something wrong?

**Comment by shadcn** [comment]
Yes. Any entity type should work. 

Did you configure path alias for taxonomy terms?

**Comment by alain0** [comment]
I did. And also tried to regenerate aliases, also with deleting all existing aliases beforehand.
I also tried other vocabularies. And also tried passing content without locales. All to no avail..
Do you have any other suggestions?
Thanks in advance!

**Comment by alain0** [comment]
I now see the preview in Drupal giving me an error: "Error: the path attribute is missing for entity type taxonomy_term--themes"
When I check the json response (/en/jsonapi/taxonomy_term/themes?fields[taxonomy_term--themes]=path&filter[status]=1), I see the path attribute is indeed missing. I can however add other attributes to the request (like the 'name') and those turn up in the response.
This field is not excluded via the overrides in the JSON:API settings. What else can prevent Drupal from return the path?

**Comment by alain0** [comment]
Ok solved. Found the solution here: https://www.drupal.org/project/jsonapi/issues/3012019

In my case running this did the trick:

```bash
drush config:delete core.base_field_override.taxonomy_term.themes.path
```

**Comment by shadcn** [comment]
Aha. I’ve been burned more than once by this. I’ll document this for others. 

Thank you
