### ISSUE TITLE
GraphQL requests from next-drupal do not work after GraphQL module update to 4.6.0

### ISSUE THREAD

**Issue by cruno91** [chapter-three/next-drupal#588]
### Package containing the bug

next-drupal (NPM package)

### Describe the bug

After updating the GraphQL module to 4.6.0, next-drupal GraphQL requests no longer work.

The GraphQL 4.6.0 update included [this set of changes](https://github.com/drupal-graphql/graphql/commit/237652097030c824f5313cfd1b8a476eeb5e0419#diff-4c2ba4a9c82001ac8140ed15ecaca59c67711727b26f899ffade45d08538e17fR83) which checks headers' Content-Type on requests.

GraphQL requests in [next-drupal use "application/vnd.api+json"](https://github.com/chapter-three/next-drupal/blob/main/packages/next-drupal/src/client.ts#L49) for the Content-Type which does not match the checks in the module.

This results in an error when trying to navigate to any NextJS page that uses `drupal.fetch()` from next-drupal to fetch data from Drupal's GraphQL:

```
⨯ lib/drupal.ts (37:10) @ query
 ⨯ Error: Bad Request
    at query (webpack-internal:///./lib/drupal.ts:28:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getStaticProps (webpack-internal:///./pages/index.tsx:39:18) {
  page: '/'
}
  35 | 
  36 |   if (!response?.ok) {
> 37 |     throw new Error(response.statusText)
     |          ^
  38 |   }
  39 | 
  40 |   const { data, errors }: QueryJsonResponse<DataType> = await response.json()
 ✓ Compiled /_error in 203ms (497 modules)
```

The server-side (Drupal) error is:

```
Symfony\Component\HttpKernel\Exception\BadRequestHttpException: The content type 'application/vnd.api+json' is not supported. in Drupal\graphql\Routing\QueryRouteEnhancer->assertValidPostRequestHeaders() (line 104 of /app/drupal/web/modules/contrib/graphql/src/Routing/QueryRouteEnhancer.php).
```

### Expected behavior

Requests succeed by passing the expected Content-Type for the GraphQL module.

### Steps to reproduce:

1. Make successful GraphQL requests from a next-drupal site to a Drupal site running GraphQL module version 4.5
2. Update GraphQL to 4.6
3. Clear Drupal cache
4. Re-run the next-drupal server and make the same request
5. You will see the errors detailed above

### Additional context

Drupal slack thread: https://drupal.slack.com/archives/C01E36BMU72/p1699467051864729

**Comment by JohnAlbin** [comment]
Fixed in #598
