### ISSUE TITLE
use next/config instead of process.env

### ISSUE THREAD

**Issue by sakkelaaksonen-siili** [chapter-three/next-drupal#59]
Using process.env in any code will prevent those variables from being passed on to various build and runtime phases if not using .env-files.
use next/config instead so that environment variables can be set and used from actual environment and not just .env-files

**Comment by shadcn** [comment]
Which of the config would be better a non .env? Can you share an example?

Thank you

**Comment by sakkelaaksonen-siili** [comment]
Well for example, retrieving the values from a configuration service. The more intricate issue is that when the rendering code(all of the methods in this package are meant to be executed in pages or components) calls process.env directly, it is hard to reliably set the env vars without .env files, which cannot always be included in the repository if there are secrets, between build and server runtime when dockerizing in multistage environments. I know it's not the most common use case though,

**Comment by sakkelaaksonen-siili** [comment]
as in which config is better (assuming you mean public or server runtime configs), well that is defined by the call scope of each function. If it can run in browser, it must be public.

**Comment by shadcn** [comment]
I see. I’m take a look at how best we can solve this.

**Comment by sakkelaaksonen-siili** [comment]
https://github.com/vercel/next.js/discussions/16995
The problem arises especially if you run next outside vercel. Not supporting multiple build env and such is a major problem in the Nextjs ecosystem. Referencing process.env anywhere outside build configs is going to cause trouble to somebody.
I just refactored my own code to set NEXT_PUBLIC_DRUPAL_BASE_URL to getConfig and use it from there.

**Comment by shadcn** [comment]
The `DrupalClient` now handles this and we explicitly removed all dependencies on environment variables in the client.

Marking this as done. Feel free to re-open if you have any question. Happy to discuss this further. Thank you.
