### ISSUE TITLE
Request for Next-Drupal Roadmap for Upcoming Major/Minor Release

### ISSUE THREAD

**Issue by Danishkhurshid** [chapter-three/next-drupal#595]
### Package

next-drupal (NPM package)

### Ask the question

Requesting details on the roadmap for the next major/minor releases. Please share insights on planned features, deprecated functionalities, and any planned updates to the documentation. 

This information will help the community prepare for and contribute to the next phase of Next-Drupal.

**Comment by Danishkhurshid** [comment]
@JohnAlbin mentioning you here because it appears that you're the only one currently engaged in this project.

**Comment by JohnAlbin** [comment]
See #692
