### ISSUE TITLE
Graphql

### ISSUE THREAD

**Issue by dottodot** [chapter-three/next-drupal#6]
Hello, just looking into using this module but I'll be using graphql rather than the rest api. Just wanted to check if it will work in particular with Incremental Static Regeneration.

**Comment by arshad** [comment]
Yes. The Next [module](https://www.drupal.org/project/next) works with both JSON API and GraphQL. 

The [next-drupal](https://github.com/chapter-three/next-drupal/tree/main/packages/next-drupal) however works only with JSON API right now.

**Comment by violabg** [comment]
are you planning on implementing GraphQL for next-drupal?

**Comment by shadcn** [comment]
Not for now. However we are following @jmolivas work on schema generation and will decide on how best to support it.

**Comment by shadcn** [comment]
See also https://www.chapterthree.com/blog/nextjs-drupal-and-graphql-how-to-use-graphql-next-drupal
