### ISSUE TITLE
Module '"next-drupal"' has no exported member 'DrupalNode'.

### ISSUE THREAD

**Issue by simon-olsen** [chapter-three/next-drupal#60]
I just started a fresh install of `npx create-next-app -e https://github.com/chapter-three/next-drupal-basic-starter` and I'm getting the following problem in my VS Code.

```
import {
  DrupalNode,
  getPathsFromContext,
  getResourceFromContext,
  getResourceTypeFromContext,
} from "next-drupal"
```

`Module '"next-drupal"' has no exported member 'DrupalNode'.`

I checked a previous Next-Drupal project I worked on and DrupalNode wasn't being imported there. My current project also seems to work fine.

Is this new? Do I need to configure or install a different version of `next-drupal`? This is what I have currently...

```
"dependencies": {
    "@hookform/resolvers": "^2.8.3",
    "axios": "^0.24.0",
    "next": "^11.1.2",
    "next-drupal": "^0.15.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.19.5",
    "styled-components": "^5.3.3",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.14.0",
    "@types/node": "^15.0.2",
    "@types/react": "^17.0.4",
    "autoprefixer": "^10.2.6",
    "babel-plugin-styled-components": "^1.13.3",
    "eslint": "^7.28.0",
    "eslint-config-next": "^11.0.0",
    "postcss": "^8.3.5",
    "typescript": "^4.3.5"
  },
```

**Comment by shadcn** [comment]
Can you try updating to `next-drupal 1.0.0`? `DrupalNode` is a type exported by `next-drupal`.

**Comment by shadcn** [comment]
@simon-olsen is this still an issue?

**Comment by simon-olsen** [comment]
Upgrading to `^1.0.0` fixed the issue. Thanks for your help!
