### ISSUE TITLE
Viewing a node when Next.js site doesn't have preview URL configured throws an exception

### ISSUE THREAD

**Issue by mglaman** [chapter-three/next-drupal#602]
### Package containing the bug

next (Drupal module)

### Describe the bug

The **Preview URL** is not required. So you can save a Next.js site without one. 

Simple OAuth URL generator is crashing

### Expected behavior

Preview URL should be marked as required or not crash

### Steps to reproduce:

1. First create a Next.js site without a preview URL
2. Then create a node
3. View the node
4. 😢

**Comment by apmsooner** [comment]
@mglaman - I provided a solution for this several months ago - just needs to get approved/merged. https://github.com/chapter-three/next-drupal/pull/481

**Comment by JohnAlbin** [comment]
Fixed with #481
