### ISSUE TITLE
It was not possible to parse your key

### ISSUE THREAD

**Issue by Msteimel** [chapter-three/next-drupal#61]
I've been running into the following issue below after following the quick start Guide

![Screen Shot 2021-12-17 at 2 34 41 PM](https://user-images.githubusercontent.com/25468002/146604658-20fe1eb6-f9e3-47af-872d-b2fde8278079.png)

I check the drupal logs and get the following error: _Lcobucci\JWT\Signer\InvalidKeyProvided: It was not possible to parse your key, reason: in Lcobucci\JWT\Signer\InvalidKeyProvided::cannotBeParsed()_ 

Auth tokens are being generated when visiting the Next.js site and the path to the keys seem correct.

I'm running php 7.4

**Comment by shadcn** [comment]
@Msteimel How were the keys generated?

**Comment by Msteimel** [comment]
@shadcn I followed the steps on the start guide https://next-drupal.org/learn/quick-start/create-consumer 

When that didn't work I tried the _openssl_ and get the same error.

**Comment by shadcn** [comment]
Let me see if I can try to reproduce this. 

Can you add more details about your setup? How are you running Drupal? ddev? Valet…etc?

Thank you

**Comment by Msteimel** [comment]
I'm using Valet. 

The keys are located outside the web root.

I originally faced the same issue [has issue #15](https://github.com/chapter-three/next-drupal/issues/15) but that no longer is the case. 

I've checked the server logs and don't see errors (but I'm not a server expert by any means).

**Comment by shadcn** [comment]
@Msteimel Is this still an issue? Did you figure it out?

**Comment by Msteimel** [comment]
@shadcn I got busy with some other projects. I'll try again with a fresh install when I get a chance.
