### ISSUE TITLE
Remove scope from preview URL generation and validation process

### ISSUE THREAD

**Issue by bojanbogdanovic** [chapter-three/next-drupal#635]
### Package

Not package-specific

### Describe the feature request

Currently the scope is being determined by the current user and its assigned role. This is then being used in the generation and validation process of the preview URL. This seems redundant if we can just lean on the default scopes from the associated consumer, also the scope/role is exposed in the preview URL, the preview URL can be shared and used by anonymous users and ideally from a security perspective we don't want to expose the user role. Another issue with this setup is that this is not compatible with simple_oauth:6.0, which gives the possibility to have scopes that are mapped directly to permissions instead of roles.

### Describe the solution you'd like
I would like to remove the scope from the preview URL generation and validation process. The docs already state that the default scope needs to be set on the consumer, with this solution the main difference would be that the default scope always is used instead of the scope/role that is assigned on the user that is generating the preview URL.

**Comment by JohnAlbin** [comment]
>  the main difference would be that the default scope always is used instead of the scope/role that is assigned on the user that is generating the preview URL.

Sending the scope/role of the user viewing the Drupal content site doesn't make any sense. The current user has nothing to do with the authentication that the `next-drupal` code will use to connect to Drupal. On my test site, I've got a special role for the Next.js user which means the oauth scope is unique to that user and doesn't match any other Drupal user.

Also, I took a look and the scope sent via the search params by Drupal aren't actually used by the `next-drupal` code when doing authentication with the Drupal server. The scope is just returned back to the Drupal server in the fetch body's JSON. So… it's completely superfluous.

I'm totally fine with this change. :)
