### ISSUE TITLE
No route found for the specified format api_json on translatePath()

### ISSUE THREAD

**Issue by vhin0210** [chapter-three/next-drupal#654]
### Package containing the bug

next-drupal (NPM package)

### Describe the bug

Pages always return 404. Saw the error below in Drupal logs.

`Response failed validation. Response: {"jsonapi":{"version":"1.0","meta":{"links":{"self":{"href":"http:\/\/jsonapi.org\/format\/1.0\/"}}}},"errors":[{"title":"Not Acceptable","status":"406","detail":"No route found for the specified format api_json. Supported formats: json.","links":{"via":{"href":"http:\/\/nginx\/router\/translate-path?path=%2Fblog%2Ftest"},"info":{"href":"\u003Chttp:\/\/nginx\/router\/translate-path?path=\/blog\/test\u0026_format=json\u003E; rel=\u0022alternate\u0022; type=\u0022application\/json\u0022"}}}]} Errors: [{"property":"meta","pointer":"\/meta","message":"The property meta is required","constraint":"required","context":1},{"property":"","pointer":"","message":"The property errors is not defined and the definition does not allow additional properties","constraint":"additionalProp","context":1},{"property":"data","pointer":"\/data","message":"The property data is required","constraint":"required","context":1},{"property":"errors[0].links.info.href","pointer":"\/errors\/0\/links\/info\/href","message":"Invalid URL format","constraint":"format","context":1,"format":"uri-reference"},{"property":"errors[0].links.info","pointer":"\/errors\/0\/links\/info","message":"Object value found, but a string is required","constraint":"type","context":1},{"property":"errors[0].links.info","pointer":"\/errors\/0\/links\/info","message":"Failed to match exactly one schema","constraint":"oneOf","context":1},{"property":"","pointer":"","message":"Failed to match exactly one schema","constraint":"oneOf","context":1}]`

### Expected behavior

Page should load. /router/translate-path should return status 200

### Steps to reproduce:

Sadly, I'm not sure. It was working before but I don't know how it get to this :(

**Comment by JohnAlbin** [comment]
404 is the correct response when you go to `/router/translate-path` and don't specify a path to translate.

If you use Firefox, it will pretty print the JSON response on that 404 page and show you:
```
{"message":"Unable to translate empty path. Please send a ?path query string parameter with your request."}
```

**Comment by vhin0210** [comment]
![Screenshot from 2024-05-25 23-29-58](https://github.com/chapter-three/next-drupal/assets/1862334/bacca292-e58f-4144-8c28-7ada60420995)

@JohnAlbin 

The error is "No route found for the specified format api_json" but the request sent has no _format parameter. Please look at the screenshot.
