### ISSUE TITLE
addFields() not working for getResourceFromContext()?

### ISSUE THREAD

**Issue by alain0** [chapter-three/next-drupal#66]
Hi,

In an effort to reduce the amount of data for certain pages (nextjs is giving me warnings :) I'm trying to use **addFields()** on the params I pass to **getResourceCollectionFromContext** and **getResourceFromContext** within getStaticProps. This works fine for **getResourceCollectionFromContext** but for **getResourceFromContext** I keep getting all fields returned for the requested node and its included relationships. 

It seems it should be possible as it is also used on **getResourceFromContext** in the advanced example from the docs (https://next-drupal.org/docs/data-fetching#advanced-example).

I tried it as well without drupal-jsonapi-params, by just setting the fields key in the params object. No luck.
I also tried using the query string (obtained by params.getQueryString()) and querying the Drupal jsonapi directly. Then I do get only the specified fields.

Is this a bug? Am I missing something?

**Comment by shadcn** [comment]
Can you share the code or just the params/fields part? Thank you.

**Comment by alain0** [comment]
Sure:

```js
  const params = new DrupalJsonApiParams()
  const type = await getResourceTypeFromContext(context) 
  params.addFields(type, ["id", "title", "path", "body"])

  const node = await getResourceFromContext(type, context, { params: params.getQueryObject() })
  ```

**Comment by alain0** [comment]
With **getResource** it also works btw:

```js
  const params = new DrupalJsonApiParams()
  params.addFields("node--article_waag", ["id", "title", "path", "body"])

  const node = await getResource("node--article_waag", "997c7273-2262-4f6b-89f3-e70f8a01595a", {
    params: params.getQueryObject()
  })
```

**Comment by shadcn** [comment]
You're right. We fixed nested params [here](https://github.com/chapter-three/next-drupal/commit/651d6976f88d3f4097df1c41648412837262df4a) but `getResourceFromContext` does not call this.

Working on a fix...

**Comment by shadcn** [comment]
Update: I have a fix ready. Adding some tests and I'll push it.

**Comment by shadcn** [comment]
I just tagged `next-drupal` `1.0.1` with the fix. Can you update and try again? Thank you.

**Comment by alain0** [comment]
I can confirm it is now working as expected. 

Thanks for your super swift replies and fix!

**Comment by shadcn** [comment]
Awesome. 

Thanks for reporting this bug. This helped me find another one :)
