### ISSUE TITLE
getAccessToken doesn't verifies the clientId and clientSecret in optional parameters.

### ISSUE THREAD

**Issue by Arijeet996** [chapter-three/next-drupal#667]
### Package containing the bug

next-drupal (NPM package)

### Describe the bug

The `getAccessToken` function currently doesn't  verifies the optional authentication parameters leading to an error stating that `'clientId' and 'clientSecret' required.`, even when provided in the optional parameters.

### Expected behavior

The `getAccessToken` function needs to verify the existence of `clientId` and `clientSecret` in both the default authentication and optional authentication parameters. If these credentials are not present in either of them, an error should be thrown indicating that both `clientId` and `clientSecret` are required.

### Steps to reproduce:

1. Try fetching a resource which needs oauth authentication.
2. Don't pass the auth credentials as default params with DrupalClient
3. Pass the auth credentials as optional params. 

Example:

```typescript
const translatedPath = await drupal.translatePath(path, {
      withAuth:  {
          clientId: YOUR_CLIENT_ID,
          clientSecret: YOUR_CLIENT_SECRET,
          url: YOUR_URL
      } 
})
```

**Comment by JohnAlbin** [comment]
Fixed with #707
