### ISSUE TITLE
found 404, for [.../slug], with multilingual module installed

### ISSUE THREAD

**Issue by amit-mall** [chapter-three/next-drupal#678]
### Package containing the bug

I’m not sure

### Describe the bug

I can  see path object is missing in `/jsonapi/node/page`. While I use a drush command to fix this. `drush config:delete core.base_field_override.node.page.path`.  Now path is visible 
`"path": {
"alias": "/page",
"pid": 114222,
"langcode": "und"
}`
still I'm getting path null from below:
`const path = await drupal.translatePathFromContext(context)`
This issue is only with multilingual site, for normal website, it's working fine
please help me in this

**Comment by amit-mall** [comment]
@shadcn @JohnAlbin please help me into this

**Comment by JohnAlbin** [comment]
You need to re-read about Next.js' Dynamic Path Segments. https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes

`[.../slug]` should be `[...slug]`. That error is probably preventing Next.js from putting a valid `slug` field inside the `context` variable.
