### ISSUE TITLE
Node version / NVM/ Mac M1... ECONNREFUSED

### ISSUE THREAD

**Issue by scotthooker** [chapter-three/next-drupal#69]
I've spent a good bit of time debugging this random access token problem. 

`POST /oauth/token HTTP/1.1
Authorization: Basic MjhlNzQ2MTYtNDBjYy00YjhjLWE2OWUtYmJiMzU4NTk0NDNkOnNlY3JldA==
Content-Type: application/x-www-form-urlencoded;charset=UTF-8`

works fine in postman, terminal etc... but fails inconsistently across a few different sites within node-fetch

I THINK I've narrowed it down to node versions / nvm weirdness on M1 Apple Silicon.

Proposal: Add in to docs recommended local set up nvm version etc... 

Question: Does this seem logical as the router of the problem? Could someone who is also seeing this issue test a change in node?

**Comment by shadcn** [comment]
@scotthooker did you figure this out? What environment are you running Drupal on (ddev, docker)? I'll see if I can get hold of an M1 machine to test.

**Comment by scotthooker** [comment]
Aye latest of both - pretty sure its node / nvm issues with fetch

**Comment by scotthooker** [comment]
Same as the linked issue can be closed.
