### ISSUE TITLE
Error: 500 Service unavailable

### ISSUE THREAD

**Issue by sabbir-hossain** [chapter-three/next-drupal#7]
I'm new to drupal and trying to setup drupal with next.js. I have followed every steps from [https://next-drupal.org/docs/quick-start](url). I haven't found any issue while configuring **drupal** and **next.js**. But when I try to run my next.js project I get the following error:

```
Error: 500 Service unavailable (with message)
    at ..\next-js-project\node_modules\next-drupal\dist\index.js:23:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getStaticProps (..\next-js-project\.next\server\pages\index.js:3584:20)
    at async renderToHTML (..\next-js-project\node_modules\next\dist\next-server\server\render.js:27:178
0)
    at async ..\next-js-project\node_modules\next\dist\next-server\server\next-server.js:112:97
    at async __wrapper (..\next-js-project\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (..\next-js-project\node_modules\next\dist\next-server
\server\next-server.js:137:387)
    at async DevServer.renderToHTML (..\next-js-project\node_modules\next\dist\next-server\server\next-s
erver.js:138:610)
    at async DevServer.renderToHTML (..\next-js-project\node_modules\next\dist\server\next-dev-server.js
:36:578)
    at async DevServer.render (..\next-js-project\node_modules\next\dist\next-server\server\next-server.
js:75:160)
```
I'm using **windows** and **xampp**. I setup my drupal in htdocs like following structure.

```
|--xampp
      |----htdocs
               |-----vendor
               |-----web
               |-----comoser
````
My environment data:
```
NEXT_PUBLIC_DRUPAL_BASE_URL=http://localhost:8080/web
NEXT_IMAGE_DOMAIN=localhost
DRUPAL_SITE_ID=18903ef4-b720-40cf-8557-f71eb8bed89c
DRUPAL_FRONT_PAGE=/node
DRUPAL_PREVIEW_SECRET=preview-secret-here-should-be-unique
DRUPAL_CLIENT_ID=71bdaea3-fecb-4f32-944e-d455fef8a837
DRUPAL_CLIENT_SECRET=abc1234
```

And I have added  `console.log(process.env)` in `_app.tsx` and I think it show all of my environment data.

How can I solve this issue?
Thanks in advance.

**Comment by arshad** [comment]
A `500` error might be something on the Drupal end. Can you check if `/jsonapi` path is reachable on your Drupal site?

**Comment by sabbir-hossain** [comment]
@arshad yes, it is reachable.

**Comment by arshad** [comment]
Anything in the Drupal logs?

**Comment by arshad** [comment]
@sabbir-hossain Did you figure this out?

**Comment by sabbir-hossain** [comment]
@arshad I have deploy drupal project in cloud. then it is working.

**Comment by jsheffers** [comment]
I've run into this same issue

Drupal logs show:  

```ArgumentCountError: Too few arguments to function Drupal\simple_oauth\Entities\AccessTokenEntity::convertToJWT(), 0 passed in /Path/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php on line 78 and exactly 1 expected in Drupal\simple_oauth\Entities\AccessTokenEntity->convertToJWT() (line 21 of /Path/web/modules/contrib/simple_oauth/src/Entities/AccessTokenEntity.php)```

**Comment by arshad** [comment]
@jsheffers I think I've seen this before. Does this patch/thread help? https://www.drupal.org/project/simple_oauth/issues/3194635

**Comment by jsheffers** [comment]
For me, this was because of PHP 8 and dependency issues. Applying the patch from the following thread to `drupal/simple_oauth` and it fixed this issue.

https://www.drupal.org/project/simple_oauth/issues/3230707

**Comment by Msteimel** [comment]
> For me, this was because of PHP 8 and dependency issues. Applying the patch from the following thread to `drupal/simple_oauth` and it fixed this issue.
> 
> https://www.drupal.org/project/simple_oauth/issues/3230707

I'm running into the same issue. I get two of the exact same error in the drupal log. Applying the patch you referenced causes one of the errors to go away.
