### ISSUE TITLE
Allow 2.x of "cweagans/composer-patches".

### ISSUE THREAD

**Issue by rajeshreeputra** [chapter-three/next-drupal#704]
### Package

next-drupal (NPM package)

### Describe the feature request

Update composer.json to allow both the version of "cweagans/composer-patches".

**Comment by JohnAlbin** [comment]
From #705:

> The installation instructions for Next Drupal already include requiring composer-patches to the Drupal project using the Next module. From https://next-drupal.org/learn/quick-start/apply-patches
>
> That means this require line in the module's composer.json is redundant/can conflict with with the Drupal project's composer.json.
>
> I think the proper fix to support either 1.x or 2.x of composer-patches is to remove the `"cweagans/composer-patches": "~1.0",` line from `modules/next/composer.json`
