### ISSUE TITLE
Can anyone give me a brief documentation?

### ISSUE THREAD

**Issue by maazshaikh7** [chapter-three/next-drupal#712]
### Package

I’m not sure

### Ask the question

Apart from npm install, what else do I have to do to get started. I can't find what environment variables are needed, and having some errors in running the file using `npm run dev` without changing anything. I am new to this so can someone please help me?

**Comment by robdecker** [comment]
Hi @maazshaikh7 please see the [Get Started](https://next-drupal.org/learn/quick-start) docs on the website.
