### ISSUE TITLE
Next.js 12 support?

### ISSUE THREAD

**Issue by siwinski** [chapter-three/next-drupal#73]
I am trying to add this project to an existing Next.js 12 site but it fails because `next-drupal` defines its `next` dependency requirement as `"next": "^11.0.0"`.  Will Next.js 12 be supported at some point?  If so, is there an ETA?

**Comment by shadcn** [comment]
Next.js 12 is supported. I'll update the peer dependencies. Thanks for heads up.

**Comment by sakkelaaksonen-siili** [comment]
:+1:
