### ISSUE TITLE
useMenu CORS in local

### ISSUE THREAD

**Issue by ambercit** [chapter-three/next-drupal#77]
useMenu in layout page 

Access to fetch at 'http://local.nextjs.com:8888/jsonapi/menu_items/main' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.esm.js?84fa:186 GET http://local.nextjs.com:8888/jsonapi/menu_items/main net::ERR_FAILED

**Comment by shadcn** [comment]
@ambercit Do you have CORS enabled? 

- https://www.drupal.org/node/2715637
- https://drupal.stackexchange.com/questions/245903/how-do-i-set-up-cors

**Comment by shadcn** [comment]
@ambercit did you figure this out?

**Comment by ambercit** [comment]
@shadcn we solve by the links you offer，is this will support drupal  layout build later

**Comment by shadcn** [comment]
@ambercit For Layout Builder we are currently blocked by this issue: [Expose Layout Builder data to REST and JSON:API](https://www.drupal.org/project/drupal/issues/2942975)
