### ISSUE TITLE
Getting ready for Drupal 11 for modules/next

### ISSUE THREAD

**Issue by apathak18** [chapter-three/next-drupal#777]
### Package

next (Drupal module)

### Ask the question

A clear and concise description of what the question is.
Drupal 11 is getting ready for a stable ~~ prepare next drupal module as D11 compatible 
If applicable, add screenshots to help explain your issue.
**Deprecating warnings**
<img width="964" alt="Screenshot 2024-06-16 at 9 11 05 PM" src="https://github.com/chapter-three/next-drupal/assets/106175376/9bf31c3f-0d53-4133-b7c1-bb9057fe1dba">

<img width="973" alt="Screenshot 2024-06-16 at 9 11 17 PM" src="https://github.com/chapter-three/next-drupal/assets/106175376/41293423-3ced-4fbf-904d-a984cabfaeb3">
**Adding D11 in .info.yml**
<img width="985" alt="Screenshot 2024-06-16 at 9 11 31 PM" src="https://github.com/chapter-three/next-drupal/assets/106175376/89b4cabd-f5cc-4aac-b2d9-67f4b7b195b1">

**Comment by backlineint** [comment]
This has been released as 2.0.0-beta1: https://www.drupal.org/project/next/releases/2.0.0-beta1
