### ISSUE TITLE
Path alias pattern causes conflict between live and preview

### ISSUE THREAD

**Issue by ysvahn** [chapter-three/next-drupal#82]
Hello !

I'm facing a weird problem : 

Setting `blog/[node:title]` as the path alias pattern does not work: On the app, the URL `localhost:3000/blog/slug` resolves to a 404, but `localhost:3000/blog/blog/slug` works but obviously isn't correct.
When I try to access the preview, the resolved URL is `localhost:3000/blog/slug` -> does not work (404)

When setting back the path alias pattern back to `/[node:title]` correctly resolves on `localhost:3000/blog/slug`.
The preview then resolves to `localhost:3000/slug` instead of `localhost:3000/blog/slug`, resulting in a 404.

Project structure is :
```
nextjs
    |___pages
          |____index.js
          |____[...slug].js
          |____blog
                 |___index.js
                 |___[...slug].js
```

`next-drupal` version used is 1.1.1, `drupal/next` version is 1.0.0

**Comment by shadcn** [comment]
What does your `getStaticPaths` look like in `pages/[...slug]` and `pages/blog/[...slug]`?

**Comment by Kroonax** [comment]
pages/[...slug].js :
```
export async function getStaticPaths(context) {
  return {
    paths: await getPathsFromContext(
      [
        "node--webform",
        "node--rich_content",
      ],
      context
    ),
    fallback: "blocking",
  };
}
```

pages/blog/[...slug].js :
```
export async function getStaticPaths(context) {
  const paths = await getPathsFromContext("node--event", context);
  return {
    paths,
    fallback: "blocking",
  };
}
```

A workaround I found is to change project structure to :

```
nextjs
    |___pages
          |____index.js
          |____[...slug].js
          |____blog.js
```

And put all the Blog type logic inside of the "main" [...slug].js but I personally think this solution is kind of ungraceful 😞

**Comment by shadcn** [comment]
Yeah this is how I usually do it. One [...slug].js to handle all node routes. But you're not limited to that you can use nested paths. 

Hold on. I'll send an example.

**Comment by shadcn** [comment]
### 1. Update `getStaticPaths` in `pages/blog/[...slug].js`

```js
export async function getStaticPaths(context) {
  const paths = await getPathsFromContext(["node--article"], context)

  // Delete the "blog" prefix for route.
  paths.map((path) => {
    path.params.slug.shift()

    return path
  })

  return {
    paths,
    fallback: "blocking",
  }
}
```

### 2. Pass in the `prefix` to `getStaticProps`

```js
export async function getStaticProps(context) {
  const node = await getResourceFromContext("node--article", context, {
    prefix: "blog", // <-------------------------
    params: {
      include: "field_image,uid",
    },
  })
}
```

We have a `prefix` option we can use here. Unfortunately next does not provide much in `context`. If we had the `dir` info that would be easier.

I think we can add the prefix options to `getPathsFromContext` as well to make this a bit simpler.

Can you give this a try and let me know?

**Comment by Kroonax** [comment]
This is actually pretty clever (even if a little bit clunky) and it works, too !

I totally forgot about the `prefix` option in getResourceFromContext since the context given to `getStaticProps` is so poor.

The `dir` thingy is something Next community has been asking since forever (like conditional rerendering fired by a Back Office for example haha)

You're truly a life saver, thanks a lot !
