### ISSUE TITLE
Can't find how to get includes from json api on getResourceByPath

### ISSUE THREAD

**Issue by je34429** [chapter-three/next-drupal#87]
I'm not sure if I'm doing something wrong but when I use getResourceByPath I can't get the paragraphs that are currently active on this contentType, I only get a reference to their ID but I can't include them the same way I do when using getResourceFromContext with the params object. Would be great to have the params object enabled here to get reference fields or entities like paragraphs the same way

**Comment by shadcn** [comment]
@je34429 Can you add the code for getResourceByPath vs getResourceFromContext please?

**Comment by je34429** [comment]
sure!, this works on SSR (getServerSideProps):

const node = await getResourceFromContext('node--page, context, {
    include: `uid,
                    field_a,
                    field_b,
                    field_c,
                    ...
                 `
 });

this doesn't work on ISG (getStaticProps):

const node = await getResourceByPath( "/home", "node--page", {
   include: `uid,
                  field_a,
                  field_b,
                  field_c,
                  ...
                `
 });

**Comment by shadcn** [comment]
Ah you know what! This looks like an error in the docs. `getResourceByPath` does not need the type.

```jsx
const node = await getResourceByPath("/home", {
    params: {
      include: "uid, field_a, field_b, field_c,",
    },
  })
```

**Comment by je34429** [comment]
OMG!!!!, man you are the best!! thank soooo much!
