### ISSUE TITLE
Cannot read property 'default_langcode' of undefined

### ISSUE THREAD

**Issue by iliamrv** [chapter-three/next-drupal#9]
hi,

I use Drupal 9.2.2 and Next.js module. The problem after I install and configure next-drupal package and go to node page, I see the next message:

"Cannot read property 'default_langcode' of undefined"

It is possible that JSON doesn't provide data that next-drupal request. How can I resolve this issue? Thanks

**Comment by arshad** [comment]
Let's check a few things.

- Have you configured a preview route? 
- Is path aliases configured for the node type?
- Have you applied the path for subrequests.module? See https://next-drupal.org/docs/quick-start#apply-patch

**Comment by je34429** [comment]
hey there, having the same issue, I'm trying to run the project without typescript, only js but I can't find the problem

**Comment by arshad** [comment]
Can you tell me more about the error message? Which line..etc?

**Comment by arshad** [comment]
We just tagged a new release with a potential fix. Can you pull the latest `next-drupal` and try again? Thank you.

**Comment by je34429** [comment]
thank you very much man I managed to solve the problem with a different config on drupal, not sure why but reinstalling and reconfiguring modules fixed the problem. Anyway I will definitely try out this new release.

best regards

**Comment by arshad** [comment]
Awesome. I'm going to close this issue. Feel free to reopen or create a new one if you have any question. Thank you.
