### ISSUE TITLE
accessToken is not pass to getResourceByPath in getResourceFromContext (get-resource.ts)

### ISSUE THREAD

**Issue by Tuestunmanan** [chapter-three/next-drupal#91]
`diff --git a/node_modules/next-drupal/src/get-resource.ts b/node_modules/next-drupal/src/get-resource.ts
index 6f1182e..e6edda7 100644
--- a/node_modules/next-drupal/src/get-resource.ts
+++ b/node_modules/next-drupal/src/get-resource.ts
@@ -54,6 +54,7 @@ export async function getResourceFromContext<T extends JsonApiResource>(
       resourceVersion: previewData?.resourceVersion,
       ...options?.params,
     },
+    ...options
   })
 
   // If no locale is passed, skip entity if not default_langcode.`

**Comment by shadcn** [comment]
This has been fixed in the latest release. https://next-drupal.org/docs/reference/getresourcebypath

You can now use authentication using the `withAuth` option.
