### ISSUE TITLE
Using a fake JSON API to test components and allow decoupled design

### ISSUE THREAD

**Issue by theodorosploumis** [chapter-three/next-drupal#92]
I am wondering if we could use a fake JSON API like [json-server](https://www.npmjs.com/package/json-server) with this project so we test the components without a Drupal backend as also as allow frontent designers to create components in a decoupled way.

- Does this make sense?
- Do the "Basic Starter" components support this or they are strongly tighten to the Drupal JSON API?
- What other options exist to allow API mocking for "free-of-Drupal" components development?

**Comment by shadcn** [comment]
Hmm interesting. I can see this enabling front-end teams to work independently from Drupal. I'll look into this.

**Comment by theodorosploumis** [comment]
I found that https://www.npmjs.com/package/drupal-jsonapi-extractor can be very helpful here. Will give it a try and come back soon.

**Comment by backlineint** [comment]
Doing some issue triage. Generating JSON:API responses either manually or using https://www.npmjs.com/package/drupal-jsonapi-extractor and then using something like json-server or MSW (https://mswjs.io/) to run a mock server locally should be possible. But for things like complicated json:api parameters, or even media references I worry that it would become impractical pretty quickly.

If the goal is to develop components in isolation, I'd instead suggest using Storybook with Next.js. The following documentation should help you get started: https://storybook.js.org/docs/get-started/nextjs There really shouldn't be much Next.js for Drupal specific that you'll need to do - the process should be similar to using Storybook with any Next.js site.

Closing this as not planned, but if anyone runs into Next.js for Drupal specific Storybook issues, let us know.
