### ISSUE TITLE
getEntityFromRouteMatch returns null on revision routes

### ISSUE THREAD

**Issue by j4-m** [chapter-three/next-drupal#95]
`NextEntityTypeManager::getEntityFromRouteMatch` falsely returns null with Drupal 9.3.6. This is because the parameter taken from the route match is being upcasted to a `Node` but it is being treated as though it is the revision ID:

```diff
if (in_array($route_match->getRouteName(), $revision_routes) && in_array('node', $entity_types_ids)) {
-  return $this->entityTypeManager->getStorage('node')->loadRevision($route_match->getParameter('node_revision'));
+  return $route_match->getParameter('node_revision');
}
```

**Comment by shadcn** [comment]
@j4-m Can you try the dev version of `next.module` and see if this fixes it. We made some improvement in #78.

https://github.com/chapter-three/next-drupal/blob/58f1150e750d860cb62b60f28edca3673dbb3c68/modules/next/src/NextEntityTypeManager.php#L64-L89

**Comment by j4-m** [comment]
Oh nice one @shadcn I will give it a go. The other problem I have just ran into, using Content Moderation if you haven't already guessed, is that when the preview URL includes `rel:latest-version` JSON:API will return the latest version regardless of whether it's published or not but it would seem you have also done some work on that on the dev version...

**Comment by j4-m** [comment]
@shadcn the dev release has solved all my problems so I'll sit tight for a new release. Thanks for your help.
